:noaudio:
:toc2:

= Business Activities Monitoring Lab

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

<<usecase3>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented using Detour, WireTap Pattern
* Add your own Intercept strategy
* Use wildcard & regexp to filter the endpoints to be intercepted

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Use Detour & WireTap pattern

- Develop a Junit Test case covering the Detour. As Detour does not correspond to a DSL word, it should be implemented using content based routing on a condition which is evaluated when a message
  is received to forward or detour the content to a producer or group of processors. The condition could be defined as a boolean value defined in a class
- Develop a Junit Test case covering the WireTap Pattern. Design 2 methods where you will check that the students have implemented a wiretap using a copy of the original exchange but also where
  they have created a new exchange.

Remarks: For the 2 classes to be developed, use as target endpoint where the information to be collected should be send a topic. Create a common Camel Route which is used to grab the messages
  published within the topic and validate the number of messages received like also their content

[[usecase2]]
=== Add some interceptors

- Develop 2 Camel routes where all the messages are intercepted and publishes in a topic. The interceptor will create a new message containing an id to identify the message, a property referring to the application
  processing the message, the content of the body collected and the breadCrumbId which is a global application identifier.

[[usecase3]]
=== Use wildcard & regexp to filter the endpoints to be intercepted

- Base on the previous use case, develop an interceptor where you will intercept only the messages coming from some consumer endpoints using a wildcard.
- Idem but now using a regular expression and where the interceptor is applied to the producer where the message is send.

ifdef::showScript[]


endif::showScript[]
