:scrollbar:
:data-uri:
:sourcedir: ../code/security-ws/src/test/java
:toc2:
:linkattrs:

== Business Activities Monitoring Intercept Lab

.Goals
* Configure your local environment to develop a number of use cases related to business monitoring with intercepts
* Gain experience using Detour and Wire Tap patterns
* Add your own intercept strategy
* Use a wildcard and a regular expression to filter the endpoints to be intercepted

.Prerequisites
* Experience with Java, Spring, and Maven
* Experience with Camel development using Red Hat JBoss Fuse

.Use Cases
In this lab, you examine the following use cases:

* <<usecase1>>
* <<usecase2>>
* <<usecase3>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:

== Prepare Lab Environment
===  Install Lab Assets

[cols="2,1,1",options="header"]
|===
| Software | Version | Notes

| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|===

=== Install Lab Project

. Download and install locally the latest release of the project published in the {course_git_repo} GitHub repository. 
. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Use Detour and Wire Tap Patterns

In this use case, you develop two JUnit test cases--one using the Detour pattern and the other using the Wire Tap pattern.

. Develop a JUnit test case using the Detour pattern.
* Because Detour does not correspond to a DSL word, implement your test case using content-based routing.
* Use a condition that is evaluated when a message is received to forward or detour the content to a producer or group of processors.
* The condition can be defined as a boolean value defined in a class.

. Develop a JUnit test case using the Wire Tap pattern, consisting of two methods:
* For the first method, employ a wiretap using a copy of the original exchange.
* For the second method, employ a wiretap using a new exchange.

[TIP]
====
* For the two classes you develop, use a target endpoint where the information to be collected is sent to a topic.
* Create a common Camel route that is used to extract the messages published to the topic.
* In the Camel route, validate that the correct number of messages is received and the content is accurate.
====

[[usecase2]]
== Add Interceptors

In this use case, you develop two Camel routes where all of the messages are intercepted and published to a topic.

. Make sure that the interceptor creates the following:
** A message containing an ID to identify the message
** A property referring to the application processing the message
** The content of the body collected
** The `breadCrumbId`, which is a global application identifier


[[usecase3]]
== Use Wildcard and Regular Expression to Filter Intercepted Endpoints

In this use case, you use wildcard and regular expression patterns to filter the endpoints to be intercepted.

. Develop an interceptor that intercepts only the messages coming from select endpoints, using wildcards for the filtering.

* This exercise is identical to the previous one, except that you use a regular expression instead of a wildcard and you apply the interceptor to the producer that sent the message.

