:scrollbar:
:data-uri:
:sourcedir: ../code/security-ws/src/test/java
:toc2:
:linkattrs:

== Business Activities Monitoring Notification Lab

.Goals
* Configure your local environment to develop and explore use cases related to business monitoring notifications
* Implement an event notification to collect Camel route information
* Register an MBean to monitor an endpoint

.Prerequisites
* Experience with Java, Spring, and Maven
* Experience with Camel development using Red Hat JBoss Fuse

.Use Cases
In this lab, you examine two use cases:

* <<usecase1>>
* <<usecase2>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:

== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|====

=== Install Lab Project

. Download and install locally the latest release of the lab project published in the {course_git_repo} GitHub repository. 
. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.

[[usecase1]]
== Implement Event Notification to Collect Camel Route Information

In this use case, you create a class that extends the `EventNotifierSupport` class.

. Generate a message that you publish within the log file when a Camel Exchange is created and completed.
. In the message, include a Camel `ExchangeId`, a header with the `routeId`, and a customized message.
. Using the previous example, use `ExchangeSentEvent` to calculate how much time it takes to call an HTTP endpoint exposed by another Camel route.
. Use a delayer in the Camel route to delay the response.


[[usecase2]]
== Register MBean to Monitor Endpoint

In this use case, you create a custom endpoint and register the endpoint as an MBean using Spring JMX. The use should meet the following criteria:

* The custom endpoint must provide an attribute to return a dummy value and an operation showing the URL of the endpoint.
* The test case must verify that the customer endpoint as well as the MBean are used in a Camel route.
* The test case must also verify that you can query the attribute and the operation of the registered JMS object using the JMX Server.

