:noaudio:
:toc2:

= Business Activities Monitoring Lab

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

.Goals
* Configure your local environment to develop and resolve use cases
* Implement an Event Notification to collect Camel Route information
* Register a MBean to monitor an endpoint

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Implement an Event Notification to collect Camel Route information

- The goal of this use case is to create a class which extends the EventNotifierSupport class and where you will generate a message that you will publish within the log file when a Camel
  Exchange is created and when it is also completed. The message must include the Camel ExchangeId, a header with the routeId and a customized message

- Repeat the previous but use the ExchangeSentEvent to calculate how much time it tooks to call an HTTP endpoint exposed by another Camel route. Use a delayer with the Camel route to slow dow the process
  generating the response.


[[usecase2]]
=== Register a MBean to monitor an endpoint

- The goal of this use case is to create a new custom endpoint where you will register also the endpoint as a MBean using Spring JMX. The custom endpoint must provide an attribute to return a dummy value and
  an operation showing the url of the endpoint. The test case must verify that the customer endpoint like also the MBean are used in a Camel Route and that you can query using the JMX Server
  the JMS object registered (attribute and operation).

ifdef::showScript[]


endif::showScript[]
