:scrollbar:
:data-uri:
:noaudio:


== Detour Wiretap

* Goal: Route information to another destination
* Implement using Wiretap EIP pattern in FireForget mode
* Message copied or created

* Wiretap example:
+
[source,text]
----
 from("direct:start")
     .to("log:foo")
     .wireTap("seda:tap")
     .bean(MyBean.class)
     .to("mock:result");

 from("seda:tap")
     .to("mock:tap");
----
* Use condition to detour traffic
+
* Detour example:
+
[source,text]
----
from("direct:start")
.choice()
  .when().method("control", "isDetour")
     .to("mock:detour").end()
  .to("mock:result");
----

ifdef::showscript[]

Transcript:

By using the Wiretap EIP and the Detour logic you can reroute messages to another destination. The Wiretap EIP that is provided with Camel can be sent to another route, as shown in the example. This route can send the exchange to a mock endpoint that can be part of a unit test. Using the Wiretap EIP, you can either send a copy of the exchange or create a new exchange populated with different values. There is no built-in detour EIP, but under certain conditions the functionality can be implemented as shown with a choice function to send the exchange to a detour route. 


endif::showscript[]
