:noaudio:

[#healthcheck]
== Health Check

* Goal : Control/check if endpoints (producer/consumer) are still healthy
* Require camel-metrics component and/or Dropwizard Metrics API
* Allow to register some beans controlling the status of the endpoints, route or context
+
.Camel Context Health Example
[source]
----
public class CamelHealthCheck extends HealthCheck {

    @Override
    protected Result check() throws Exception {
        Result result = checkCamelContext();
        if (!result.isHealthy()) {
            return result;
        }

    private Result checkCamelContext() {
        LOGGER.debug("Checking context [{}] of type [{}]", camelContext.getName(), camelContext.getClass());
        ServiceStatus status = camelContext.getStatus();
        if (!status.isStarted()) {
            return Result.unhealthy(String.format("CamelContext [%s] is not running", camelContext.getName()));
        }
        return Result.healthy();
    }
----

ifdef::showscript[]
[.notes]
****

== Health Check

The goal of health checks is to ensure that the camel context has started and the Camel endpoints are healthy. Apache Camel comes with health check integrated with Spring Boot if you are using actuators. The health check does a coarse grained check to ensure that Camel started up properly. As show in the example, you can write your own check by implementing the HealthCheck interface or by extending AbstractHealthCheck which provides some useful methods.

****
endif::showscript[]