:scrollbar:
:data-uri:
:noaudio:


== Health Check

* Goal: Control/check if producer and consumer endpoints are healthy
* Requires Camel metrics component or Dropwizard Metrics API
* Allows registering beans to control status of endpoints, route, and context

* CamelContext health example:
+
[source,text]
----
public class CamelHealthCheck extends HealthCheck {

    @Override
    protected Result check() throws Exception {
        Result result = checkCamelContext();
        if (!result.isHealthy()) {
            return result;
        }

    private Result checkCamelContext() {
        LOGGER.debug("Checking context [{}] of type [{}]", camelContext.getName(), camelContext.getClass());
        ServiceStatus status = camelContext.getStatus();
        if (!status.isStarted()) {
            return Result.unhealthy(String.format("CamelContext [%s] is not running", camelContext.getName()));
        }
        return Result.healthy();
    }
----

ifdef::showscript[]


Transcript:

The goal of health checks is to ensure that the CamelContext has started and the Camel endpoints are healthy. If you are using actuators, Apache Camel comes with health checks integrated with Spring Boot. A health check does a coarse-grained check to ensure that Camel started properly. As shown in the example, you can write your own health check by implementing the HealthCheck interface or by extending AbstractHealthCheck, which provides some useful methods.


endif::showscript[]
