:scrollbar:
:data-uri:
:noaudio:


== Jolokia and JMX

* Jolokia is JMX-HTTP bridge
* Use `@JsonMbean` to integrate with Jolokia
* Works also with JMX support libraries that use ModelMBeans under hood
* Serialization of complex Java Beans is more powerful with JSON MBeans

* Jolokia example:
+
[source,java]
----
private List<ObjectName> registeredMBeans;
public static final  String JOLOKIA_IT_DOMAIN           = "jolokia.it";

public void start() {
     registeredMBeans = registerMBeans(ManagementFactory.getPlatformMBeanServer(), JOLOKIA_IT_DOMAIN);
     MBeanServer jolokiaServer = getJolokiaMBeanServer();
     if (jolokiaServer != null) {
         registeredJolokiaMBeans.addAll(registerJsonMBeans(jolokiaServer, JOLOKIA_IT_JSONMBEAN_DOMAIN));
     }
 }

@JsonMBean()
    public static class JsonAnnoTest implements JsonAnnoTestMXBean {

        public Chili getChili() {
            return new Chili("Bhut Jolokia",1000000);
        }

    }
----

ifdef::showscript[]

Transcript:


JMX 1.4 introduced MXBeans, which allow for arbitrary data to be translated into so-called OpenData that is accessible via JMX. For example, arbitrary JavaBeans are translated into a CompositeData structure with property names as keys and OpenData values.

Jolokia provides the `@JsonMBean` annotation for marking an MBean as a JSON MBean. Such an MBean, if registered at the Jolokia MBeanServer, creates a proxy on the PlatformMBeanServer where every complex value gets translated into plain strings in JSON format. This is true for attributes, operation return values, and arguments. That way, a JSR-160-based console (like JConsole) can easily access complex data types exposed by custom MBeans. JSON MBeans work for Java 6 and newer.


endif::showscript[]
