:noaudio:

[#topics]
== Module Topics

In this module you will learn about the following topics which cover the Business Activities Monitoring concepts :

* Use EIP patterns to collect the Business information
* Intercept Camel Exchanges using the consumer, producer or a condition
* Collect information using Event notification mechanism
* Integrate your Camel project with ELK
* Extend the JMX Layer to expose your own MBeans
* Setup some controls with Health Check
* Integrate your Camel Routes with SNMP Traps or Nagios Management Platform

ifdef::showscript[]
[.notes]
****

== Module Topics

This module covers different technologies that you can use within a project to Monitor the activities related to the Business. These activities are in fact, the
message, body or headers information transported through the different Camel Routes. The techniques to be used can be classified from less invasive to more invasive depending
if you prefer to use a EIP pattern, interceptor or extend the code using an Event Notification approach. through this module, we will investigate the different
mechanisms and explain how to use it.

****
endif::showscript[]