:noaudio:

[#eventnotification]
== Event Notification

* Goal : Being notified about an event, change done to a Camel Exchange
* Support : exchange send, complete, fail, create, redeliver, Route added, started
+
.Notification event example
[source,java]
----
MyEventNotifier extends EventNotifierSupport {

   AtomicInteger routeStartedEvent = new AtomicInteger();
   AtomicInteger routeStoppedEvent = new AtomicInteger();
   AtomicInteger camelContextStoppingEvent = new AtomicInteger();

   @Override
   public void notify(EventObject event) throws Exception {
       if (event instanceof RouteStartedEvent) {
           routeStartedEvent.incrementAndGet();
       } else if (event instanceof RouteStoppedEvent) {
           routeStoppedEvent.incrementAndGet();
       } else if (event instanceof CamelContextStoppingEvent) {
           camelContextStoppingEvent.incrementAndGet();
       }
   }

   @Override
   public boolean isEnabled(EventObject event) {
       return true;
   }
----

ifdef::showscript[]
[.notes]
****

== Event Notification
To be notified when an event occurs in reference to a Camel exchange, use the EventNotifierSupport class. You can be informed about events relating to an exchange sunch as route start and stops as well as when an exchange gets sent. To enable this, create a class that extends EventNotifierSupport and override its notify method so you can be notified when events of interest occur. This feature can be used to calculate how long it takes to send and receive replies when sending to an external endpoint. This would allow the programmer to isolate bottlenecks in the code or determine which services have the highest latency.

****
endif::showscript[]