:scrollbar:
:data-uri:
:toc2:
:linkattrs:
:sourcedir: ../code/security-ws/src/test/java


== REST Security with Basic Authentication and Role Lab

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience using basic authentication for a Jetty server
* Restrict access to specific paths based on the user's role
* Develop a RESTful service project and secure it
* Expose RESTful services using a Camel route
* Experiment with `@RolesAllowed` JAX-RS annotation
* Configure a Jetty endpoint to authenticate an HTTP user request using `HashLoginService`
* Send a HTTP request using an Apache Commons HttpClient

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with RESTful services and HTTP basic authentication
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you examine three use cases:

* <<usecase1>>
* <<usecase2>>
* <<usecase3>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:

== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to explore the use cases, import the project into a new JBoss Developer Studio workspace.

[[usecase1]]
== Explore Camel REST DSL Using Jetty and Basic Authentication

In this use case, you develop a JUnit test case using the `org.jboss.fuse.security.camel.basic.BasicAuthRESTCamelDSLJettyHashLoginTest.java` class that extends the `BaseJettyTest` class.

. Set up an Apache Camel route.
. Use the REST DSL syntax to expose a RESTful service for the `/say/hello/{id}` path.
* `{id}` represents the ID of the user. It is used in the `hello` response to the HTTP request.

. Configure the Jetty component using the `SecurityHandler` Jetty class to authenticate the user HTTP request using basic authentication and Base64.

* The `org.eclipse.jetty.security.SecurityHandler` is configured to request basic authentication and use the `org.eclipse.jetty.security.HashLoginService` class to authenticate the user.

. Use the `src/test/resources/org/jboss/fuse/security/basic/myrealm.props` properties file to define the users.
* This properties file contains a list of users defined in this format:
+
[source,text]
----
user: password, role
----

. Create `UsernameWrongPasswordTest()` and `UsernameTest()` Java methods to test the credentials of a user presenting an invalid or valid password, respectively.
. Use the `HttpClient` method  to issue the HTTP request against the RESTful endpoint started by Apache Camel using the `callRestEndpoint()` method.
. Verify that a `200` (OK) HTTP status code is returned when the user is authenticated.
. Using `Assert` method calls, verify that the REST service replies with a `"Hello World " + user` when the user is authenticated.
. Verify that a `401` (Unauthorized) HTTP status code is returned when invalid credentials are supplied.

NOTE: The `BaseJettyTest` class extends the `CamelTestSupport` class.

[[usecase2]]
== Explore Camel REST DSL Using Jetty, Basic Authentication, and Role Access Restrictions

This use case expands on the previous use case. You develop it using the `org.jboss.fuse.security.camel.basic.role.BasicAuthRESTCamelDSLJettyRoleConstraintTest` Java class.

. Expose two RESTful services:

* `/say/hello/{id}`
* `/say/bye/{id}`

. Restrict, or constrain, access to the paths:

* `/say/hello/*` should be accessible to users having either or both of the `user` or `admin` roles
* `/say/bye/*` should be accessible only to users having the `admin` role

. Define a `ConstraintMapping` list and pass it as a parameter to the `ConstraintSecurityHandler` Jetty class when you develop the `SecurityHandler`.

. Develop three methods for the use case based on this information:
+
[cols="2",options="header"]
|====
|Method
|Description
|`shouldSayHelloTest()`
a|HTTP code: `200`

Response message asserted: `"Hello World " + user`

user: donald, password: duck, role: user
|`sayByeNotAllowedForUserRoleTest()`
a|HTTP code: `403`

user: donald, password: duck, role: user

|`sayByeAllowedForAdminRoleTest()`
a|HTTP code: `200`

Response message asserted: `"Bye" + user`

user: mickey, password: mouse, role: admin
|====

[[usecase3]]
== Explore CXF JAX-RS Service Using `@RolesAllowed` and Basic Authentication

In this use case, instead of employing role-constrained Jetty paths, you leverage the `@RolesAllowed` JAX-RS annotation. You restrict access on a REST path to a specified role with a Java API for RESTful Web Services (JAX-RS) annotation. You develop this project using the Apache CXF Framework.

. Create the `org.jboss.fuse.security.cxf.role.BasicAuthCxfRSRoleTest` class that extends the `BaseCXF` class.

. In this class, create a static `Server` class using `public static class Server extends AbstractBusTestServerBase`.
* This `Server` class is responsible for creating and starting the CXF server and exposes the RESTful service.

. Add a `Static` block of this class and have it set up the bus using the Spring XML `serverConfig.xml` file that you package in the `src/test/resources/org/jboss/fuse/security/basic/config` directory.

* The Spring beans file contains the definition of the beans required to instantiate a Jetty instance with a security handler. 
* The skeleton of the project already contains the declaration of the beans. 
* Because the file already contains the definition of the beans, you do not need to define them to configure the `org.eclipse.jetty.security.HashLoginService`, `org.eclipse.jetty.util.security.Constraint`, and `org.eclipse.jetty.security.ConstraintMapping` objects.

. Declare the beans, as you did for the first use case.

. In the `run()` method of a static `Server` class, configure the JAX-RS Service:
.. Instantiate the `JAXRSServerFactoryBean`.
.. Set up the provider and resources for the class exposing the RESTful service:

* `setResourceClasses`: `CustomerServiceWithRole.class`
* `setResourceProvider`: `CustomerServiceWithRole.class`, `new SingletonResourceProvider(new CustomerServiceWithRoleImpl())`
* `setAddress`: `http://localhost:PORT/`

. Register the `org.apache.cxf.interceptor.security.SecureAnnotationsInterceptor` class as an `inInterceptor` with a `securedObject` property.
* This interceptor scans classes containing the `@RolesAllowed` annotation.

. Create the `org.jboss.fuse.security.cxf.service.CustomerServiceWithRole` interface with these JAX-RS annotations:
+
[source,json]
----
@Path("/customerservice/")
public interface CustomerServiceWithRole {

    @GET
    @Path("/customers/{id}/")
    Customer getCustomer(@PathParam("id") String id);

    @PUT
    @Path("/customers/")
    Response updateCustomer(Customer customer);

    @POST
    @Path("/customers/")
    @RolesAllowed({"admin"})
    Response addCustomer(Customer customer);

    @DELETE
    @Path("/customers/{id}/")
    Response deleteCustomer(@PathParam("id") String id);

}
----

. Add the `@RolesAllowed` annotation for the `user` role  to the `getCustomer` method.

* The code implementing the service is available at `org.jboss.fuse.security.cxf.service.CustomerServiceWithRoleImpl.java`.

. Create two methods--the first to test a user with the `user` role to access the `/customerservice/customers/123` REST endpoint and the second with a role that is not allowed.
+
[cols="2",options="header"]
|===
|Method |Description
|`allowForDonaldUserCorrectRoleTest()`
a|HTTP code: `200`

Response message asserted: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Customer><id>123</id><name>John</name></Customer>`

user: donald, password: duck, role: user, realm: myrealm
|`deniedForUmperioNotCorrectRole()`
a|HTTP code: `500`

Response message asserted: `Unauthorized`

user: umperio, password: bogarto, role: author
|===


ifdef::showscript[]

:numbered!:

== Teacher Information

* Time estimated: 2d

* How to evaluate the student's solution:

** Verify that the JUnit tests are passing successfully.
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, etc.)
** Review the solutions proposed by the student to resolve the different use cases.
** For each use case, verify that the SOAP request and response populated. They should be comparable to what you can find in the `output/ws-*` corresponding folder.

endif::showscript[]
