:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= REST Security with Basic Authentication and Role Lab

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about Basic Authentication Jetty Server
* Restrict the access to certain paths based on the role of the user
* Design RESTfull Service project and secure it
* Expose the RESTfull services using a Camel route
* Configure the Jetty Endpoint to authenticate the HTTP User request using the HashLoginService
* Send the HTTP Request using Apache Commons HttpClient

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with RESTfull & HTTP Basic Authentication
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.


== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Camel REST DSL with Jetty Component & Basic Authentication

The goal of this use case is to design a Junit Test case using the class +org.jboss.fuse.security.camel.basic.BasicAuthRESTCamelDSLJettyHashLoginTest.java+ which extend the class +BaseJettyTest+ class.

Within this project, you will setup an Apache Camel Route, use the REST DSL syntax to expose a RESTfull service according to this path +/say/hello/{id}+ where {id} represents the user for which you would like to say hello
. Next, you will configure the Jetty Component using the Jetty SecurityHandler class to authenticate the user HTTP request using Basic Authentication & Base64.

The +org.eclipse.jetty.security.SecurityHandler+ will be configured to request Basic Authentication and will use the +org.eclipse.jetty.security.HashLoginService+ class to authenticate
the user using a properties file called +src/test/resources/org/jboss/fuse/security/basic/myrealm.props+. This property file will contain a list of users defined as such :
user: password, role.

For this use case, you must create 2 java methods +UsernameWrongPasswordTest()+ and +UsernameTest()+ to test the credentials of a user having either a correct or wrong password.
Use the method HTTPClient to issue the HTTP request against the RESTFull Endpoint started by Apache Camel with the help of this method +callRestEndpoint()+.
Verify that you get a HTTP Code 200 when the user has been authenticated correctly and that the REST Service replies with this response +"Hello World " + user+ that you will validate with Assert methods.
A code 401 should be returned for a not allowed user.

NOTE: The +BaseJettyTest+ class extends the +CamelTestSupport+ class

[[usecase2]]
=== Camel REST DSL with Jetty Component, Basic Authentication & Role Access Restriction

This usecase extends the previous but will be designed using the java class +org.jboss.fuse.security.camel.basic.role.BasicAuthRESTCamelDSLJettyRoleConstraintTest+. We will expose two RESTFull Services:

- +/say/hello/{id}+
- +/say/bye/{id}+

and restrict (or constraint) the access to the paths as such

- +/say/hello/*+ for users having the role user or admin
- +/say/bye/*+ for users having the role admin only

To achieve this goal, you will define a List of ConstraintMapping that you will pass as parameter to the Jetty +ConstraintSecurityHandler+ class when you will design the +SecurityHandler+.

There are 3 methods to be developed for this usecase based on the following information :

[cols="2*", options="header"]
|===
|Method
|Description

|shouldSayHelloTest()
a|HTTP code: 200

Response message asserted: "Hello World" + user

user: donald, password: duck, role: user

|sayByeNotAllowedForUserRoleTest()
a|HTTP code: 403

user: donald, password: duck, role: user

|sayByeAllowedForAdminRoleTest()
a|HTTP code: 200

Response message asserted: "Bye" + user

user: mickey, password: mouse, role: admin

|===


ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
