:scrollbar:
:data-uri:
:toc2:
:linkattrs:
:sourcedir: ../code/security-ws/src/test/java

== REST Security with JAAS

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience using Jetty and the Java API for Authentication and Authorization Service (JAAS)
* Develop a RESTful service project and secure it
* Expose RESTful services using a Camel route and CXF RS
* Configure a Jetty endpoint to authenticate the HTTP user request using JAAS and a `JAASLoginService` class

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with RESTful services and HTTP basic authentication
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you examine two use cases:

* <<usecase1>>
* <<usecase2>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:

== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
| link:http://sourceforge.net/projects/soapui/files/[SoapUI^] | Latest version | Optional
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to explore the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Explore Camel REST DSL Using Jetty, Basic Authentication, and JAAS

This use case is a variation of the basic authentication use case you developed in the _REST Security with Basic Authentication and Role Lab_. In this lab, you replace the `HashLoginService` Jetty class with the `org.eclipse.jetty.jaas.JAASLoginService` class. You register this class as a realm with its corresponding JAAS file to install the JAAS module responsible for finding and authenticating the user.

. Set up an Apache Camel route using the REST DSL syntax to expose a RESTful service for the `/say/hello/{id}` path.
* `{id}` represents the ID of the user. It is used in the `hello` response to the HTTP request.

. Configure Jetty using the `org.eclipse.jetty.security.SecurityHandler` Jetty class to authenticate a user HTTP request using basic authentication and Base64.

. Use the `org.eclipse.jetty.jaas.JAASLoginService` class to authenticate the user using `myrealm` as the realm and `propsFileModule` as the JAAS login module.

. Create the `org/jboss/fuse/security/basic/myrealm-jaas.cfg` file.
. Define the `propsFileModule` module with the following values:
+
[source,text]
----
org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
file="src/test/resources/org/jboss/fuse/security/basic/myrealm.props";
----

. Configure the `java.security.auth.login.config` key using a Java `System.Property` with the value of the `org/jboss/fuse/security/basic/myrealm-jaas.cfg` JAAS configuration file.

. Create `UsernameWrongPasswordTest()` and `UsernameTest()` Java methods in the `org.jboss.fuse.security.camel.jaas.BasicAuthRESTCamelDSLJettyJaasTest` class to test the credentials of a user presenting an invalid or valid password, respectively.

. Use the `HttpClient` method to issue the HTTP request against the RESTful endpoint started by Apache Camel using the `callRestEndpoint()` method.

. Verify that a `200` (OK) HTTP status code is returned when the user is authenticated.
. Using `Assert` method calls, verify that the REST service replies with a `"Hello World " + user` when the user is authenticated.
. Verify that a `401` (Unauthorized) HTTP status code is returned when invalid credentials are supplied.

[[usecase2]]
== Explore CXF JAX-RS Using Jetty Server and JAAS

In this use case, you use JAAS with a module that gets its list of users from a properties file. This JAAS module checks the user credentials supplied by the HTTP client, which uses basic authentication.

Similar to the previous use case in this lab, you reuse the code developed with CXFRS from the _REST Security with Basic Authentication and Role Lab_. You leverage the `org.eclipse.jetty.jaas.JAASLoginService` class, instead of the `org.eclipse.jetty.security.HashLoginService` class.

. Develop a `JaasCxfRSTest` Java class based on the `BasicAuthCxfRSRoleTest` class source code.
. Create a `ServerJAASConfig.xml` file  using the `org.eclipse.jetty.jaas.JAASLoginService` bean with the `propsFileModule` JAAS login module and `myrealm` realm.
. Configure the Spring bus to use this configuration file.
. Adapt the `JAXRSServerFactoryBean` bean to use `CustomerService` and `CustomerServiceImpl`.
. Remove the `SecureAnnotationsInterceptor`.
. Set up the `java.security.auth.login.config` system property key.

ifdef::showscript[]

:numbered!:


== Teacher Information

* Time estimated: 2d

* How to evaluate the student's solution:

** Verify that the JUnit tests are passing successfully.
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, etc.)
** Review the solutions proposed by the student to resolve the different use cases.
** For each use case, verify that the SOAP request and response populated. They should be comparable to what you can find in the `output/ws-*` corresponding folder.


endif::showscript[]
