:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= REST Security with JAAS

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

* Configure your local environment to develop and resolve use cases
* Become more experimented about JAAS & Jetty
* Design RESTfull Service project and secure it
* Expose the RESTfull services using a Camel route
* Configure the Jetty Endpoint to authenticate the HTTP User request using JAAS & JAASLoginService class

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with RESTfull & HTTP Basic Authentication
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Camel REST DSL with Jetty Component, Basic Authentication & JAAS


[[usecase2]]
=== CXF JAXRS with Jetty Server & JAAS


ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
