:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= REST Security with JAAS

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

* Configure your local environment to develop and resolve use cases
* Become more experimented about JAAS & Jetty
* Design RESTfull Service project and secure it
* Expose the RESTfull services using a Camel route or CXF RS
* Configure the Jetty Endpoint to authenticate the HTTP User request using JAAS & JAASLoginService class

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with RESTfull & HTTP Basic Authentication
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Camel REST DSL with Jetty Component, Basic Authentication & JAAS

This usecase is a variation of the Basic Authentication use case 1 that you have designed within the Lab 1. What is different is that we will replace the HashLoginService class of Jetty with the
+org.eclipse.jetty.jaas.JAASLoginService+ class and that you will register a Realm with its corresponding JAAS file to install the JAAS Module responsible to find the user and authenticate it.

Within this project, you will setup an Apache Camel Route, use the REST DSL syntax to expose a RESTfull service according to this path +/say/hello/{id}+ where {id} represents the user for which you would like to say hello
. Next, you will configure the Jetty Component using the Jetty SecurityHandler class to authenticate the user HTTP request using Basic Authentication & Base64.

The +org.eclipse.jetty.security.SecurityHandler+ will be configured to request Basic Authentication and will use the +org.eclipse.jetty.jaas.JAASLoginService+ class to authenticate
the user using as realm name +myrealm+ and as jaas login module +propsFileModule+.

Create the +org/jboss/fuse/security/basic/myrealm-jaas.cfg+ file and define the module +propsFileModule+ with the following values :

[source]
----
org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
file="src/test/resources/org/jboss/fuse/security/basic/myrealm.props";
----

Next, configure, using Java System Property, the key "java.security.auth.login.config" with the value of the JAAS Config file +org/jboss/fuse/security/basic/myrealm-jaas.cfg+

Finally, create 2 java methods +UsernameWrongPasswordTest()+ and +UsernameTest()+ within the class +org.jboss.fuse.security.camel.jaas.BasicAuthRESTCamelDSLJettyJaasTest+ to test the credentials of a user having either a correct or wrong password.
Use the method HTTPClient to issue the HTTP request against the RESTFull Endpoint started by Apache Camel with the help of this method +callRestEndpoint()+.

Verify that you get a HTTP Code 200 when the user has been authenticated correctly and that the REST Service replies with this response +"Hello World " + user+ that you will validate with Assert methods.
A code 401 should be returned for a not allowed user.

[[usecase2]]
=== CXF JAXRS with Jetty Server & JAAS

The goal of this use case is to use the Java Api for Authentication and Authorization Service with a Module using users defined in a property file. This JAAS Module will check the user credential passed by the HTTP client
performing the Basic Authentication

So, like the previous use case, you will reuse the use case developed with CXFRS within the Lab 1 but you will use the +org.eclipse.jetty.jaas.JAASLoginService+ instead of the +org.eclipse.jetty.security.HashLoginService+
class.

In order to develop this project, you will develop a new Java Class +JaasCxfRSTest+ based on the code of the class +BasicAuthCxfRSRoleTest+ and perform the following modifications :

- Create a new file "ServerJAASConfig.xml" where you will use the +org.eclipse.jetty.jaas.JAASLoginService+ bean with the login Module name "propsFileModule" and realm "myrealm"
- Configure the Spring Bus to use this config file
- Adapt the +JAXRSServerFactoryBean+ to use +CustomerService+ and +CustomerServiceImpl+
- Remove the +SecureAnnotationsInterceptor+
- Setup the System property Key +java.security.auth.login.config+

ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
