:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= TLS with Mutual Authentication

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

* Configure your local environment to develop and resolve use cases
* Become more experimented about TLS & mutual authentication
* Design RESTfull Service project and secure it
* Expose the RESTfull Service using Camel Rest DSL & Netty4 HTTP component
* Setup Mutual TLS using Apache CXF Rest framework with Jetty

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with RESTfull & HTTP Basic Authentication
* Basic knowledge about PKI, encryption with TLS/SSL
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

=== Keys and certificates

Follow these instructions in order to create the Private/Public keys of the user and the server, their corresponding certificate and trust them (Client with the Server and Server with the Client).

[source]
----
# Create the keystore for the client and Server

keytool -genkeypair -validity 730 -alias myservicekey -keystore serviceKeystore.jks -dname "cn=localhost" -keypass skpass -storepass sspass
keytool -genkeypair -validity 730 -alias myclientkey -keystore clientKeystore.jks -keypass cspass -storepass cspass

# Place the server public cert in client key/truststore
keytool -export -rfc -keystore serviceKeystore.jks -alias myservicekey -file MyService.cer -storepass sspass
keytool -import -noprompt -trustcacerts -file MyService.cer -alias myservicekey -keystore clientKeystore.jks -storepass cspass

# Place client public cert in service key/truststore
keytool -export -rfc -keystore clientKeystore.jks -alias myclientkey -file MyClient.cer -storepass cspass
keytool -import -noprompt -trustcacerts -file MyClient.cer -alias myclientkey -keystore serviceKeystore.jks -storepass sspass
----

NOTE: The command should be executed within this folder used for the Camel use case +src/test/resources/org/jboss/fuse/security/camel/tls+ and this for the CXF case +src/test/resources/org/jboss/fuse/security/cxf/mutualtls+

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project. 

Refer to the following URL's for the relevant Apache CXF documentation: 
- http://cxf.apache.org/docs/ws-security.html
- http://cxf.apache.org/docs/a-simple-jax-ws-service.html

[[usecase1]]
=== Mutual TLS with Netty4 HTTP & Camel REST DSL



[[usecase2]]
=== Mutual TLS using Apache CXF REST framework & Jetty


ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
