:scrollbar:
:data-uri:
:toc2:
:linkattrs:
:sourcedir: ../code/security-ws/src/test/java


== TLS with Mutual Authentication Lab

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience using TLS and mutual authentication
* Develop a RESTful service project and secure it
* Expose a RESTful service using Camel REST DSL and Netty4 HTTP component
* Set up TLS mutual authentication using Apache CXF REST framework with Jetty

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with RESTful services and HTTP basic authentication
* Understanding of link:https://docs.oracle.com/cd/B10501_01/network.920/a96582/pki.htm[PKI^] and encryption with TLS/SSL
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you examine two use cases:

* <<usecase1>>
* <<usecase2>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:


== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
| link:http://sourceforge.net/projects/soapui/files/[SoapUI^] | Latest version | Optional
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to explore the use cases, import the project into a new JBoss Developer Studio workspace.

=== Create Keys and Certificates

In this section, you create the user and server private and public keys and their corresponding certificates, and mark them as trusted. This means the client trusts the server certificate and the server trusts the client certificate.

* For the first use case (Camel), execute the following command in the `src/test/resources/org/jboss/fuse/security/camel/tls` folder.

* For the second use case (CXF), execute the following command in the `src/test/resources/org/jboss/fuse/security/cxf/mutualtls` folder.
+
[source,text]
----
# Create the keystore for the client and Server
keytool -genkeypair -validity 730 -alias myservicekey -keystore serviceKeystore.jks -dname "cn=localhost" -keypass skpass -storepass sspass
keytool -genkeypair -validity 730 -alias myclientkey -keystore clientKeystore.jks -keypass cspass -storepass cspass

# Place the server public cert in client key/truststore
keytool -export -rfc -keystore serviceKeystore.jks -alias myservicekey -file MyService.cer -storepass sspass
keytool -import -noprompt -trustcacerts -file MyService.cer -alias myservicekey -keystore clientKeystore.jks -storepass cspass

# Place client public cert in service key/truststore
keytool -export -rfc -keystore clientKeystore.jks -alias myclientkey -file MyClient.cer -storepass cspass
keytool -import -noprompt -trustcacerts -file MyClient.cer -alias myclientkey -keystore serviceKeystore.jks -storepass sspass
----


[[usecase1]]
== Explore TLS Mutual Authentication Using Netty4 HTTP and Camel REST DSL

In this use case, you develop a `org.jboss.fuse.security.camel.tls.TLSRestDSLNetty4HttpTest` JUnit test class to authenticate the HTTP request using basic authentication, JAAS, and TLS mutual authentication. The client and the server exchange their certificates and verify that the client and server are trusted to communicate with each other.

As mentioned during the installation step of this lab, the certificates and keys must be generated and available under the `src/test/resources/org/jboss/fuse/security/camel/tls` folder.

=== Configure Camel REST DSL Route

. Expose a REST service using REST DSL syntax and the Netty4 HTTP component at the `say/hello/{id}` path.
. Return a `Hello World ${header.id}` message.
. Configure the Netty4 HTTP component to support JAAS and TLS.

=== Configure JAAS and Security Constraint

. Use the `org.apache.camel.component.netty4.http.JAASSecurityAuthenticator` Netty4 HTTP JAAS class to authenticate the client user and password at the server side.
. Configure the realm name as `myrealm` and the JAAS configuration file in the `/org/jboss/fuse/security/basic/myrealm-jaas.cfg` file.
. Include a security constraint for the Netty4 HTTP component to restrict access to the `/say/hello/*` path to users with the `admin` role.

=== Configure Server-Side SSL

. Set up the SSL parameters at the server side to enable TLS communication with the client and to require TLS client authentication.
. Configure the keystore and truststore.

=== Configure Client-Side SSL

. Set up the SSL parameters at the client side to enable TLS communication with the server and to require TLS server authentication.
. Configure the keystore and truststore.

=== Develop JUnit Tests

. Develop four unit tests to check these scenarios:
+
[cols="3",options="header"]
|====
|Method
|Request
|Description
|`testFailAuth()`: No HTTP basic authentication is included within the HTTP header
|"netty4-http://https://localhost:" + PORT + "/say/hello/noauthheader"
a|HTTP code: `401`
|`testBasicAuth()`: HTTP request generated with HTTP basic authentication and user is allowed to access the path
|"netty4-http://https://localhost:" + PORT + "/say/hello/Mickey"
a|HTTP code: `200`

Response message asserted: `"Hello World Mickey"`
|`testBasicAuthSecConstraintWithoutAdminRole()`: HTTP request generated with HTTP basic authentication and user is not allowed to access the path
|"netty4-http://https://localhost:" + PORT + "/say/hello/Donald"
a|HTTP code : `401`
|`testHttpRequest`: Test HTTP request without TLS
|"netty4-http://http://localhost:" + PORT + "/say/hello/Mickey"
a| Response message asserted: `"No response received from remote server"`
|====

[[usecase2]]
== Explore TLS Mutual Authentication Using Apache CXF REST Framework and Jetty

In this use case, you develop an Apache CXF REST project implementing TLS mutual authentication. The CXF server side is configured using the Jetty component and the CFX Spring `httpj:engine-factory` bean. The client is configured using the Spring `http:conduit` bean.

=== Configure Application

. Configure the SSL parameters at the server and client side using the keystore and truststore generated in the _Create Keys and Certificates_ section.
. Create Sprint CXF XML files named `ClientConfig.xml` and `Serverconfig.xml` for client and server configuration, respectively.
. Place these configuration files in the `src/test/resources/org/jboss/fuse/security/cxf/mutualtls` folder.
. Set up the SSL parameters ensuring that you require client SSL authentication.

=== Develop Unit Test

. Develop the `org.jboss.fuse.security.cxf.mutualtls.MutualTLSCxfRSTest` JUnit test class to set up the Spring CXF bus.
* The bus is responsible for instantiating the Jetty component configured to support SSL and client authentication.
. Configure CXF, using the `JAXRSServerFactoryBean` class, to expose the REST service that uses the annotated `CustomerService` class.
. Implement the `testMutualTLS()` method:
* Use `CustomerResponse = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Customer><id>123</id><name>John</name></Customer>";` for the HTTP response returned.
* Use `"https://localhost:" + PORT + "/customerservice/customers/123"` for the URL of the HTTP request.
* Use the `callRestEndpoint("localhost", BASE_SERVICE_URL)` method to send the HTTP request.
* Assert that the HTTP response status code is `200`.
* Assert that the received response corresponds to the expected response.

ifdef::showscript[]

:numbered!:


== Teacher Information

* Time estimated: 2d

* How to evaluate the student's solution:

** Verify that the JUnit tests are passing successfully.
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, etc.)
** Review the solutions proposed by the student to resolve the different use cases.
** For each use case, verify that the SOAP request and response populated. They should be comparable to what you can find in the `output/ws-*` corresponding folder.

endif::showscript[]
