:scrollbar:
:data-uri:
:toc2:
:linkattrs:
:sourcedir: ../code/security-ws/src/test/java


== REST Security with Interceptors Lab

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience using Apache Camel Intercept/Policy and REST Filter
* Develop a RESTful service project and secure it
* Expose RESTful services using a Camel route and CXF RS
* Configure a Jetty endpoint to authenticate the HTTP user request using the Intercept/Policy created

.Prerequisites
* Experience with Java, Spring, Maven
* Familiarity with RESTful services and HTTP basic authentication
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you examine two use cases:

* <<usecase1>>
* <<usecase2>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:

== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
| link:http://sourceforge.net/projects/soapui/files/[SoapUI^] | Latest version | Optional
|====

=== Install Lab Project

Download and install locally the latest release of the project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to explore the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Authenticate User with JAX-RS Request Filter

In this use case, you authenticate an incoming HTTP request using the `ContainerRequestFilter` JAX-RS class. This filter is registered as a CXFRS provider. It extracts the HTTP `Authorization` header from the HTTP request and decodes the Base64-encoded username and password.

. Create an `org.jboss.fuse.security.cxf.intercept.JAXRSContainerFilterTest` Java class that extends the `AbstractBusClientServerTestBase` class.
. Add a static public server class that extends  `AbstractBusTestServerBase`.
. In the `run()` method, write the code required to create the `JAXRSServerFactoryBean` bean.
. Use these parameters:
+
[source,json]
----
 setAddress("http://localhost:" + PORT + "/");
 setResourceClasses(CustomerServiceImpl.class);
 setResourceProvider(CustomerServiceImpl.class, new SingletonResourceProvider(new CustomerServiceImpl()));
 setAddress("http://localhost:" + PORT + "/");
----

. Add a provider to the `JAXRSServerFactoryBean` instance using `setProvider(new SimpleAuthenticationFilter());`.
. Register the `SimpleAuthenticationFilter` class.

* This inner Java class implements the `javax.ws.rs.container.ContainerRequestFilter` interface.

. In the `public void filter(ContainerRequestContext requestContext)` method, add the code required to extract the HTTP `Authorization` header, decode the Base64 string, and check if the supplied user and password are "mickey" and "mouse", respectively.
. If the user and password are correct, print or log that the user is authenticated.
. If the user and password are not correct, create a `javax.ws.rs.core.Response` with the `<message>Authentication failed</message>` message and the `UNAUTHORIZED` (`401`) response code.

. In the test class, add the `testBasicAuth` and `testFailAuth` methods in which you issue an HTTP request using the `getAndCompare(String address, String acceptType, String auth, int expectedStatus, String response)` method.

. Call the endpoint at `http://localhost:PORT/customerservices/customers/123`.
* Include an `Accept` header with the value `application/xml`.
* Include an `Authorization` header, using HTTP basic authentication.
* The value `Authorization` header should be a string of the form "Basic xxxxxxx" where xxxx is the Base64-encoded string of the user and password separated by a colon.
. Check the following:
* The response code for `testBasicAuth` is `200` (OK) and the response body is `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Customer><id>123</id><name>John</name></Customer>`.
* The response code for `testFailAuth` is `401` (Unauthorized) and the response body is `<message>Authentication failed</message>`.

[[usecase2]]
== Authenticate User with Apache Camel Interceptor/Policy

In this use case, you develop an Apache Camel policy acting as an interceptor to accept or refuse the HTTP request, depending on whether authentication is successful or not. You develop the Apache Camel project using REST DSL syntax and Netty4 HTTP to expose the `/say/hello/{id}` RESTful service.

The REST endpoint redirects the Camel Exchange to a `direct:hello` endpoint where you apply the policy strategy to intercept the HTTP request.

=== Develop Project

. Use the `org.jboss.fuse.security.camel.policy.SimpleAutPolicyTest` Java class to develop a Camel route exposing a REST Netty4 HTTP endpoint and test case.

. Configure a route exposing the `from("direct:hello")` endpoint.
. Call a policy processor created using the `org.jboss.fuse.security.camel.policy.SimpleAuthenticationPolicy` class.
. Return the simple message `Hello World ${header.id}` as a response.

* Your Java class `SimpleAuthenticationPolicy` policy must implement the `org.apache.camel.spi.AuthorizationPolicy;` interface.

. Override the `public Processor wrap(RouteContext routeContext, Processor processor)` wrap method.
. Return the `SimpleAuthenticationProcessor(processor, this);` object.

* The `org.jboss.fuse.security.camel.policy.SimpleAuthenticationProcessor` Java class, which extends the `DelegateAsyncProcessor` Camel class, retrieves the Camel `Exchange` instance in the `process(Exchange exchange, AsyncCallback callback)` method.

. Develop the strategy to extract the HTTP `Authorization` header in the `applySecurityPolicy(Exchange exchange)` method.
. Authenticate the user and password extracted from the Base64-encoded string, as in the previous use case.

. Use the `login(String user, String password)` method to verify the extracted user and password.

. Add different catch blocks in the `applySecurityPolicy(Exchange exchange)` method to collect these exceptions and messages:
+
[source,javascript]
----
} catch (NullPointerException ne) {
    throw new AuthenticationException("Authorization Header is not present or can't be decoded");
} catch (AuthenticationException ae) {
    throw new AuthenticationException("Authentication Failed. There is no user with username and/or password", ae.getCause());
} catch (UnsupportedEncodingException e) {
    throw new AuthenticationException("Base64 String can't be decoded", e.getCause());
}
----

. Add an `onException` processor in the Camel DSL route definition to catch these `AuthenticationException.class` exceptions.
. Set the `Body` of the Camel `Exchange` object to a `javax.rs.core.Response` object that you configure with the  HTTP `404` (Not Found) error code and the message extracted from the caught exception.

=== Develop Test Case

. In the test class, add a `testBasicAuth` method.
. In this method, write code to perform two requests--one authorized and the other unauthorized.
. Use the `ProducerTemplate.requestBodyAndHeader()` method to send the HTTP request using Netty4 HTTP.
* Remember to pass the HTTP method as a parameter as well as any HTTP headers, including an `Authorization` header, when required.
. Send two HTTP requests--one without an HTTP `Authorization` header and a second with the header.
. Verify that the response message and HTTP status code returned are as shown in this table:
+
[cols="2",options="header"]
|===
|Request
|Description
|`netty4-http://http://localhost:" + PORT + "/say/hello/noauthheader`
a|HTTP code: `500`

Response message returned: `Netty HTTP operation failed invoking http://localhost:23000/say/hello/noauthheader with statusCode: 500`
|`netty4-http://http://localhost:" + PORT + "/say/hello/Donald`
a|HTTP code: `200`

Response message returned: `Hello World Donald`
|===

* You can use any username and password from the password map.


ifdef::showscript[]

:numbered!:

== Teacher Information

* Time estimated: 2d

* How to evaluate the student's solution:

** Verify that the JUnit tests are passing successfully.
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, etc.)
** Review the solutions proposed by the student to resolve the different use cases.
** For each use case, verify that the SOAP request and response populated. They should be comparable to what you can find in the `output/ws-*` corresponding folder.

endif::showscript[]
