:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= REST Security with Interceptors

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

* Configure your local environment to develop and resolve use cases
* Become more experimented about Apache Camel Intercept/Policy and REST Filter
* Design RESTfull Service project and secure it
* Expose the RESTfull services using a Camel route or CXF RS
* Configure the Jetty Endpoint to authenticate the HTTP User request using the Intercept/Policy created

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with RESTfull & HTTP Basic Authentication
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project. 

[[usecase1]]
=== Authenticate the user using JAXRS ContainerRequestFilter

The goal of this use case is to develop the strategy performing the authentication of the incoming HTTP request using the JAXRS ContainerRequestFilter. This filter will be registered as a CXFRS Provider
in order to extract from the HTTP Request, the HTTP Authorization header to decode the Base64 user and password.

Create a new Java class +org.jboss.fuse.security.cxf.intercept.JAXRSContainerFilterTest+ which extend the class +AbstractBusClientServerTestBase+. Add a static public Server class extending the +AbstractBusTestServerBase+
and develop within the +run()+ method the code required to create the +JAXRSServerFactoryBean+ bean.

Use the following parameters :

[source]
----
 setAddress("http://localhost:" + PORT + "/");
 setResourceClasses(CustomerServiceImpl.class);
 setResourceProvider(CustomerServiceImpl.class, new SingletonResourceProvider(new CustomerServiceImpl()));
 setAddress("http://localhost:" + PORT + "/");
----

Add a new Provider +setProvider(new SimpleAuthenticationFilter());+ to the JAXRSServerFactoryBean and register the +SimpleAuthenticationFilter+ class.

This inner java class implements the interface +javax.ws.rs.container.ContainerRequestFilter+.

Within the method +public void filter(ContainerRequestContext requestContext)+, add the code required to extract the HTTP Authorization header, decode the Base64 String and check if the user
and password passed are equal respectively to "mickey" and "mouse". If this is the case, then print or log that the user is authenticated. Otherwise, create a +javax.ws.rs.core.Response+ with the message +<message>Authentication failed</message>+
and the response code +UNAUTHORIZED+.

Within the Test class, add 2 methods +testBasicAuth+ and +testFailAuth+ where you will issue a HTTP Request using the method +getAndCompare(String address, String acceptType, String auth, int expectedStatus, String response)+

Call the endpoint at the address +http://localhost:PORT/customerservices/customers/123+ with the HTTP Accept type +application/xml+ and pass the HTTP Authorization String under the form "Basic xxxxxxx" where xxxx is the base64 string of the user and password.
The response code expected for +testBasicAuth+ is +200+ while it should be +401+ for the second. Assert that you will receive as response +<message>Authentication failed</message>+ in case of failure and +<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Customer><id>123</id><name>John</name></Customer>+
in case of success.

ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
