:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= REST Security with Interceptors

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

* Configure your local environment to develop and resolve use cases
* Become more experimented about Apache Camel Intercept/Policy and REST Filter
* Design RESTfull Service project and secure it
* Expose the RESTfull services using a Camel route or CXF RS
* Configure the Jetty Endpoint to authenticate the HTTP User request using the Intercept/Policy created

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with RESTfull & HTTP Basic Authentication
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project. 

[[usecase1]]
=== Authenticate the user using JAXRS ContainerRequestFilter

The goal of this use case is to develop the strategy performing the authentication of the incoming HTTP request using the JAXRS ContainerRequestFilter. This filter will be registered as a CXFRS Provider
in order to extract from the HTTP Request, the HTTP Authorization header to decode the Base64 user and password.

Create a new Java class +org.jboss.fuse.security.cxf.intercept.JAXRSContainerFilterTest+ which extend the class +AbstractBusClientServerTestBase+. Add a static public Server class extending the +AbstractBusTestServerBase+
and develop within the +run()+ method the code required to create the +JAXRSServerFactoryBean+ bean.

Use the following parameters :

[source]
----
 setAddress("http://localhost:" + PORT + "/");
 setResourceClasses(CustomerServiceImpl.class);
 setResourceProvider(CustomerServiceImpl.class, new SingletonResourceProvider(new CustomerServiceImpl()));
 setAddress("http://localhost:" + PORT + "/");
----

Add a new Provider +setProvider(new SimpleAuthenticationFilter());+ to the JAXRSServerFactoryBean and register the +SimpleAuthenticationFilter+ class.

This inner java class implements the interface +javax.ws.rs.container.ContainerRequestFilter+.

Within the method +public void filter(ContainerRequestContext requestContext)+, add the code required to extract the HTTP Authorization header, decode the Base64 String and check if the user
and password passed are equal respectively to "mickey" and "mouse". If this is the case, then print or log that the user is authenticated. Otherwise, create a +javax.ws.rs.core.Response+ with the message +<message>Authentication failed</message>+
and the response code +UNAUTHORIZED+.

Within the Test class, add 2 methods +testBasicAuth+ and +testFailAuth+ where you will issue a HTTP Request using the method +getAndCompare(String address, String acceptType, String auth, int expectedStatus, String response)+

Call the endpoint at the address +http://localhost:PORT/customerservices/customers/123+ with the HTTP Accept type +application/xml+ and pass the HTTP Authorization String under the form "Basic xxxxxxx" where xxxx is the base64 string of the user and password.
The response code expected for +testBasicAuth+ is +200+ while it should be +401+ for the second. Assert that you will receive as response +<message>Authentication failed</message>+ in case of failure and +<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Customer><id>123</id><name>John</name></Customer>+
in case of success.

[[usecase2]]
=== Authenticate the user using Apache Camel Interceptor/Policy

The goal of this use case is to develop an Apache Camel Policy acting as an interceptor to accept/refuse the HTTP Request if the authentication process succeeds/fails. We will design an Apache Camel project using the REST DSL
syntax and the component Netty4 HTTP to expose the following RESTfull service +/say/hello/{id}+.

The REST endpoint will redirect the Camel Exchange created to a +direct:hello+ endpoint where you will apply your Policy strategy to intercept the HTTP Request.

Use the Java class +org.jboss.fuse.security.camel.policy.SimpleAutPolicyTest+ to design your Camel Route exposing the Rest Netty4 HTTP Endpoint and test case.

Configure a route exposing the from("direct:hello") endpoint and calling next a policy processor created using the class +org.jboss.fuse.security.camel.policy.SimpleAuthenticationPolicy+. Return as response this
simple message +Hello World ${header.id}+.

Your policy java class +SimpleAuthenticationPolicy+ must implement the interface +org.apache.camel.spi.AuthorizationPolicy;+. Override the wrap method +public Processor wrap(RouteContext routeContext, Processor processor) {+ and
return this object new +SimpleAuthenticationProcessor(processor, this);+

The +org.jboss.fuse.security.camel.policy.SimpleAuthenticationProcessor+ java class which extends the +DelegateAsyncProcessor+ class of Camel will get the Camel Exchange within the method +process(Exchange exchange, AsyncCallback callback) {+

Develop the strategy to extract the HTTP Authorization header within the +applySecurityPolicy(Exchange exchange)+ method and authenticate the user/password extracted from the Base64 encoded string as done within the
 previous use case.

Use the +login(String user, String password)+ method to verify the user, password extracted.

Add different catch blocks within the +applySecurityPolicy(Exchange exchange) {+ method to collect the following exceptions and messages

[source]
----
} catch (NullPointerException ne) {
    throw new AuthenticationException("Authorization Header is not present or can't be decoded");
} catch (AuthenticationException ae) {
    throw new AuthenticationException("Authentication Failed. There is no user with username and/or password", ae.getCause());
} catch (UnsupportedEncodingException e) {
    throw new AuthenticationException("Base64 String can't be decoded", e.getCause());
}
----

Add a onException processor within the Camel DSL Route definition to catch these exception +AuthenticationException.class+. Set the Body of the Camel Exchange with a +javax.rs.core.Response+ object that you will
configure with the HTTP Error code 404 and the message extracted from the Exception caught.


Within the Test Class, add this method +testBasicAuth+ and develop the code to perform 2 requests; one unauthorized and the other authorized.
You will use the +ProducerTemplate.requestBodyAndHeader()+ method to send using the Netty4 HTTP endpoint, the HTTP Request. Don't forget to pass the HTTP Method as parameter to the HTTP header and Authorization header when required

Send 2 HTTP Requests and assert the response message or HTTP code returned for; request without HTTP Authorization header and request with HTTP Authorization header

[cols="2*", options="header"]
|===
|Request
|Description

|netty4-http://http://localhost:" + PORT + "/say/hello/noauthheader
a|HTTP code: 500

Response message asserted: Netty HTTP operation failed invoking http://localhost:23000/say/hello/noauthheader with statusCode: 500

| netty4-http://http://localhost:" + PORT + "/say/hello/Donald
a|HTTP code: 200

Response message asserted: "Hello World Donald"

|===

NOTE: You can use as user/password one of the value of the Map of the passwords


ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
