:scrollbar:
:data-uri:
:toc2:
:linkattrs:
:sourcedir: ../code/security-ws/src/test/java


== REST Security Using apiman Lab

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience using apiman with the basic authentication plug-in and Keycloak plug-in
* Design a RESTful service and secure it using apiman API Gateway
* Expose RESTful services using a Camel route

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with with RESTful and HTTP basic authentication
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you examine two cases:

* <<usecase1>>
* <<usecase2>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.


:numbered:

== Prepare Lab Environment

=== Install Lab assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
| link:http://sourceforge.net/projects/soapui/files/[SoapUI^] | Latest version | Optional
|====

=== Install Lab Project

Download and install locally the latest release of the project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to explore the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Secure Camel REST Endpoint Using apiman with Basic Authentication Plug-in

. Create a Camel route exposing a REST endpoint at `/say/hello/{id}`.
. Secure it using the apiman Gateway at `http://localhost:6060/gateway/Policy_BasicAuthStatic/message/1.0/say/hello/`.

* The process to register and configure the basic authentication plug-in that you use to create the API for the endpoint are respectively in the `src/test/resources/test-plan-data/policies/basic-auth-static/001-publish-api.resttest` and `src/test/resources/test-plan-data/policies/basic-auth-static/002-register-client.resttest` files.

. At server launch time, parse and use the configuration files to execute the REST HTTP requests against the apiman server to set up the APIs.

* The `GatewayTester` class used by the `@RunWith() annotation` starts a Jetty apiman Server with the apiman servlets.

. Use the `org.jboss.fuse.security.apiman.BasicAuthenticationTest` Java class.
. Add two test methods to test both a successful and failing basic authentication using the `protected void runAndValidate(String expectedResponse, int code, String uri, String payload, String httpMethod, Map<String, String> requestHeaders, String username, String password)` method.
. Using the table below, determine various parameters and expected responses for each test case:
+
[cols="2",options="header"]
|====
|Method
|Description
|`testBasicAuthenticationAgainstBackendApi()`
a|HTTP code: `200`

Method: `GET`

Response message asserted: `"Hello World " + user`

user: bwayne, password: bwayne

address: `http://localhost:6060/gateway/Policy_BasicAuthStatic/message/1.0/say/hello/ + user`

header: `"X-API-Key","12345"`

|`sayByeNotAllowedForUserRoleTest()`
a|HTTP code: `401`

Method : `GET`

Response message asserted: None

user: bwayne, password: wrongpassword

address: `http://localhost:6060/gateway/Policy_BasicAuthStatic/message/1.0/say/hello/ + user`

header: `"X-API-Key","12345"`
|====

[[usecase2]]
== Retrieve OAuth2 Token with Roles Using apiman/Keycloak

In this section, you use the apiman Keycloak OAuth plug-in to get an OAuth token for an application--the Camel REST endpoint--and authenticate the HTTP request. The `reader` or `writer` roles are defined and associated with a user in Keycloak. Using the Keycloak plug-in, roles are used to configure the REST HTTP operation (GET, POST) and path to authorize or reject a user calling the REST endpoint.

Follow the link:https://github.com/FuseByExample/enforcement-security-in-action#24-use-case---oauth2-with-keycloak["Use case - Oauth2 with Keycloak^"] instructions to explore this use case.

ifdef::showscript[]

:numbered!:

== Teacher Information

* Time estimated: 2d

* How to evaluate the student's solution:

** Verify that the JUnit tests are passing successfully.
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, etc.)
** Review the solutions proposed by the student to resolve the different use cases.
** For each use case, verify that the SOAP request and response populated. They should be comparable to what you can find in the `output/ws-*` corresponding folder.

endif::showscript[]
