:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= REST Security with Apiman

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

* Configure your local environment to develop and resolve use cases
* Become more experimented about Apiman with Basic Auth Plugin and Keycloak Plugin
* Design RESTfull Service project and secure it using Apiman Gateway
* Expose the RESTfull services using a Camel route

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with RESTfull & HTTP Basic Authentication
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.


== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Secure a Camel REST endpoint using Apiman with Basic Auth Plugin

The goal of this test case is to start a Camel Route exposing a REST endpoint at the address +/say/hello/{id}+ and next to secure it using the Apiman Gateway at this address +http://localhost:6060/gateway/Policy_BasicAuthStatic/message/1.0/say/hello/+.

The process to register and configure the Basic Auth Plugin that you will use to create the Api for our endpoint have been done respectively within these files (src/test/resources/test-plan-data/policies/basic-auth-static/001-publish-api.resttest,src/test/resources/test-plan-data/policies/basic-auth-static/002-register-client.resttest).

Such config files are parsed and used at the launch of the server to execute REST HTTP requests against the ApiMan Server to setup the Apis.

The GatewayTester class which is used by the annotation @RunWith() will start a Jetty Apiman Server with the Apiman servlets, ...

To play with this use case, use the +org.jboss.fuse.security.apiman.BasicAuthenticationTest+ Java Class and add 2 methods to test respectively a successfull and failing Basic auth using
the method +protected void runAndValidate(String expectedResponse, int code, String uri, String payload, String httpMethod, Map<String, String> requestHeaders, String username, String password)+

[cols="2*", options="header"]
|===
|Method
|Description

|testBasicAuthenticationAgainstBackendApi()
a|HTTP code: 200

Method : GET

Response message asserted: "Hello World " + user"

user: bwayne, password: bwayne

address: http://localhost:6060/gateway/Policy_BasicAuthStatic/message/1.0/say/hello/ + user

header: "X-API-Key","12345"

|sayByeNotAllowedForUserRoleTest()
a|HTTP code: 401

Method : GET

Response message asserted: ""

user: bwayne, password: wrongpassword

address: http://localhost:6060/gateway/Policy_BasicAuthStatic/message/1.0/say/hello/ + user

header: "X-API-Key","12345"

|===

=== Oauth2 with Roles using Apiman/Keycloak

For this project we will use the Apiman Keycloak OAuth plugin to get a OAuth token for an application which is our Camel REST endpoint and next authenticate the HTTP Request. Two roles "reader" or "writer"
have been defined and associated to a user in Keycloak. This role will be used to configure, using the Keycloak Plugin, the REST HTTP operation (GET, POST) and path to authorize or unauthorize a user
callign the REST endpoint.

Follow the instructions defined within this project to play with the use case - https://github.com/FuseByExample/enforcement-security-in-action#24-use-case---oauth2-with-keycloak

ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
