:scrollbar:
:data-uri:
:noaudio:

== Module Topics

* Preparation
* Basic HTTP Authentication
* Resource Access Restriction
* JAAS
* JAX-RS `@RolesAllowed`
* Camel Policy
* JAX-RS Filter
* Mutual TLS
* Security Reinforcement

ifdef::showscript[]

Transcript:

This module discusses security concerns related to authenticating an application sending HTTP requests using basic authentication with or without the Java Authentication and Authorization Service, or JAAS. It investigates how you can use user roles to restrict access to certain RESTful paths by using Jetty/Netty security constraints or the Java API for the RESTful web services, or JAX-RS, annotation `@RolesAllowed`. The security constraint mechanism checks if the path of a resource being accessed matches a rule and its associated role.

The module also looks at ways to secure the communication between a client and a server using the Transport Layer Security (TLS) protocol and mutual authentication. Instead of using a security mechanism managed by the HTTP web container or Netty TCP server, the module describes the concept of an interceptor based on the Apache Camel policy and a JAX-RS container filter.

The module concludes by explaining how to secure an endpoint with an API management platform. With this approach, you delegate security responsibility by using API plug-ins to authenticate the incoming HTTP request with either basic authentication or OpenID Connect/OAuth2.

endif::showscript[]
