:noaudio:

[#jaxrsintercept]
== JAXRS - Filter

- Goal : Intercept the HTTP Request and extract the required info to authenticate the user
- How : Using the ContainerRequestFilter JAXRS Interface implemented as CXF Intercept

.Example
[source]
----
@Provider
@PreMatching
public class SecurityRequestFilter implements ContainerRequestFilter {

@Override
    public void filter(final ContainerRequestContext requestContext)
                throws IOException {
...
----

.References

- http://blog.dejavu.sk/2014/02/04/filtering-jax-rs-entities-with-standard-security-annotations/[Filtering JAX RS entities]

ifdef::showscript[]
[.notes]
****

== JAXRS - Filter

The JAXRS specification proposes since the version 2.0 of the specification a Filter which is also an Interceptor executed at the container side and will be of course used to extract the content of the HTTP Request.
This filter is available by implementing the Java Interface ContainerRequestFilter and contains one method to override "filter". This method will get the ContainerRequestContext object from where you can access the
HTTP headers or parameters and call your Java Class responsible to authenticate the user.

This filter can be bind globally to all the resources or assigned to a specific resource if the annotation @NameBinding is declared. In case the filter should be applied at the pre-match extension point, i.e. before any request matching has been performed by JAX-RS runtime, the filter MUST be annotated with a @PreMatching annotation.

To inform the framework that the filter must be discovered at runtime and loaded, use the annotation @Provider or register the class on by example, the JAXRSServerFactoryBean.

In case of failure, you can use ContainerRequestContext object to specify the HTTP Return code to return like also the customized message.

****
endif::showscript[]