:noaudio:

[#jaas]
== JAAS

* Basic Authentication can be performed using JAAS Api (Java Standard)
* Well Supported by many Web Containers or Camel Components
* Rely on a Config File containing Login modules definition and Realms

.Example
[source]
----
<entry name> {
    <LoginModule> <flag> <LoginModule options>;
    <LoginModule> <flag> <LoginModule options>;
    . . .
    };


xyz {
    com.acme.SomeLoginModule required debug=true;
};
----

* Control also the access to the Web Resources based on Role assigned
* Different JAAS Implementations exist to support : LDAP, JDBC queries

ifdef::showscript[]
[.notes]
****

== JAAS

The Java Authentication and Authorization Service (JAAS) which is part of the JDK since the version 1.4 can be used for 2 purposes: to authenticate the users and to verify that they have the access control rights (permissions) required to do the actions performed.
JAAS is supported by the JBoss Fuse and JBoss EAP platforms in combination with Apache Camel, Apache CXF & Apache ActiveMQ. Different JAAS Login classes have created to authenticate the user using a properties file, a file containing user id with encrypted passwords, a JDBC or LDAP backend
server.

To use JAAS, it is required to create a JAAS config file containing a collection of entries (which corresponds to the realms to be protected) and the Login Modules that we will associate to an Entry or Realm. An entry can contain several Login Modules having a priority level different.
That offers the possibility to configure a fallback mechanism if the first Login Module, defined within the list doesn't reply. For each module, we can define additional parameters that the Module, which is a Java Class, will use to by example configure
the JDBC/LDAP connection or simply to retrieve the Users Properties File. As you can see from the example, the different modules are declared between the brackets characters and separate with a semicolon. After the name of the Login Module, the flag indicating the
ranking of the Module for the entry is defined.

Remark : As the JAAS config is read one time and discovered at the launch of the JVM, it is not possible within a Java Application to use several JAAS config files.

****
endif::showscript[]