:scrollbar:
:data-uri:

:linkattrs:


== JAAS

* Basic authentication can be performed using Java Authentication and Authorization Service (JAAS) API (Java Standard)
* Well supported by many web containers or Camel components
* Relies on configuration file containing login modules definition and realms

* Example:
+
[source,text]
----
<entry name> {
    <LoginModule> <flag> <LoginModule options>;
    <LoginModule> <flag> <LoginModule options>;
    . . .
    };


xyz {
    com.acme.SomeLoginModule required debug=true;
};
----

* Control access to web resources based on role assigned
* Different JAAS implementations exist to support LDAP and JDBC queries


ifdef::showscript[]

Transcript:

JAAS has been part of the Java SE Development Kit since version 1.4. You can use JAAS to authenticate users and verify that they have the access control rights, or permissions, required to do the actions they want to perform. JAAS thus gives you another method for performing basic authentication.

JAAS is well supported by many web containers and Camel components, including the JBoss Fuse and JBoss EAP platforms and Apache Camel, Apache CXF, and Apache ActiveMQ. Different JAAS login classes have been created to authenticate the user using either a properties file, a file containing the user ID with encrypted passwords, or a Java Database Connectivity (JDBC) or Lightweight Directory Access Protocol (LDAP) back-end server.

To use JAAS, you need to create a JAAS configuration file containing a collection of entries. These entries correspond to the realms to be protected and the login modules to associate with an entry or realm.

An entry can contain several login modules, each having a different priority level. This lets you configure a fallback mechanism if the first login module defined in the list does not reply.

For each module, you can define additional parameters that the module, which is a Java class, uses to, for example, configure the JDBC or LDAP connection or retrieve a user's properties file. Different modules are declared between brackets and separated by semicolons. After the name of the login module, you define a flag indicating the module's priority rank.

You can also control access to web resources based on the role assigned.

Note that the JAAS configuration file is discovered and read one time when launching the Java VM. Therefore, it is not possible to use several JAAS configuration files within a Java application.

endif::showscript[]
