:noaudio:

[#reenforce-security-token]
== Re-enforce Security - OpenId - Token

* Goal : Authenticate a user using a Identity provider to get a token used for SSO purposes
* Authentication between Client and Identity Provider: public, secret or PKI
* JSon Web Token :
- Compact token format,
- Encode claims to be transmitted,
- Base64url encoded and digitally signed and/or encrypted

Example
[source]
----
{
  "jti": "af68fac6-fd50-4b73-bd37-5c555a8e561e",
  "exp": 1442847825,
  "nbf": 0,
  "iat": 1442847525,
  "iss": "http://localhost:8080/auth/realms/fuse",
  "aud": "fuse",
  "sub": "3591e417-7c60-4464-8714-96190c7fad92",
  "azp": "fuse",
  "session_state": "f58d5dfc-6e4c-4ad2-bd2f-70713f6b942d",
  "client_session": "f06b673f-ecbe-47f2-ba76-b6a5901d5afe",
  "allowed-origins": [],
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "view-profile"
      ]
    }
  },
  "name": "admin ",
  "preferred_username": "admin",
  "given_name": "admin"
}
----

.References

- http://www.softwaresecured.com/2013/07/16/federated-identities-openid-vs-saml-vs-oauth/[SAML vs Oauth vs OpenID Connect]
- https://openid.net/specs/draft-jones-json-web-token-07.html[JWT Spec]

ifdef::showscript[]
[.notes]
****

== Re-enforce Security - OpenId - Token

When the process to authenticate the HTTP Agent/Client connected to your application must be managed by an Identity Provider as Google, Twitter, Facebook, Gitlab, Keycloak, then it will be required to secure the
Api as we did for the HTTP Basic Authentication but using now a different Plugin.

To achieve this goal, it will required to use the KeyClok OAuth2 Policy and also to configure Keycloak to act as an OAuth2 Broker between your application and the Identity Provider; Google, Facebook, Twitter, ...

Remark : If you don't want to use one of the Identity Provider supported by Keycloak, you can simply use Keycloak to authenticate your user according to a realm and next return to this user a token. Keycloak uses the OpenID Connect spec and Json
Web Token to return your token when you will issue a request to be authenticated.

The process to configure a new Keycloak realm, a client (which is in our case the Apiman Client) and the user that the client will use to be authenticated is described within the MicroServices in Action project available
within the Github Fuse By Example Repo. This is also the case for the Keycloak Plugin that you will use to secure your Api.

****
endif::showscript[]
