:scrollbar:
:data-uri:
:noaudio:

== Security Reinforcement

.Role-Based Security

- Goal: Restrict/allow access to application based on authorization rule
- Should be combined with Keycloak plug-in
- How: Define collection of authorization rules
- Example:

[cols="3",width="70%"]
|===
|Path |Verb|Role Required
|.* |`PUT` |Writer
|.* |`GET` |Reader
|===

ifdef::showscript[]

Transcript:

A key benefit to using Keycloak in combination with apiman is that you can restrict or allow access to an application based on an authorization rule. To do so, you define roles to a realm within the Keycloak management console and map the roles with an HTTP action using the Apiman authorization rule plug-in.

When you configure the authorization rule plug-in, you describe for each web resource or path the action allowed and the role assigned as a list or collection of rules. Some examples are shown here.

When the HTTP client calls the gateway, the Keycloak plug-in extracts the JSON web token, checks to see if the token is still valid, and if it is, extracts the role assigned to the user from the token.

Based on this role, the plug-in checks the authorization policy rule and allows or denies access to the resource accordingly.

This approach lets you externalize the authentication of the HTTP client outside of Apiman according to a defined realm and use the token passed by the client when it calls the RESTFul service to allow or deny access to the service. You can do this without needing to locally manage the security aspects except for the security constraints, which are the authorization rules.


endif::showscript[]
