:scrollbar:
:data-uri:

:linkattrs:

== JAX-RS Filter

- Goal: Intercept HTTP request and extract information required to authenticate user
- How: Use `ContainerRequestFilter` JAX-RS interface implemented as CXF intercept

* Example:
+
[source,text]
----
@Provider
@PreMatching
public class SecurityRequestFilter implements ContainerRequestFilter {

@Override
    public void filter(final ContainerRequestContext requestContext)
                throws IOException {
...
----

.Reference

* link:http://blog.dejavu.sk/2014/02/04/filtering-jax-rs-entities-with-standard-security-annotations/["Filtering JAX-RS Entities with Standard Security Annotations^"]

ifdef::showscript[]

Transcript:

Starting with version 2.0, the JAX-RS specification proposes in the specification a filter that is an interceptor executed on the container side and used to extract the content of the HTTP request.

To make this filter available, you implement the Java interface `ContainerRequestFilter` containing one method to override `filter`. This method gets the `ContainerRequestContext` object, from which you can access the HTTP headers or parameters and call the Java class responsible for authenticating the user.

You can bind the filter globally to all resources, or assign it to a specific resource by declaring the `@NameBinding` annotation. To apply the filter at a prematch extension point--that is, before any matching request has been performed by the JAX-RS runtime--you must annotate the filter with a `@PreMatching` annotation.

To inform the framework that the filter must be discovered at runtime and loaded, either use the `@Provider` annotation or, for example, register the class on the `JAXRSServerFactoryBean`.

In case of failure, use the `ContainerRequestContext` object to specify the HTTP return code to return a customized message.

endif::showscript[]
