:scrollbar:
:data-uri:
:linkattrs:


== Basic HTTP Authentication

* HTTP user agent provides username and password
* Base64-encoded string
* Included within a HTTP `Authorization` header:
+
[source,text]
----
Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l
----
+
* Server can request that an agent be authenticated:
+
[source,text]
----
WWW-Authenticate: Basic realm="myrealm"
----
* Error code returned: `401 - Unauthorized`
* Combined preferably with TLS (HTTPS, SSL)
* Full access to the resources

.Reference

* link:https://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01#AA["W3C HTTP Access Authentication specification^"]

ifdef::showscript[]

Transcript:

The World Wide Web Consortium, or W3C, is responsible for managing and developing the HTTP protocol specification. Within the HTTP 1.0 and HTTP 1.1 specifications, the W3C specified an access authentication mechanism that relies on a simple challenge/response request and response. In this basic authentication scheme, the user agent must authenticate itself with a user ID and a password for each realm.

The server services the request only if it can validate the user ID and password for the protection space of the request URI. To be authenticated and authorized, the HTTP client or agent issues an HTTP request containing a HTTP header with the name `Authorization`, followed by a colon, followed by the token `Basic`, followed finally by the user ID and password within a base64-encoded string.

If the server receives an unauthorized request for a URI within the protection space, the server responds with a challenge containing the HTTP header `WWW-Authenticate`, followed by a colon, the token `Basic`, and the realm that protects the URI space that the server is verifying. This returns an error code `401 - Unauthorized`.

This solution is simple and very basic, but also not very secure. The user ID and password can be easily decoded and retrieved. For this reason, the recommended approach is to use digest authentication, preferably combined with HTTPS, which implements the transport layer secure protocol (TLS or SSLv3).

endif::showscript[]
