:scrollbar:
:data-uri:
:noaudio:

== Security Reinforcement

.Basic Authentication

* Goal: Set up API using basic authentication plug-in
* How:
- Create versioned API for organization
- Define target endpoint using REST or SOAP
- Associate policy using basic authentication plug-in

* Supports HTTP(S) connection with user/password, LDAP, JDBC

* Example:
+
[source,text]
----
  "contracts" : [
    {
      "apiOrgId" : "Policy_BasicAuthStatic",
      "apiId" : "echo",
      "apiVersion" : "1.0.0",
      "policies" : [
        {
          "policyImpl" : "class:io.apiman.gateway.engine.policies.BasicAuthenticationPolicy",
          "policyJsonConfig" : "{ \"realm\" : \"Test\", \"forwardIdentityHttpHeader\" : \"X-Authenticated-Identity\", \"staticIdentity\" : { \"identities\" : [ { \"username\" : \"bwayne\", \"password\" : \"bwayne\" } ] }  }"
        }
      ]
    }
  ]
----

ifdef::showscript[]

Transcript:

To use the Apiman platform to secure an endpoint using the HTTP basic authentication plug-in, you define an organization, register an API for a specific version, assign it to the basic authorization policy, and publish it.

When you create an organization, you define a project and namespace that Apiman uses to group all of the related web resources or APIs together. Within a project, this organization represents a group of related endpoints, part of an application, or part of several related applications.

The API that you register corresponds to the target endpoint that you want to secure. It is encoded and can be documented with its corresponding Swagger JSON/YAML file. When the API is encoded to a specific version, you add a policy and select the `BasicAuthenticationPolicy`. This policy provides different options for using the HTTPS scheme, defining the realm to be used for communication between the server and the client, and defining whether to match the extracted user ID and password against a static list of users, an LDAP repository, or a JDBC database.

After you finish registering the versioned API, you publish it. Apiman creates the gateway endpoint that the HTTP client or agent uses to access the service.

endif::showscript[]
