:scrollbar:
:data-uri:
:noaudio:

== Security Reinforcement

.Delegate Endpoint Security

* Goal: Externalize/delegate security endpoint to an API
* How: API acts as proxy/gateway matching:
- Incoming request against one-to-many policies
- Delivery request to target endpoint if validation succeeds
* Advantages:
- Tracking of APIs and consumers of those APIs
- Centralized governance-policy configuration

ifdef::showscript[]

Transcript:

You can delegate and manage the security of an Apache Camel or CXF endpoint using an API management platform that acts as a proxy or gateway to intercept an incoming HTTP request, match the web resource accessed with one of the rules defined, apply the rule, and, if the matching succeeds, issue a request to the target endpoint.

The rules, the APIs to be managed, and the organization holding the APIs are all managed using the API management server, while the proxy is handled by an API manager gateway. The server can manage several gateways. The statistics and usage of the APIs are reported within an `ElasticSearch` back-end repository.

The advantage to using an API management platform is that it lets you centrally manage the governance of policies, assign policies to a plan and different APIs, and track your clients to determine who is doing what with the APIs.

The current apiman project is supported only on JBoss EAP. The next release may also be packaged on JBoss Fuse.

endif::showscript[]
