:noaudio:

[#reenforce-security-basic]
== Re-enforce Security - Basic Auth

* Goal : Setup an Api using the Basic Auth Plugin
* How :
- Create a versioned Api for an Organisation
- Define the target endpoint using REST or SOAP
- Associate a Policy using the Basic Auth Plugin

* Supports http(s) connection with
- User/password, LDAP, JDBC

.Example
[source]
----
  "contracts" : [
    {
      "apiOrgId" : "Policy_BasicAuthStatic",
      "apiId" : "echo",
      "apiVersion" : "1.0.0",
      "policies" : [
        {
          "policyImpl" : "class:io.apiman.gateway.engine.policies.BasicAuthenticationPolicy",
          "policyJsonConfig" : "{ \"realm\" : \"Test\", \"forwardIdentityHttpHeader\" : \"X-Authenticated-Identity\", \"staticIdentity\" : { \"identities\" : [ { \"username\" : \"bwayne\", \"password\" : \"bwayne\" } ] }  }"
        }
      ]
    }
  ]
----

ifdef::showscript[]
[.notes]
****

== Re-enforce Security - Basic Auth

To use the Apiman platform and secure an endpoint using HTTP Basic Authentication Plugin, it will be required to perform differet steps; first we will define an organization, next register an Api for a specific version
and assign it to the Basic Auth Policy and publish it.

By creating an organization, we define a project/namespace that Apiman will use to group all the related Web Resources or Apis together. This organization will represent within a project a group of related Endpoints part of an
application or part of several applications related.

The Api that will will register corresponds to our target endpoint that we want to secure. It is encoded and can be documented with its correspoding Swagger JSON/Yaml file. When the Api has been encoded to a specifc
version, we will add a Policy and will select the BasicAuthenticationPolicy. This policy provides different options to use the HTTPS scheme, define the realm to be used for the communication between the Server and the
 client like also how to match the extracted user-id and password against a static list of users, a LDAP repo or a JDBC database.

 When you have finished to register the versioned APi, then you will publish the Api and Apiman will create the Gateway endpoint that the HTTP Client/Agent will now use to access the service.

****
endif::showscript[]