:scrollbar:
:data-uri:

:linkattrs:

== Resource Access Restriction

* Concept: Combine user roles with resource access paths
* Goal: Restrict or allow access to resources
* Implementation: Web container or component-specific
* Operations are supported (`GET`, `POST`, `PUT`)
* How: URL requested matched with rules

* Example:
+
[source,text]
----
Constraint constraint = new Constraint();
constraint.setRoles(new String[] { "user", "admin" });

ConstraintMapping mapping = new ConstraintMapping();
mapping.setPathSpec("/say/hello/*");
mapping.setMethod("GET");
mapping.setConstraint(constraint);
----

ifdef::showscript[]

Transcript:

When you develop a RESTFul application, you define several web resources and identify them by their Uniform Resource Identifiers, or URIs. Those URIs are acted upon through one of the commands supported by the HTTP agent and the server: `GET`, `POST`, `PUT`, `DELETE`, and so on. To deny or allow access to these web resources, you can define a collection of authorization rules describing which resources are accessible and how they can be reached using a role.

These rules, also known as constraints, are supported by many web containers such as Jetty and Netty HTTP. You can describe them according to the mechanism that they provide. For example, with Jetty, you can declare a constraint to enable the HTTP basic authentication mode, to assign the authorized roles, and to declare a `ConstraintMapping` containing the path to the web resource and the command to use to access the resource.

By combining the HTTP basic authentication mechanism with SSL/TLS transport and constraints, you can secure your RESTful services. The disadvantages of this approach are that the authorization to deny or allow access to the web resources is defined at the level of the web container and is project-dependent, because the support and implementation are different for Jetty and Netty HTTP. This requires you to stop and restart the web server to support new security constraints.

Note that the Java class used to authenticate the user ID sending its credentials using basic authentication must be able to retrieve the user's role from the properties file containing this information.

endif::showscript[]
