:scrollbar:
:data-uri:
:linkattrs:
:noaudio:

== Preparation

.Recommended Reading

* link:https://github.com/FuseByExample/rest-dsl-in-action["REST DSL in action with Camel, ElasticSearch & Kibana^"]
* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_CXF_Development_Guide/RESTGuide.html[Developing RESTful Web Services^]
* link:https://en.wikipedia.org/wiki/Basic_access_authentication[Basic access authentication^]
* link:https://docs.oracle.com/javase/8/docs/technotes/guides/security/jaas/JAASRefGuide.html["Java Authentication and Authorization Service (JAAS) Reference Guide^"]

.Recommended Tasks

* Develop Camel REST DSL routes and CXF REST services
* Review basic HTTP authentication and the Java API authentication and authorization mechanism
* Generate keystore and truststore and self-signed certificates using Java keytool


ifdef::showscript[]

Transcript:

To prepare yourself for this module, Red Hat recommends that you review the information on the web pages shown here.

Also, test yourself to make sure you can do the following:

* Create some CXF/Camel web services routes with a REST client and REST service for the REST DSL in Action GitHub project.
* Review how basic HTTP authentication works based on the IETF specification. Also review the Java API authentication and authorization mechanism.
* Using a Java keytool, generate a keystore or truststore and some self-signed certificates.

endif::showscript[]
