:scrollbar:
:data-uri:
:noaudio:
:linkattrs:

== Mutual TLS

* Goal: Two parties authenticating each other
* TLS offers client-to-server authentication using client-side *X.509 authentication*
* How: Server uses `CertificateRequest` message to request certificate from client

* Server-side example:
+
[source,text]
----
<http:destination id="{Namespace}PortName.http-destination">
  <http:tlsServerParameters secureSocketProtocol="TLSv1">
    ...
    <sec:clientAuthentication want="true" required="true"/>
  </http:tlsServerParameters>
</http:destination>
----

* Client-side example:
+
[source,text]
----

<http:conduit id="{Namespace}PortName.http-conduit">
  <http:tlsClientParameters>
    ...
    <sec:keyManagers keyPassword="CertPassword">
      <sec:keyStore type="JKS"
                    password="KeystorePassword"
                    file="certs/CertName.jks"/>
    </sec:keyManagers>
----

.References

* link:https://en.wikipedia.org/wiki/Transport_Layer_Security[Transport Layer Security^]
* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html-single/Apache_CXF_Security_Guide/index.html#i305901[Mutual Authentication Overview^]

ifdef::showscript[]

Transcript:

Many web applications rely on the HTTPS protocol to reinforce the security communication between the server and the client. In many cases, these applications set up the communication in only one direction, from server to client.

That means that the SSL server certificate is only presented to the client for the client to verify or validate that it is properly connected to the server. This control mechanism is very important, because it guarantees the integrity of the message transmitted--that is, no alterations of the message took place. It also guarantees that the server is authenticated, because its X509 certificate has been verified by the client and its CA authority. Finally, it guarantees that the communication is secured between both parties as encrypted using the public key, the part of the certificate that the client can use.

In mutual TLS, the client also sends its own certificate to the server, which the server controls to authenticate the client. This process is called mutual TLS because the server sends the client a `CertificateRequest` within the TCP communication to get the client's certificate.

To use the mutual TLS mechanism, both parties must generate their X509 certificates and cross-sign them for the client to accept the SSL server certificate and vice versa. If you use Apache CXF or one of the Apache Camel components supporting TLS, you must configure the SSL parameters to configure the `Keystore`, `TrustStore`, and `KeyManagers` used by both parties.

Note that the `SSLengine` needs to be configured at the server to specify whether client authentication is required or optional but preferred.

endif::showscript[]
