:scrollbar:
:data-uri:


== Security Reinforcement

.OpenID and Token

* Goal: Authenticate user using identity provider to get a token used for single sign-on purposes
* Authentication between client and identity provider: public, secret, or public key infrastructure (PKI)
* JSON web token:
- Compact token format
- Encode claims to be transmitted
- Base64url encoded and digitally signed and/or encrypted

* Example:
+
[source,text]
----
{
  "jti": "af68fac6-fd50-4b73-bd37-5c555a8e561e",
  "exp": 1442847825,
  "nbf": 0,
  "iat": 1442847525,
  "iss": "http://localhost:8080/auth/realms/fuse",
  "aud": "fuse",
  "sub": "3591e417-7c60-4464-8714-96190c7fad92",
  "azp": "fuse",
  "session_state": "f58d5dfc-6e4c-4ad2-bd2f-70713f6b942d",
  "client_session": "f06b673f-ecbe-47f2-ba76-b6a5901d5afe",
  "allowed-origins": [],
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "view-profile"
      ]
    }
  },
  "name": "admin ",
  "preferred_username": "admin",
  "given_name": "admin"
}
----

.References

* link:https://www.softwaresecured.com/federated-identities-openid-vs-saml-vs-oauth/["Federated Identities: OpenID vs SAML vs OAuth^"]
* link:https://openid.net/specs/draft-jones-json-web-token-07.html["JSON Web Token (JWT)^"]

ifdef::showscript[]

Transcript:

When you need an identity provider such as Google, Twitter, Facebook, Gitlab, or Keycloak to manage the process of authenticating the HTTP agent or client connected to your application, then you secure the API in the same way that you did for HTTP basic authentication. The only change is that you use a different plug-in.

For this type of authentication, you obtain a token to use for single sign-on purposes. Authentication between the client and the identity provider can take the form of a public key, secret, or public key infrastructure (PKI). The JSON web token offers a compact token format that lets you encode the claims to be transmitted. The token is base64url-encoded and digitally signed and/or encrypted.

To secure the API, you use the Keycloak OAuth2 policy and configure Keycloak to act as an OAuth2 broker between your application and the identity provider.

Note that if you do not want to use one of the identity providers supported by Keycloak, you can simply use Keycloak to authenticate your user according to a realm and return a token to this user. Keycloak uses the OpenID Connect specification and a JSON web token to return your token when you issue an authentication.

To configure a new Keycloak realm, describe a client--in this case, the Apiman client--and the user that the client will use to be authenticated within the MicroServices in Action project available in the `Fuse By Example` GitHub repository. Also define the Keycloak plug-in that you want to use to secure your API.

endif::showscript[]
