:scrollbar:
:data-uri:
:noaudio:
:linkattrs:

== Camel Policy

* Goal: Extract from HTTP request information needed to authenticate user
* How: Use Camel policy to wrap route/pipeline with new processor
* Camel authorization policy extends the policy interface
* Free to design/develop security authentication solution as desired

* Example:
+
[source,text]
----
public class ShiroSecurityPolicy implements AuthorizationPolicy {

    public Processor wrap(RouteContext routeContext, final Processor processor) {
        return new ShiroSecurityProcessor(processor, this);
    }
    ...
    @Override
    public boolean process(Exchange exchange, AsyncCallback callback) {
        try {
            applySecurityPolicy(exchange);
----

.Reference
* link:http://camel.apache.org/security.html[Apache Camel Security^]

ifdef::showscript[]

Transcript:

Another option for securing a CXF or RESTful endpoint is to extract the information needed to authenticate a user from the HTTP request. To do so, you use a Camel policy to wrap the route and pipeline with a new processor.

This approach uses the concept of an interceptor. Different implementations of an interceptor exist, two of which are discussed in this module: one based on the Apache Camel framework and the other based on a JAX-RS filter. If you want, you can develop your own strategy on top of Apache CXF with an interceptor combined with Apache ActiveMQ via the plug-in model.

To use an interceptor pattern with Apache Camel, you implement the Java interface `AuthorizationPolicy`. This interface contains two methods, `beforeWrap` and `wrap()`. The method to be overridden is `wrap()`. The `wrap()` method is called during setup of the Apache Camel route. Within the list of the pipeline, the framework adds the authentication/authorization processor used to authenticate the incoming HTTP request or agent.

To support this approach, you need to create an authentication processor implementing the `AuthorizationPolicy`, register it within the Java/XML DSL route, and create a Java security class. The class contains the code required to extract the HTTP headers and/or body from the Camel Exchange to authenticate the request.

endif::showscript[]
