:scrollbar:
:data-uri:

:linkattrs:


== JAX-RS `@RolesAllowed`

- Allow/deny access to resources
- Annotations supported:
* `@PermitAll`, `@DenyAll`, `@RolesAllowed`
- `@RolesAllowed` lists roles permitted to access methods in application
- Delegates responsibility to JAXRS framework

- Example:
+
[source,text]
----
@Path("projects")
@Produces("application/json")
public class ProjectsResource {

    @POST
    @RolesAllowed("manager")
    public Project createProject(final Project project) { ... }

    @GET
    @Path("{id}")
    public Project getProject(@PathParam("id") final Long id) { ... }
----

.Reference
* link:http://docs.oracle.com/javaee/6/api/javax/annotation/security/RolesAllowed.html[Annotation Type RolesAllowed^]


ifdef::showscript[]

Transcript:

Previously you learned how to use security constraints to deny or allow access to the web resources of a web or RESTful application. For RESTful applications, another option is available for securing access to web resources: the Java annotation `@RolesAllowed`. You define this Java API for RESTful web services, or JAX-RS, annotation for the different methods declared within the Java class containing the REST services. This annotation allows access to a resource path based on the roles assigned by defining a list of roles permitted to access methods in an application.

The advantage of using this annotation is that it lets you document the security aspect of the application within the Java class containing the description of the REST services. In addition, because this annotation is supported by a variety of JAX-RS frameworks and not by the web container or HTTP/TCP component, it is container-agnostic.

Two additional annotations exist: `@DenyAll` or `@PermitAll`. The annotation used depends on the role of the user that the authentication or JAAS authentication login module is able to retrieve.

endif::showscript[]
