:noaudio:

[#basic_auth]
== Basic Authentication

* HTTP user agent provides : user & password
* Base64 Encoded String
* Included within a HTTP Authorization Header
+
[source]
----
Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l
----
+
* Server can request an agent to be authenticated
+
[source]
----
WWW-Authenticate: Basic realm="myrealm"
----
* Error code returned : 401 - Unauthorized
* Combined preferably with TLS (HTTPS, SSL)
* Full access to the resources !

.References

- https://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01#AA[W3C Http Basic Authentication spec]

ifdef::showscript[]
[.notes]
****

== Basic Authentication

The World Wide Web or W3C consortium, responsible to manage and develop the HTTP Protocol specification has described within the HTTP 1.0 and a HTTP 1.1 specifications an Access Authentication
mechanism which relies on a simple challenge-response request and response. The "basic" authentication scheme is based on the model that the user agent must authenticate itself with a user-ID and a password for each realm.

The server will service the request only if it can validate the user-ID and password for the protection space of the Request-URI. To be authenticated and authorized, the HTTP client or agent will issue a HTTP request containing a HTTP header
with the name "Authorization" followed by a column, the token "Basic" and the user-ID and password within a base64 encoded string.

Upon receipt of an unauthorized request for a URI within the protection space, the server should respond with a challenge containing as HTTP Header "WWW-Authenticate", a colon character, the token "Basic" followed by the realm
which protects the URI space that the server will verify.

This solution is simple and very basic but is not really secure as the user id/password can be easily decoded and the user id, password retrieved. This is the reason why, the Digest Authentication should be preferered or combined
with the HTTPS which implements the Transport Layer Secure protocol (TLS or SSLv3).

****
endif::showscript[]