:scrollbar:
:data-uri:
:linkattrs:
:toc2:


== Persistence with Camel SQL Components Lab

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience using the Apache Camel JDBC component
* Design Apache Camel routes using Direct, Mock, and JDBC components

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with SQL and databases
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you examine three use cases:

* <<usecase1>>
* <<usecase2>>
* <<usecase3>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:


== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Query Database Using Apache Camel SQL

In this use case, you develop a JUnit test case that creates an Apache Derby database and populates it with records. You use the Apache Camel JDBC component to select SQL records from this database. The route you use in the JUnit test is based on a Direct consumer, and is responsible for sending an Exchange object to the JDBC endpoint.

. Create the `org.jboss.fuse.persistence.jdbc.SelectFromTest.java` class, extending the `CamelSpringTestSupport` class.

. Override the Spring method used to specify the location of the Spring XML configuration file.
* Use `src/test/resources/org/jboss/fuse/persistence/sql/camelContext.xml` as the configuration file.

. Use the Spring JDBC framework to create a Derby embedded database with the name `testdb`.
. In the XML file, perform these steps:
.. Develop an Apache Camel route exposing the `direct:start` endpoint.
.. Use a `SELECT * FROM REPORT.T_INCIDENT` SQL query to fetch records from the Derby database.
.. Send the SQL query to the JDBC component.
.. Assign the result of this query to the Camel Body object.

. In the `testSelectFrom` method, validate the results with `Assert` rules.
. Verify that the second record contains these column/value pairs:
* `INCIDENT_ID`: 2
* `INCIDENT_REF`: 002
* `GIVEN_NAME`: Jeff
* `FAMILY_NAME`: Delong
* `EMAIL`: jdelong@redhat.com


[[usecase2]]
== Use Named Parameter Query with JDBC Camel

In this use case, you develop a JUnit test case where an Apache Derby database is created and populated with records. This database is used to select some SQL records using the Apache Camel JDBC component with a SQL query containing named parameters.

. Create an `org.jboss.fuse.persistence.jdbc.SelectFromTest.java` class that extends the `SelectFromWithParamsTest` class.
* Reuse the Spring Camel XML configuration file created in the previous use case.

. Create the code to be tested in the `testNamedParametersQuery` method.

. Just as you did in the previous use case, use the `from(direct:select).to(jdbc)` route definition to send a Camel Exchange to the Direct endpoint.
. Use the `SELECT * FROM REPORT.T_INCIDENT where GIVEN_NAME = :?firstname AND FAMILY_NAME = :?lastname` SQL query.
. Initialize a map with the header values you want to pass in as JBDC parameters to the selected query.
. Verify that you receive two records and that the first record contains these column/value pairs:
* `INCIDENT_ID`: 1
* `INCIDENT_REF`: 001
* `GIVEN_NAME`: CharlesP
* `FAMILY_NAME`: Moulliard
* `EMAIL`: cmoulliard@redhat.com


[[usecase3]]
== Insert and Select Records Using JDBC Camel

In this use case, you develop a JUnit test case that uses one Camel route to insert records into a database and then uses another route to query the inserted records.

=== Implement Camel Routes
. Develop a route to insert a record into the database using the JDBC component.
.. Use the `direct:insert` component to send the `INSERT` query.
.. Format the query using the `Named` parameter.

. Use these parameters to set up the `INSERT` query:
+
[cols="3",options="header"]
|=====
|Parameter  | Named Parameter of Field  | Value
|`ref`      |`INCIDENT_REF`             |005
|`date`     |`INCIDENT_DATE`            |2016-03-25
|`firstname`|`GIVEN_NAME`               |Chad
|`lastname` |`FAMILY_NAME`              |Darby
|`summary`  |`SUMMARY`                  |Incident Course-005
|`details`  |`DETAILS`                  |This is a report incident for course-005
|`email`    |`EMAIL`                    |cdarby@redhat.com
|`phone`    |`PHONE`                    |111 10 20 300
|=====

. Create a second route to select records from the database:
+
[source,text]
----
from("direct:start")
to("jdbc:testdb")
to("mock:insert")
----

=== Implement Test Case

. Create an `org.jboss.fuse.persistence.jdbc.InsertAndSelectFromTest` class.
. Create a `testInsertAndSelect` Java method.
. In the `testInsertAndSelect` method, insert the record using the `direct:insert` Camel endpoint.
. In the `testInsertAndSelect` method, use the `mock:insert` Camel endpoint to verify that you receive five records and that the fifth record contains these column/value pairs:
* `INCIDENT_ID`: 5
* `INCIDENT_REF`: 005
* `GIVEN_NAME`: Chad
* `FAMILY_NAME`: Darby
* `EMAIL`: cdarby@redhat.com


