:noaudio:
:toc2:

= Persistence with Camel 'SQL' Components

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

<<usecase3>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about Apache Camel SQL components
* Design Apache Camel Routes using JDBC & JPA components
* Develop Camel and Arquillian Test Cases
* Run Apache Camel in standalone mode or using WildFly Camel subsystem

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with SQL, Database & ORM - Hibernate
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Query an Apache Derby database using an Apache Camel SQL component

The goal of this use case is to design a Junit Test case where an Apache Derby Database will be created and populated with some records. This database will be next used to
select some SQL records previously populated within the database using the Apache Camel JDBC component. The route that we will use within the Junit Test is based on a Direct consumer, responsible to
send an Exchange object to the JDBC endpoint.

The use case will be developed using the class +org.jboss.fuse.persistence.jdbc.SelectFromTest.java+ which extend the class +CamelSpringTestSupport+ class.
This class will override the method of Spring used to pass as parameter the location of the Spring XML config file +src/test/resources/org/jboss/fuse/persistence/sql/camelContext.xml+.
You will develop into this XML file the Apache Camel route exposing the +direct:start+ endpoint and sending the result to the +jdbc+ component.
The SQL query that you will use +SELECT * FROM REPORT.T_INCIDENT+ to fetch the records from the Derby database will be assigned to the Camel Body Object and the result will be validated
with some Assert rules.

Here are the values that we expect to receive :

4 records containing for the second record these values :

* 2 for the INCIDENT_ID field
* 002 for the  INCIDENT_REF field
* Jeff for the GIVEN_NAME field
* Delong for the FAMILY_NAME field
* jdelong@redhat.com for the EMAIL field

NOTE: Use Spring JDBC framework to create a Derby embedded Database where the Database Name is testdb

ifdef::showScript[]


endif::showScript[]
