:noaudio:
:toc2:

= Persistence with Camel 'SQL' Components

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

<<usecase3>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about Apache Camel SQL components
* Design Apache Camel Routes using JDBC & JPA components
* Develop Camel and Arquillian Test Cases
* Run Apache Camel in standalone mode or using WildFly Camel subsystem

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with SQL, Database & ORM - Hibernate
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Query an Apache Derby database using an Apache Camel SQL component

The goal of this use case is to design a Junit Test case where an Apache Derby Database will be created and populated with some records. This database will be used to
select some SQL records using the Apache Camel JDBC component. The route that we will use within the Junit Test is based on a Direct consumer, responsible to
send an Exchange object to the JDBC endpoint.

The use case will be developed using the class +org.jboss.fuse.persistence.jdbc.SelectFromTest.java+ which extends the class +CamelSpringTestSupport+ class.
This class will override the method of Spring used to pass as parameter the location of the Spring XML config file +src/test/resources/org/jboss/fuse/persistence/sql/camelContext.xml+.
You will develop into this XML file the Apache Camel route exposing the +direct:start+ endpoint and sending the result to the +jdbc+ component.
The SQL query that you will use +SELECT * FROM REPORT.T_INCIDENT+ to fetch the records from the Derby database will be assigned to the Camel Body Object and the result will be validated
with some Assert rules within the method +testSelectFrom+.

Here are the values that we expect to receive :

4 records containing for the second record these values :

* 2 for the INCIDENT_ID field
* 002 for the  INCIDENT_REF field
* Jeff for the GIVEN_NAME field
* Delong for the FAMILY_NAME field
* jdelong@redhat.com for the EMAIL field

NOTE: Use Spring JDBC framework to create a Derby embedded Database where the Database Name is testdb.

[[usecase2]]
=== Use a Named Parameters Query to fetch record from a Database using the JDBC Camel component

The goal of this use case is to design a Junit Test case where an Apache Derby Database will be created and populated with some records. This database will be used to
select some SQL records using the Apache Camel JDBC component with a SQL query containing named parameters.

The use case will be developed using the class +org.jboss.fuse.persistence.jdbc.SelectFromTest.java+ which extends the class +SelectFromWithParamsTest+ class and the code to be tested
will be created within the method +testNamedParametersQuery+.

Like the previous use case, we will use the following route definition +from(direct:select).to(jdbc)+ to send a Camel Exchange to the Direct endpoint. The message to be send will use as input this SQL Query definition
+SELECT * FROM REPORT.T_INCIDENT where GIVEN_NAME = :?firstname AND FAMILY_NAME = :?lastname+. So, configure accordingly your Camel Exchange in order to pass the parameter.

Here are the values that we expect to receive :

2 records containing for the first record these values :

* 1 for the INCIDENT_ID field
* 001 for the  INCIDENT_REF field
* Charles for the GIVEN_NAME field
* Moulliard for the FAMILY_NAME field
* cmoulliard@redhat.com for the EMAIL field

NOTE: You can reuse the Spring Camel XML config file created from the previous use case

[[usecase3]]
=== Use a Named Parameters Query to fetch record from a Database using the JDBC Camel component

The goal of this use case is to design a Junit Test case where we will insert and select records from an Apache Derby Database using 2 different routes. So, you will design a first route to insert a record
into the database using the JDBC component. The component that you will use to send the Insert Query is +direct:insert+. The query must be formatted using Named parameter. Here are the parameters
that you will use to setup the insert query :

- ref: named param of the field "INCIDENT_REF", value "005"
- date: named param of the field "INCIDENT_DATE", value 2016-03-25"
- firstname: named param of the field "GIVEN_NAME", value "Chad"
- lastname: named param of the field "FAMILY_NAME", value "Darby"
- summary: named param of the field "SUMMARY", value "Incident Course-005;
- details: named param of the field "DETAILS", value "This is a report incident for course-005"
- email: named param of the field "EMAIL", value "cdarby@redhat.com"
- phone: named param of the field "PHONE", value "+111 10 20 300"

The second route is defined as such :

[source]
----
from("direct:start")
to("jdbc:testdb")
to("mock:insert")
----

The class to be used to create the Junit Test is +org.jboss.fuse.persistence.jdbc.InsertAndSelectFromTest+ and the java method +testInsertAndSelect+. As the method name suggests, you will first insert the record using the Camel endpoint
+direct:insert+ and next control using the +mock:insert+ that you have received the following information :

5 records containing for the fifth record these values :

* 5 for the INCIDENT_ID field
* 005 for the  INCIDENT_REF field
* Chad for the GIVEN_NAME field
* Darby for the FAMILY_NAME field
* cdarby@redhat.com for the EMAIL field

ifdef::showScript[]


endif::showScript[]
