:noaudio:
:toc2:

= Persistence with Camel JPA & Infinispan Components

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

<<usecase3>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about Apache Camel JPA, Infinispan components
* Design Apache Camel Routes using DIRECT, MOCK, JDBC components
* Develop Camel and Arquillian Test Cases
* Run Apache Camel in standalone mode or using WildFly Camel subsystem

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with SQL, Database & ORM - Hibernate, JPA
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with JPA, Database & Hibernate
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Camel JPA Component

For this use case, you will create 2 Apache Camel Routes, one sending an exchange with the java object to be inserted within a Derby Database using the JPA component and the
second querying every x second the records from the database and sending the result to a mock endpoint.

To develop this usecase, you will create the following artifacts :

- persistence.xml file located under META-INF folder. The name of the persistence unit is Camel and the java class to be mapped with its corresponding table is +org.jboss.fuse.persistence.model.SendEmail+
  The database driver to be configured is +org.apache.derby.jdbc.EmbeddedDriver+ while the url is +jdbc:derby:target/derby;create=true+
- Spring Camel XML file containing the routes definition, the declaration of the Spring bean +org.springframework.orm.jpa.LocalEntityManagerFactoryBean+ and +org.springframework.transaction.support.TransactionTemplate+
- The Junit Test case using the class +Jorg.jboss.fuse.persistence.jpa.paConsumerTest+ which extend the class +CamelSpringTestSupport+ class.

The method that Junit will test is called +testInsertAndReceive+. Within this method, you will send 3 camel exchanges to the endpoint +direct:start+ with respectively the body value "alpha","beta" and "gamma"
Verify on the mock endpoint that you will receive 3 records, that the +Exchange.BATCH_SIZE+ is equal to 3 and that the second record assert this statement for the email

[source]
----
SendEmail email = mock.....
assertEquals("dummy@somewhere.org", email.getAddress());
----

ifdef::showScript[]


endif::showScript[]
