:scrollbar:
:data-uri:
:toc2:
:linkattrs:

== Persistence with Camel JPA and WildFly Subsystem Lab

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience using Apache Camel JPA components
* Design Apache Camel routes using Direct, Mock, and JPA components
* Develop Camel and Arquillian test cases
* Run Apache Camel in standalone mode and use the WildFly Camel subsystem

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with SQL and databases, and ORM, including Hibernate and JPA
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you explore two use cases:

* <<usecase1>>
* <<usecase2>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:


== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Use Camel JPA Component to Insert and Query Data

In this use case, you create two Apache Camel routes. One uses the JPA component to send an exchange with a Java object to be inserted into a Derby database. The second queries the records from the database every `x` seconds and sends the result to a mock endpoint.

=== Create JPA Persistence Configuration
. Create a `persistence.xml` file and place it in the `META-INF` folder.
. Specify "Camel" as the persistence unit name.
. Map the `org.jboss.fuse.persistence.model.SendEmail` Java class to its corresponding table.
. Configure the `org.apache.derby.jdbc.EmbeddedDriver` database driver.
. Use the `jdbc:derby:target/derby;create=true` address.

=== Create Spring Camel XML File
. Create a Spring Camel XML file and define the routes in this file.
. Add a declaration of the `org.springframework.orm.jpa.LocalEntityManagerFactoryBean` Spring bean.
. Add a declaration of the `org.springframework.transaction.support.TransactionTemplate` Spring bean.

=== Implement JUnit Test Case

. Implement a JUnit Test case using the `org.jboss.fuse.persistence.jpa.paConsumerTest` class, extending the `CamelSpringTestSupport` class.
. Define the `testInsertAndReceive` test method.
. In this method, send three Camel Exchanges to the `direct:start` endpoint, with the Body values of "alpha", "beta", and "gamma", respectively.
. In the mock endpoint, verify that you receive three records and that the `Exchange.BATCH_SIZE` is equal to `3`.
. Verify that that the second record has the `"dummy@somewhere.org"` value as the email address.
* Expect your code to look similar to this:
+
[source, text]
----
SendEmail email = mock.....
assertEquals("dummy@somewhere.org", email.getAddress());
----

[[usecase2]]
== Use Camel JPA Component with WildFly Camel

In this use case, you design an Apache Camel project using the Camel JPA component deployed on top of WildFly as a subsystem/module. You use the Arquillian testing framework to simplify the creation of the JAR file containing the artifacts. This JAR file contains the Java classes and data source, and is used to boot the Wildfly Java EE Container.

In this use case, you configure the route using the Java DSL instead of the Spring XML DSL that you used in the previous use case. The IoC framework is based on CDI andEJB, to start up the Camel route, and JPA to manage the `EntityManager` container.

In this section, you implement five artifacts--the model class, the Java Camel class, the persistence XML file, the data source XML file, and the JUnit test. 

=== Implement Model Class
. Implement the `org.jboss.fuse.persistence.jpa.model.Account` model class.
. Add the `@Entity` and `@Table` annotations.
. Map both annotations to the `account` table.
. Add the `@Id` annotation to the `id` field.

=== Implement Java Camel Class
. Implement the `org.jboss.fuse.persistence.jpa.routing.DirectToJPABuilder` Java Camel class.
. Extend the `RouterBuilder` parent class.
. Inject the `EntityManager` and  `JtaTransactionManager` instances using their CDI or JPA annotations.
. Use the `contextName` Camel CDI annotation with the `route-cdi-context` to define the `CamelContext`.
. Add the `@Startup` annotation to bootstrap the Camel route when the EJB container instantiates the beans.
. Create an Apache Camel route starting from the `direct:start` consumer.
. Call the `jpa` endpoint using the model class.

=== Implement Persistence XML File
. Implement the JPA persistence XML file.
. Name the file `persistence-jpa.xml` and place it in the `src/main/resources/org/jboss/fuse/persistence` directory.

=== Implement Data Source XML File
. Implement the data source XML file.
. Place this file in the `src/main/resources/org/jboss/fuse/persistence/` directory.

=== Implement JUnit Test
. Implement the `org.jboss.fuse.persistence.jpa.JPACamelWildflyTest` JUnit class.
* Include the `@Before setUp()`, `@After tearDown()`, and `@Test testJpaInsertCamelRoute` methods.
. Implement the `deployment()` method to generate a JAR archive with the name `camel-jpa-test.jar`.
* In the JAR file, include the classes in the routing and model subpackages.
* Include the data source and persistence XML files as `MANIFEST` resources.
. Develop the `@Before setUp` method to persist two new `Account` objects with these values:
* The first object has an `id` of `1` and `balance` of `750`.
* The second object has an `id` of `2` and `balance` of `300`.
. Using a query applied on the `EntityManager` in the `tearDown` method, clean up the content of the database.
. In the `testJpaInsertCamelRoute` method, assert that you can retrieve the `CamelContext` injected using the `@ArquillianResource` annotation.
. Create a new `Account` object and send this object to the Direct endpoint.
* The object has an `id` equal to `3` and `balance` set to `800`. 
. Use the `EntityManager` to assert that you can retrieve a reference to this account and that fields are equal to those in the account you created.
. Use the `javax.Resource` annotation to inject the `UserTransactionManager`.
* This transaction manager is used to insert the objects within the `setUp` or `TearDown` methods.

ifdef::showScript[]

endif::showScript[]

