:noaudio:
:toc2:

= Persistence with Camel JPA & Infinispan Components

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

<<usecase3>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about Apache Camel JPA, Infinispan components
* Design Apache Camel Routes using DIRECT, MOCK, JDBC components
* Develop Camel and Arquillian Test Cases
* Run Apache Camel in standalone mode or using WildFly Camel subsystem

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with SQL, Database & ORM - Hibernate, JPA
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with JPA, Database & Hibernate
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Camel JPA Component

For this use case, you will create 2 Apache Camel Routes, one sending an exchange with the java object to be inserted within a Derby Database using the JPA component and the
second querying every x second the records from the database and sending the result to a mock endpoint.

To develop this usecase, you will create the following artifacts :

- persistence.xml file located under META-INF folder. The name of the persistence unit is Camel and the java class to be mapped with its corresponding table is +org.jboss.fuse.persistence.model.SendEmail+
  The database driver to be configured is +org.apache.derby.jdbc.EmbeddedDriver+ while the url is +jdbc:derby:target/derby;create=true+
- Spring Camel XML file containing the routes definition, the declaration of the Spring bean +org.springframework.orm.jpa.LocalEntityManagerFactoryBean+ and +org.springframework.transaction.support.TransactionTemplate+
- The Junit Test case using the class +Jorg.jboss.fuse.persistence.jpa.paConsumerTest+ which extend the class +CamelSpringTestSupport+ class.

The method that Junit will test is called +testInsertAndReceive+. Within this method, you will send 3 camel exchanges to the endpoint +direct:start+ with respectively the body value "alpha","beta" and "gamma"
Verify on the mock endpoint that you will receive 3 records, that the +Exchange.BATCH_SIZE+ is equal to 3 and that the second record assert this statement for the email

[source]
----
SendEmail email = mock.....
assertEquals("dummy@somewhere.org", email.getAddress());
----

[[usecase2]]
=== Camel JPA Component & Wildfly Camel

The goal of this use case is to design an Apache Camel project using the Camel JPA component but deployed top of Wildfly as a subsystem/module. To help us to boot the Wildfly JavaEE Container, we will use the Arquillian Testing framework
to simplify the creation of the JAR file containing the artifacts as the Java classes, Datasource, ...
The route will not be longer configured using Spring XML DSL but using Java DSL. The IoC framework will be based on CDI combined with EJB to startup the CamelRoute & JPA to manage the EntityManager container.

For this use case, you will develop the following artifacts :

- Model class : +org.jboss.fuse.persistence.jpa.model.Account+
- Java Camel Class : +org.jboss.fuse.persistence.jpa.routing.DirectToJPABuilder+
- Persistence XML file located under this folder : +src/main/resources/org/jboss/fuse/persistence/persistence-jpa.xml+
- Datasource XML file located +src/main/resources/org/jboss/fuse/persistence/+
- Junit Test +org.jboss.fuse.persistence.jpa.JPACamelWildflyTest+ class with the methods @Before setUp(), @After tearDown() & @Test testJpaInsertCamelRoute

The points that you should develop are :

- Model class : Add the @Entity annotation, @Table annotation mapped to the table "account". The id field should also be annotated with the annotation @Id
- Java Camel class :
** Extend the RouterBuilder parent class
** Inject the EntityManager & JtaTransactionManager using their CDI or JPA annotations
** Define the CamelContext using rhe CamelCDI annotation "contextName" with the name +route-cdi-context+
** Add the @Startup annotation to bootsrap the Camel route when the EJB container will instantiate the beans
** Create an Apache Camel route starting from the consumer "direct:start" & calling the endpoint +jpa+ using the model class
- Junit Test class :
** Develop the deployment() method to generate a JAr archive having the name +camel-jpa-test.jar+
** Include within this jar file, the classes packaged te routing & model subpackage
** Include the datasource and persistence.xml files as MANIFEST Resources
** Develop the method @Before setUp to persist 2 new Account objects with respectively the values ((1, 750, (2, 300)) forthe id, balance
** Cleanup the content of the DB within the tearDown method using a quety applied on the EntityManager
** Within the testJpaInsertCamelRoute method, assert that you can retrieve the CamelContext injected using the @ArquillianResource annotation
** Create a new Account object (3, 800) and sned it to your direct endpoint
** Assert that you can retrieve using the EntityManager a reference for this account which is equal to the object Account created
** Use the annotation javax.Resource to inject the UserTransactionManager. this Tx manager will be used to insert the objects within the setUp or TearDown




ifdef::showScript[]


endif::showScript[]
