:noaudio:
:toc2:

= Persistence with No SQL Component & Idempotent

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about Apache Camel Infinispan component
* Transform an idempotent consumer into a persistent one
* Develop Camel Test Cases

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with SQL, Database & ORM - Hibernate, JPA
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Use a persistent Idempotent Consumer

For this use case, we will setup an Apache Camel route using a persistent Idempotent Consumer. This idempotent consumer will check the content of the header +CamelHeader+ against
the +messageId+ which is stored within the table +CAMEL_MESSAGEPROCESSED+. The Apache Camel route starts with the +direct:data-insert+ endpoint, following by the idempotent persistent
consumer, next the Camel bindy Dataformat to transform the CXF record received into a java Incident object and finally the +mock:result+ endpoint.

To design this use case, you will develop the content of the :

- Spring XML Beans file to include the Apache Camel route definition but also the beans +org.apache.camel.processor.idempotent.jpa.JpaMessageIdRepository+ and +org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean+
- Persistence.xml unit file under the folder META-INF. The name of the persistence unit is +idempotentDb+, url of the database to be used "jdbc:h2:mem:idempotentReport", database driver +org.h2.Driver+. Hibernate is used as ORM/JPA Framework
- The Junit Test class +org.jboss.fuse.persistence.idempotent.CamelIdempotentTest+ with these methods :
** testSendDifferentCsvRecords() : Send to the direct endpoint the following String & assert that the mock result endpoint will receive 2 exchanges
+
[source]
----
"111,22-04-2016,Claus,Ibsen,incident camel-111,this is a report incident for camel-111,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
"222,18-05-2016,Claus,Ibsen,incident camel-222,this is a report incident for camel-222,cibsen@gmail.com,+111 10 20 300","CamelRecord",2
----
+
** testSendSomeCsvRecordWithSameHeader() : Send 3 CSV records to the direct endpoint and check that you will only receive 2 exchanges as one should be filtered by the idempotentConsumer
+
[source]
----
111,22-04-2016,Claus,Ibsen,incident camel-111,this is a report incident for camel-111,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
222,18-05-2016,Claus,Ibsen,incident camel-222,this is a report incident for camel-222,cibsen@gmail.com,+111 10 20 300","CamelRecord",2
333,18-05-2016,Claus,Ibsen,incident camel-333,this is a report incident for camel-333,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
----
+
** testStopStartCamelRoute() : the scenario of this one is more complex. Here are the steps
+
  . Send this CSV record : 111,22-04-2016,Claus,Ibsen,incident camel-111,this is a report incident for camel-111,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
  . Stop the Camel route
  . Use a SQL Statement to check that there is one record saved into the table CAMEL_MESSAGEPROCESSED and assert that the messageId is 1 and the processName is DirectConsumer
  . Send the same CSV record to the endpoint. That should fail as the endpoint / camel route has been stopped.
  . Assert that the String exception message contains in this case this message "Exception occurred during execution on the exchange"
  . Restart the Camel Route
  . Send again this csv record : "333,18-05-2016,Claus,Ibsen,incident camel-333,this is a report incident for camel-333,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
  . Verify that the mock:result endpoint will only receive one exchange

[[usecase2]]
=== Play with Infinispan - nosql component

For this final use case of the persistence lab, we will play with the Infinispan NoSQL component to insert/get keys from an in memory Java cache. For that purpose, an Infinispan DefaultCacheManager
will be created and used for all the tests. The first test case will insert 2 keys into the cache while the second will fetch the two keys. 2 distinct Apache Camel Routes will be created to support
the 2 infinispan operations (PUT & GET).

To realize this use case, you will develop the code within the class +org.jboss.fuse.persistence.nosql.InfinispanCacheTest+ according to the following steps :

  . Create an Apache Camel route starting with a +direct:put+ endpoint, next calling the infinispan producer and passing as parameter the name of the cacheContainer to be used which is cacheContainer, the operation which is PUT
    and finally, send the result to the +mock:put+ endpoint.
  . Create a second Apache Camel route starting with a +direct:get+ endpoint, next calling the infinispan producer and passing as parameter the name of the cacheContainer to be used which is cacheContainer, the operation which is GET
    and finally, send the result to the +mock:get+ endpoint
  . Add the @test method : insertCache()
  . Add the @Test method : GetKeyFromCache()
  . For the insertCache() method, send 2 exchanges to the direct:put endpoint using as keys, values respectively; KEY_ONE/VALUE_ONE and KEY_TWO,VALUE_TWO.
  . Assert that the cache contains for the KEY_ONE, the "valueOne" and for KEY_TWO, the "valueTwo"
  . Assert that the mock:put endpoint will get 2 exchanges
  . For the GetKeyFromCache() method, send 2 exchanges to the direct:get endpoint using as key KEY_ONE and KEY_TWO to get the result from the cache
  . Assert that the exchange received from the mock:get endpoint will contain the "valueOne" and for the other exchange "valueTwo" as Infisinispan Result
  . Assert that the mock:put endpoint will get 2 exchanges

ifdef::showScript[]

endif::showScript[]
