:scrollbar:
:data-uri:
:toc2:
:linkattrs:

== Persistence with Idempotent Consumer and NoSQL Lab

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience with Apache Camel Infinispan
* Transform an Idempotent consumer into a persistent one
* Develop Camel test cases

.Prerequisites
* Experience with Java, Spring, and Apache Maven
* Familiarity with SQL, databases, and ORM, including Hibernate and JPA
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you explore two use cases:

* <<usecase1>>
* <<usecase2>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:


== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Use Persistent Idempotent Consumer

For this use case, you set up an Apache Camel route using a persistent Idempotent consumer. The Idempotent consumer checks the content of the `CamelRecord` header against the `messageId` field, which is stored in the `CAMEL_MESSAGEPROCESSED` table. The Apache Camel route starts with the `direct:data-insert` endpoint, followed by the persistent Idempotent consumer. Next, it uses the Camel Bindy data format to transform the CXF record received into a Java `Incident` object. Finally, the route ends with the `mock:result` endpoint.

To implement this use case, you create the Spring XMP beans file, the `persistence.xml` unit file, and the JUnit test class.

=== Develop Spring XML Beans File

. Include the Apache Camel route definition.
. Include the `org.apache.camel.processor.idempotent.jpa.JpaMessageIdRepository` and `org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean` beans.

=== Create Persistence XML Unit File

. Create the `persistence.xml` unit file under the `META-INF` folder.
. Name the persistence unit `idempotentDb`.
. Use the `jdbc:h2:mem:idempotentReport` database, the `org.h2.Driver` database driver, and the `org.apache.camel.processor.idempotent.jpa.MessageProcessed` class name.
. Use Hibernate as the ORM/JPA framework.

=== Build JUnit Test Class

In this section, you create the `org.jboss.fuse.persistence.idempotent.CamelIdempotentTest` JUnit test class with three methods:

* `testSendDifferentCsvRecords()`
* `TestSendSomeCsvRecordWithSameHeader()`
* `TestStopStartCamelRoute()`.

==== Create `testSendDifferentCsvRecords` Method

. Send the following data to the Direct endpoint:
+
[source,text]
----
"111,22-04-2016,Claus,Ibsen,incident camel-111,this is a report incident for camel-111,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
"222,18-05-2016,Claus,Ibsen,incident camel-222,this is a report incident for camel-222,cibsen@gmail.com,+111 10 20 300","CamelRecord",2
----
. Assert that the mock result endpoint receives the two Exchanges you sent.

==== Create `TestSendSomeCsvRecordWithSameHeader` Method

. Send three CSV records to the Direct endpoint.
+
[source,text]
----
111,22-04-2016,Claus,Ibsen,incident camel-111,this is a report incident for camel-111,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
222,18-05-2016,Claus,Ibsen,incident camel-222,this is a report incident for camel-222,cibsen@gmail.com,+111 10 20 300","CamelRecord",2
333,18-05-2016,Claus,Ibsen,incident camel-333,this is a report incident for camel-333,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
----
. Check that you receive only two Exchanges (one is filtered by the `idempotentConsumer`).

==== Create `TestStopStartCamelRoute` Method

. Send this CSV record:
+
[source,text]
----
111,22-04-2016,Claus,Ibsen,incident camel-111,this is a report incident for camel-111,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
----

. Stop the Camel route.
. Use an SQL statement to check that there is one record saved to the `CAMEL_MESSAGEPROCESSED` table, and assert that the `messageId` is `1` and the `processName` is `DirectConsumer`.
. Send the same CSV record to the endpoint.
* Because the endpoint and Camel route is stopped, expect this to fail.
. Assert that the `String` exception message contains, in this case, "Exception occurred during execution on the exchange".
. Restart the Camel route.
. Send this record again:
+
[source,text]
----
"333,18-05-2016,Claus,Ibsen,incident camel-333,this is a report incident for camel-333,cibsen@gmail.com,+111 10 20 300","CamelRecord",1
----
. Verify that the `mock:result` endpoint receives one Exchange.


[[usecase2]]
== Explore Infinispan NoSQL Component

In this use case, you explore the Infinispan NoSQL component. You insert and retrieve keys from an in-memory Java cache. You create an `DefaultCacheManager` Infinispan and use it for the tests. The first test case inserts two keys into the cache, and the second fetches the two keys. You create two distinct Apache Camel routes to support the `PUT` and `GET` Infinispan operations.

In this section, you develop the code within the `org.jboss.fuse.persistence.nosql.InfinispanCacheTest` class.

=== Develop Camel Routes

. Create an Apache Camel route starting with a `direct:put` endpoint.
.. Have the route call the Infinispan producer next, passing the cache container name ("cacheContainer") as a parameter.
* Use the `PUT` operation.
.. Have the route send the result to the `mock:put` endpoint.

. Create a second Apache Camel route starting with a `direct:get` endpoint.
.. Use the `GET` operation to have the route call the Infinispan producer, passing cache container name ("cacheContainer") as a parameter.
.. Have the route send the result to the `mock:get` endpoint.

=== Create Test Methods

==== Create `insertCache` Method

. Add the `@test insertCache` method.
.. For the `insertCache` method, send two Exchanges to the `direct:put` endpoint--for the first use the key/value pair `KEY_ONE/VALUE_ONE` and for the second, use `KEY_TWO/VALUE_TWO`.
.. Assert that the cache contains "valueOne" for the `KEY_ONE` key, and "valueTwo" for the `KEY_TWO` key.
.. Assert that the `mock:put` endpoint receives two Exchanges.

==== Create `GetKeyFromCache` Method

. Add the `@Test GetKeyFromCache` method.
.. For the `GetKeyFromCache` method, send two Exchanges to the `direct:get` endpoint using as keys `KEY_ONE` and `KEY_TWO`.
** This retrieves the values from the cache.
.. Assert that one Exchange received from the `mock:get` endpoint contains "valueOne" and that the other contains "valueTwo" as the Infinispan result.
.. Assert that the `mock:put` endpoint receives two Exchanges.

ifdef::showScript[]

endif::showScript[]

