:noaudio:
:toc2:

= Camel Transactional Client & Tx Routes

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about Apache Camel Transactional Client & Routes
* Transform an idempotent consumer into a persistent one
* Develop Camel Test Cases

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with Java Transaction, JTA
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Use a Transactional Client

The goal of this use case is to design a project using the Apache Camel Transactional client JPA to rollback a transaction when an error will took place within the route execution process.
We will develop the project using the Junit Test class +org.jboss.fuse.transaction.client.JpaTxRollbackTest.java+ where we will design the Apache Camel routes and the test case.

Create 2 routes as described here after :

  . The first route starts with the JPA Consumer using the Entity class "org.jboss.fuse.transaction.model.Project". The route must be declared to "not start" and endpoint configured to delete the
    entities when consumed and the transaction behavior should be to rollback only the last message. The delay between each poll is 1s.
  . This endpoint continues with a inner processor where we will check if the Project is equal to Camel. If this is the case, then an IllegalArgumentException will be throw with the message "Camel Forced"
  . The next process will log the message with the project name and id
  . The route ends with the "mock:result" processor
  . The second route starts with the "direct:insert" consumer and will call a jpa endpoint to insert the Project Entity received
  . The next process will log the message with the project name and id

Declare the Junit Test method +testRollBack()+ and perform the follow tasks :

   . Insert 4 records using the direct:insert consumer with these data to instantiate the Project objects :
     id: 1, project: AMX, license: ASF
     id: 2, project: Linux, license: XXX
     id: 3, project: Karaf, license: YYY
     id: 4, project: Camel, license: ASF
   . Start the JPA consumer
   . Assert that the result mockendpoint will receive 3 exchanges
   . Assert that the table Project contains 1 record for the Project Camel as the others have been deleted

[[usecase2]]
=== Combine a Transactional Client within a Transacted Route

The goal of this use case is to design a Junit Test case using the class +org.jboss.fuse.security.camel.basic.BasicAuthRESTCamelDSLJettyHashLoginTest.java+ which extend the class +BaseJettyTest+ class.


ifdef::showScript[]


endif::showScript[]
