:scrollbar:
:data-uri:
:toc2:
:linkattrs:

== Camel Transactional Client and Transacted Routes Lab

.Goals
* Configure your local environment to develop and explore use cases
* Gain experience using the Apache Camel Transactional Client and routes
* Transform an Idempotent consumer into a persistent one
* Develop Camel test cases

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with Java Transaction API (JTA)
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab you explore three use cases:

* <<usecase1>>
* <<usecase2>>
* <<usecase3>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:


== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0] | Required
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Use Transactional Client

In this use case, you implement a project using the Apache Camel Transactional Client JPA to roll back a transaction when an error takes place within the route execution process. You use the `org.jboss.fuse.transaction.client.JpaTxRollbackTest.java` JUnit test class to develop the Apache Camel routes and the test case.

=== Create Camel Routes

. In the first route, start with the JPA Consumer using the `org.jboss.fuse.transaction.model.Project` Entity class.
.. Declare the route to "not start."
.. Configure the endpoint to delete the entities when consumed.
.. Configure the transaction behavior to roll back only the last message.
.. Set the delay between each poll to one second.
.. Use an inner processor to check if the project is equal to "Camel" and, if it is,
throw an `IllegalArgumentException` exception with the "Camel Forced" message.
.. Log a message with the project name and ID.
.. End the route with the `mock:result` processor.
. Start a second route with the `direct:insert` consumer.
.. Make the route call a JPA endpoint to insert the received `Project` entity.
.. Make the route log a message with the project name and ID.

===  Instantiate Project Objects

. Declare the `testRollBack()` JUnit test method and insert four records using the `direct:insert` consumer with this data to instantiate the `Project` objects:
+
[cols="3",options="header"]
|====
| `id` | `project` | `license`
| 1    | AMX       | ASF
| 2    | Linux     | XXX
| 3    | Karaf     | YYY
| 4    | Camel     | ASF
|====

. Start the JPA consumer.
. Assert that the result mock endpoint receives three Exchanges.
. Assert that the `Project` table contains one record for the Camel project.
. Assert that the other records are deleted.

[[usecase2]]
== Create Transacted Route with SQL Component

For this use case, you develop a transacted route using an Apache Camel Transacted Policy acting as an interceptor within the route. Use the `org.apache.camel.spring.spi.SpringTransactionPolicy` policy. Create the data source containing a connection to the Derby database using the `org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder` class. The SQL script in `transaction/src/test/resources/sql/createAndPopulateDatabase.sql` sets up the database and populates three records in the `Project` table.

=== Create Route

. Use the `org.springframework.jdbc.datasource.DatasourceTransactionManager` class as the transaction manager.
* The transaction manager is responsible for handling the begin, commit, and rollback events.

. Instantiate the required Java classes (`Datasource`, `TransactionManager`, `SQL component`) and bind them within the JNDI Camel Registry.
. Create a transacted Camel route starting with the `direct:rollback` endpoint.
. Include a SQL producer to delete from the `Projects` table the record where the `id` corresponds to the header `id` value.
. Add an inner processor that throws an exception.
. Finish the route with the `mock:delete` processor.

=== Develop Test Case

. Create a test case with a `testProduceWithRollback` method.
. In this method, send an empty Body to the `direct:rollback` endpoint with a header `id` equal to `1`.
. Assert that the mock endpoint never receives an Exchange.
. Assert that the `Project` table still contains three records.


[[usecase3]]
== Combine Transacted Route with Transactional Client

In this use case, you intermix two strategies--a transactional client, or JMS component, and a transacted route, where the JPA is the transactional endpoint to be managed.

=== Configure Transactional Client

. Use the TX Manager to configure the ActiveMQ JMS Connection Factory, used by the Transactional Client.

* Arjuna TX Manager--the `TransactionManager` used for this project--is already defined in  the `transaction/src/test/resources/org/jboss/fuse/transaction/camelContext.xml` Spring Camel XML file.

. In this file, configure the `EntityManager` that is required to configure the JPA component.

=== Implement Camel Routes

. Create three Camel routes similar to these:
+
[source,xml]
----
<route>
    <from uri="direct:data-insert-rb"/>
    <transacted .../>
    <unmarshal ... />
    <to uri="jpa:org.jboss.fuse.transaction.model.Incident"/>
    <to uri="activemq:queue:incidents"/>
    <throwException ref="ioexception"/>
</route>

<route>
    <from uri="direct:select"/>
    <setHeader headerName="query">
        <constant>select * from T_INCIDENT</constant>
    </setHeader>
    <bean ref="sqlutil"/>
    <to uri="mock:result"/>
</route>
<route>
    <from uri="activemq:queue:incidents"/>
    <marshal/>
    <to uri="mock:result-queue"/>
</route>
----

. Configure the Camel Bindy CSV data format.
* You use it to transform the CSV String to a Java object or from a Java object to a String.
. Include an interceptor to catch the `java.io.IOException` and roll back the transaction using this message:
+
[source,text]
----
"###### Sorry, we can't insert your record and place it on the queue !"
----

=== Develop Test Case

In this section, you develop the the `testRollbackRecord` JUnit test method.

. Send this message to the `direct:data-insert-rb` endpoint:
+
[source,text]
----
"111,22-04-2016,Claus,Ibsen,incident camel-111,this is a report incident for camel-111,cibsen@gmail.com,+111 10 20 300"
----

. Assert that a rollback occurs and that you receive the message in the exception object as shown here:
+
[source,text]
----
"###### Sorry, we can't insert your record and place it on the queue !" 
----

. Assert that the `mock:error` endpoint receives an Exchange.
. Perform an SQL select to verify that no record exists within the `Projects` table using the `direct:select` endpoint.
. Assert that the `mock:result-queue` Mock endpoint does not contain any Exchange.

ifdef::showScript[]

endif::showScript[]

