:scrollbar:
:data-uri:

:linkattrs:

== Idempotent Consumer

* Filters out duplicate messages
* Uses an expression to calculate unique ID
* Generated ID can be checked against repository
* On completion, if exchange fails, Camel removes message ID from repository; otherwise it stays
* Repository persistence supported using:
** File, Hazelcast, JDBC, JPA, Infinispan, EHCache, SpringCache
* Extend use cases to avoid consuming duplicate messages when using distinct transaction managers

.Reference

* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Development_Guide/MsgEnd-Idempotent.html[Idempotent Consumer^]

ifdef::showscript[]

Transcript:

The Idempotent Consumer EIP pattern can be used to filter out duplicate messages. To do so, it uses an expression to calculate a unique ID that is challenged against a repository.

If the ID is already present in the repository, the message is discarded. If it is not present, the message is processed. After completion, if the exchange fails, Camel removes the message ID from the repository. If the exchange succeeds, the message ID remains in the repository.

This method makes it possible to avoid consuming duplicate messages when using distinct transaction managers.

Several persistent storage objects can be used to recover the IDs in the repository in case of a Java VM crash. These persistent storage objects include `FileIdempotentRepository`, `HazelcastIdempotentRepository`, `JdbcMessageIdRepository`, `JpaMessageIdRepository`, `InfinispanIdempotentRepository`, `JCacheIdempotentRepository`, `SpringCache`, and `EhcacheIdempotentRepository`.

endif::showscript[]
