:noaudio:

[#persistence-nosql]
== Persistence NoSQL & Caching

* Several NoSQL components proposed
** Infinispan, HazelCast, EHCache
** MongoDB, Apache Cassandra
** HawtDB, Couchbase, Gora
* Could be used for caching purposes

.References

- https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Component_Reference/IDU-Cache.html[Apache Camel Cache]
- http://camel.apache.org/infinispan.html[Infinispan Cache]

ifdef::showscript[]
[.notes]
****

== Persistence NoSQL & Caching

The Apache Camel project proposes also Non SQL Components that we can use to design additional use cases for the client's project. The most well-know technologies are supported as MongoDB, Apache Cassandra
EHCache (= Hibernate caching), Couchbase but also the new players like JBoss Infinispan, Apache Gora. One of the key benefit of some of the NoSQL components is that they can be used to cache information, to replicate using several
JVM the cache between the nodes for high availability purposes. As Apache Camel doesn't provide any scope as proposed by the JavaEE technology, a NoSQL component could be used to provide such cache
of keys, parameters shared between different CamelContexts.

****
endif::showscript[]