:noaudio:

[#persistence]
== Persistence

* Apache Camel supports different SQL components :

** JDBC - Java Spec based
** SQL - Spring SQL Component (Template base)
** JPA - Java JPA Spec
** Hibernate, iBatis, MyBatis (support ?)
** NoSQL
* Supports the Guaranteed Delivery EIP Pattern
* Some components acts only as Producers and not Consumers

.References

- http://camel.apache.org/guaranteed-delivery.html[Guarantee Delivery]

ifdef::showscript[]
[.notes]
****

== Persistence

The Apache Camel framework supports the Guaranteed Delivery EIP Pattern. Different components with Camel support this pattern such as SQL, JDBC, JPA components. Before choosing a component for a project, it is important to review if the component includes a consumer and producer or just a producer and also if the component fully supported from the Red Hat Subscription point of view and Apache community. As, some components like Hibernate don't use the Apache License 2, the code is not maintained actively under the Apache Camel project. Ibatis is not longer an Apache project even if the new project MyBatis is still released using an Apache License. For some projects, the JDBC projects could be enough as the complexity of the data model, queries does not justify to use an ORM.
Some components like JPA, SQL, Hibernate & MyBatis support Transactions while others do not.

****
endif::showscript[]