:noaudio:

[#persistence-jpa]
== Persistence JPA

* JPA Component supported on JBoss Fuse & on EAP as a module
* Propose a SharedEntityManager and EntityManager
* Component can be used as Tx Client or as part of an Tx Route
* Consumer supports: query, nativeQuery, namedQuery or Parameters

.References

- https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Component_Reference/IDU-JPA.html[Apache Camel on Fuse]
- https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Component_Reference/IDU-JPA.html[Apache Camel JPA on EAP]
- https://wildflyext.gitbooks.io/wildfly-camel/content/javaee/jpa.html[JPA Persistence with Apache Camel]


ifdef::showscript[]
[.notes]
****

== Persistence JPA

The Apache JPA component is offers a variety  of features like the consumer, producer and idempotent repository pattern.
It can also be used in combination with a Transaction Manager to be used as Transaction Client or part of a Transacted Route. One of the key benefits of this component is the flexibility offered through the different modes : query, nativeQuery, namedQuery or parameterized query. The latter will use a Java Util Map object to map the information saved within the registry with the query to be parameterized.


****
endif::showscript[]