:noaudio:

[#persistence]
== Persistence

* Apache Camel supports different SQL components :

** JDBC - Java Spec based
** SQL - Spring SQL Component (Template base)
** JPA - Java JPA Spec
** Hibernate, iBatis, MyBatis (support ?)
** NoSQL
* Supports Guarantee Delivery - EIP Pattern
* Be aware that some components acts only as Producer and/not Consumer

.References

- http://camel.apache.org/guaranteed-delivery.html[Guarantee Delivery]

ifdef::showscript[]
[.notes]
****

== Persistence

The Apache Camel framework supports the Guarantee Delivery - EIP Pattern and we can use different components to persist the information like the SQL, JDBC, JPA components. Even if they rely on a
different principe, we could also use the file and JMS component to persist the content of the Body, part of the Apache Camel Exchange. Before to choose a component for a project, it is important to review 2 parameters;
Does the component include a consumer/producer or just a producer and also is the component fully supported from the Red Hat Subscription point of view and Apache community. As, some components like Hibernate
doesn't use the Apache License 2, then the code is not maintained actively under the Apache Camel project. Ibatis is not longer an Apache project even if the new project MyBatis is still released using
an Apache License. For some projects, the JDBC projects could be enough as the complexity of the data model, queries does not justify to use an ORM.
Another point that I would like to mention is that some components support Transactions like JPA, SQL, Hibernate & MyBatis while others no.

****
endif::showscript[]