:scrollbar:
:data-uri:

:linkattrs:

== JPA Component

* Supported on JBoss Fuse, JBoss EAP as module
* Propose SharedEntityManager and EntityManager
* Can be used as transaction client or as part of transacted route
* Consumer supports: `query`, `nativeQuery`, `namedQuery`, and `Parameters`

.References

* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Component_Reference/IDU-JPA.html[JPA Component^]

* link:http://wildfly-extras.github.io/wildfly-camel/#_jpa[JPA persistence with Apache Camel^]

ifdef::showscript[]

Transcript:

Supported on both JBoss Fuse and JBoss EAP as a module, the Apache JPA component is one of the most robust components. It offers an array of features from the consumer to the producer or the Idempotent repository pattern. It can be used in combination with a transaction manager as a transaction client or as part of a transacted route.

A key benefit of this component is that it provides great flexibility in managing queries. As a consumer, it supports various modes, including `query`, `nativeQuery`, `namedQuery`, and `Parameters`. The `Parameters` mode uses a `java.util.Map` object to map the information saved within the registry to the query being parameterized.

endif::showscript[]
