:noaudio:

[#transactional-route]
== Transactional Route

* Route turned into Transactional Route
+
[source,java]
----
from("direct:rollback")
   .transacted("txPolicy")
   .to("sql:delete from projects where id = :#${header.id}")
----
+
* Implemented using an Interceptor - TransactedPolicy wrapping a processor
+
[source,java]
----
https://github.com/apache/camel/blob/master/components/camel-spring/src/main/java/org/apache/camel/spring/spi/SpringTransactionPolicy.java

public class SpringTransactionPolicy implements TransactedPolicy {

    public Processor wrap(RouteContext routeContext, Processor processor) {
        TransactionErrorHandler answer;
----
+
* Combined with the TxErrorHanlder - Spring Template !
+
[source,java]
----
https://github.com/apache/camel/blob/master/components/camel-spring/src/main/java/org/apache/camel/spring/spi/TransactionErrorHandler.java

protected void doInTransactionTemplate(final Exchange exchange) {

    // spring transaction template is working best with rollback if you throw it a runtime exception
    // otherwise it may not rollback messages send to JMS queues etc.

    transactionTemplate.execute(new TransactionCallbackWithoutResult() {
----


.References

- https://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01#AA[W3C Http Basic Authentication spec]
ifdef::showscript[]
[.notes]
****

== Transactional Route

When we turn an Apache Camel route into a Transacted route, we are in fact adding an interceptor within the list of the processors handled by Camel. This processor is added used the DSL word ("transacted") corresponding
to the SpringTransactedPolicy. According to the Apache Camel Framework, an Interceptor, which is an interface, is used to wrap the process before or after. In this case, we wrap the processor after and not before. This
interceptor will instantiate a TransactionErrorHandler object which contains the logic to execute a begin/commit or rollback of a Transaction as you can see with the code snippets added within this slide.
As the ErrorHandler uses behind the scene Spring Tx Template, it can be configured with a Spring Tx Manager or a PlatformTxManager like also the Transaction Behavior (New, ...).

****
endif::showscript[]