:scrollbar:
:data-uri:
:noaudio:
:linkattrs:

== NoSQL and Caching

* Several NoSQL components supported:
** Infinispan, HazelCast, EHCache
** MongoDB, Apache Cassandra
** HawtDB, Couchbase, Gora
* Can be used for caching

.References

* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Component_Reference/IDU-Cache.html[Apache Camel Cache Component^]
* link:http://camel.apache.org/infinispan.html[Apache Camel Infinispan Component^]

ifdef::showscript[]

Transcript:

The Apache Camel project also supports non-SQL, or NoSQL, components, such as MongoDB, Apache Cassandra, Couchbase, and EHCache, also known as Hibernate caching. Some of the newer supported technologies include JBoss Infinispan and Apache Gora.

One key benefit of some NoSQL components is that they can be used to cache information and then, by using several Java virtual machines (VMs), replicate the cache between the nodes for high-availability purposes. A cache of key-value pairs can be shared across multiple Camel contexts.


endif::showscript[]
