:scrollbar:
:data-uri:

:linkattrs:

== Transactional Client

* Concept: Make the client’s session transactional so that client can specify transaction boundaries
* Producer or consumer can be transaction
* Not equal to transaction route
* Not all Apache Camel endpoints support transactions
* Transactional client: File, JMS, ActiveMQ, JPA, others

.Reference

* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Development_Guide/MsgEnd-Transactional.html[Transactional Client^]


ifdef::showscript[]

Transcript:

The transactional client pattern is supported by the Apache Camel framework and allows a client to specify transaction boundaries. For a JMS client, this means that the JMS session, not the client or auto-acknowledge, becomes transactional. It also means that the client uses a behind-the-scenes transaction manager to commit or roll back the JMS session.

You can enable the transactional client behavior for an endpoint that is either a producer or a consumer. Setting up this behavior for the endpoint does not mean that the Apache Camel routes become transactional. For that, you use a transacted policy, discussed later in this course.

To use a transactional client, you must identify which client you want to use, because some clients are not transaction-aware. The existing transactional clients are a file, JPA, JMS, and ActiveMQ. You then select the transaction manager to use. This choice depends on where the project is being hosted--in JBoss EAP or JBoss Fuse. Arjuna transaction manager is the default choice for the JBoss EAP platform, and the Apache Aries transaction manager is the default for the JBoss Fuse platform.

endif::showscript[]
