:scrollbar:
:data-uri:
:noaudio:
:linkattrs:

== Persistence

* Apache Camel supports different SQL components:

** JDBC - Java-specification based
** SQL - Spring SQL component (template-based)
** JPA - Java JPA specification
** Hibernate, iBatis, MyBatis
** NoSQL
* Supports Guaranteed Delivery Enterprise Integration Pattern (EIP)
* Some components act only as producers and not consumers

.Reference

* link:http://camel.apache.org/guaranteed-delivery.html[Guaranteed Delivery^]



ifdef::showscript[]

Transcript:

The Apache Camel framework supports the Guaranteed Delivery EIP pattern. Various Camel components, including Spring SQL, JDBC, and JPA, support this pattern.

Before you choose a component for a project, ask yourself these questions:

* Does the component include both a consumer and a producer, or just a producer?
* Is the component fully supported by both a Red Hat subscription and the Apache community?

For components such as Hibernate that do not use Apache License 2, the code is not maintained actively under the Apache Camel project. Ibatis is no longer an Apache project, even though the new project MyBatis is released using an Apache license.

For some projects, the JDBC components may be enough--for example, if the complexity of the data model and queries do not require use of object-relational mapping.

Some components, such as JPA, SQL, Hibernate, and MyBatis, support transactions, while others do not.


endif::showscript[]
