:scrollbar:
:data-uri:


== Transactional Route

* Route turned into transactional route
+
[source,java]
----
from("direct:rollback")
   .transacted("txPolicy")
   .to("sql:delete from projects where id = :#${header.id}")
----

* Implemented using interceptor `SpringTransactionPolicy` wrapping a processor:
+
[source,java]
----
https://github.com/apache/camel/blob/master/components/camel-spring/src/main/java/org/apache/camel/spring/spi/SpringTransactionPolicy.java

public class SpringTransactionPolicy implements TransactedPolicy {

    public Processor wrap(RouteContext routeContext, Processor processor) {
        TransactionErrorHandler answer;
----

* Combined with `TransactionErrorHanlder` in Spring template:
+
[source,java]
----
https://github.com/apache/camel/blob/master/components/camel-spring/src/main/java/org/apache/camel/spring/spi/TransactionErrorHandler.java

protected void doInTransactionTemplate(final Exchange exchange) {

    // spring transaction template is working best with rollback if you throw it a runtime exception
    // otherwise it may not rollback messages send to JMS queues etc.

    transactionTemplate.execute(new TransactionCallbackWithoutResult() {

----


.Reference

* link:https://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01#AA["W3C Hypertext Transfer Protocol -- HTTP/1.1, Access Authentication^"]

ifdef::showscript[]

Transcript:

When you turn an Apache Camel route into a transacted route, you are in fact adding an interceptor within the list of the processors handled by Camel.

You add this processor using the DSL word `transacted`, which corresponds to the `SpringTransactionPolicy` shown here.

According to the Apache Camel framework, an interceptor, which is an interface, is used to wrap a process before or after. In this case, you wrap the processor after. This interceptor instantiates a `TransactionErrorHandler` object that contains the logic to execute a begin, commit, or rollback of a transaction. An example is shown.

The `ErrorHandler` uses a behind-the-scenes Spring transaction template and therefore can be configured with a Spring transaction manager, as shown here, or a platform transaction manager. The transaction behavior&#8212;`New`, and so on--can be configured in the same way.

endif::showscript[]
