:noaudio:

[#persistence-jpa]
== Persistence JPA

* JPA Component supported on JBoss Fuse & EAP as module
* Propose a SharedEntityManager and EntityManager
* Component can be used as Tx Client or part of an Tx Route
* Consumer supports; query, nativeQuery, namedQuery or Parameters

.References

- https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Component_Reference/IDU-JPA.html[Apache Camel on Fuse]
- https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Component_Reference/ch02s02.html#idp4584400[Apache Camel JPA on EAP]
- https://wildflyext.gitbooks.io/wildfly-camel/content/javaee/jpa.html[JPA Persistence with Apache Camel]


ifdef::showscript[]
[.notes]
****

== Persistence JPA

The Apache JPA component is certainly one of the most elaborated component as it offers a panel of many features starting from the consumer to the producer or idempotent repository pattern. It also
can be used in combination with a Transaction Manager to be used as Transaction Client or part of a Transacted Route. One of the key benefit of this component concerns the great flexibility that we have to manage
the query as different modes are proposed query, nativeQuery, namedQuery or Parameters. The latter will use a Java Util Map object to map the information saved within the registry with the query to be parameterized.

****
endif::showscript[]