:scrollbar:
:data-uri:
:toc2:
:linkattrs:

== Split CSV and XML Records Lab

.Goals
* Configure your local environment to develop and implement use cases
* Gain experience using Splitter Enterprise Integration Patterns (EIPs)
* Process CSV records and XML data
* Use a regular expression delimiter to split a data stream
* Extract XML content using the XML Expression Language

.Prerequisites
* Experience with Java, Spring, and Maven
* Experience with Camel development using Red Hat JBoss Fuse

.Use Cases
In this lab, you explore four use cases:

* <<usecase1>>
* <<usecase2>>
* <<usecase3>>
* <<usecase4>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:


== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Split Java Collection

In this test case, you implement a JUnit test case using the `org.jboss.fuse.largefile.tokenize.SplitJavaCollectionTest.java` class and implement three methods.

=== Split Array of String
. Split the contents of the Body containing an Array of String.
. Send the results to the `mock:result` endpoint.
. Create the `testArrayOfString` test method.
. Create the `names` String Array variable.
. Verify that you receive the correct number of split items in the Mock endpoint.
* This number should match the number of entries in the Array.
. Develop the Apache Camel route using the `direct` component and the Splitter EIP for that project.

=== Split Array of Char
. Repeat the previous test, using an Array of the Java Char primitive.
* You can use the letters of your first name for that purpose.
. Create the `testArrayOfPrimitive` method and the `chars` variable.
. Reuse the Apache Camel route created for the previous test case.

=== Split List of String
. Split the contents of the `foo` header, which is represented as a Java `List<String>`.
. Process the `List<String>` in the same way you process the Array of String.
. Develop the Apache Camel route using the `direct` component.
. Use the Splitter with the appropriate Expression Language.


[[usecase2]]
== Split Contents Using Delimiter/Token

In this use case, you implement a test case using the `org.jboss.fuse.largefile.tokenize.SplitUsingDelimiterTest.java` Java class. You verify that a String containing a special character or token can be split. You create two Apache Camel routes and two Java methods to implement the scenario.

=== Split Contents Using Delimiter
. Develop an Apache Camel route starting with a Direct endpoint and consuming a String object that you pass to the Splitter EIP Processor.
. Split the contents of the Body object using the Tokenizer Expression Language, using a carriage return as the delimiter.
. Create a String using the `records` variable name and add a collection of names, separated by a carriage return, to feed the route.
. Validate that the Mock endpoint receives the expected number of split items.
. Verify that the `Split SIZE` Camel property corresponds to the number expected and that the last exchange is completed.
. Name the method `testUsingCarriageReturn`.

=== Split Contents Using Token
. Repeat the previous use case using the `testUsingTokenPairs` method.
. Create a varariable of type String named `record` to contain the list of names, where each name is enclosed by a start token of "[" and an end token of "]".
* Expect your string to look like this: `[charles][jeff]....`.
. Define the syntax of the Apache Camel route to process the contents accordingly, and split it using the token pairs.


[[usecase3]]
== Split Contents Using Regular Expression

In this use case, you use a regular expression to split the contents of the String into a collection of pieces.

. Create a `SplitUsingRegularExpressionTest` Java JUnit test class.
. Create a `testRegExpression` method.
. Use the `record` String to contain the list of names separated by one or more spaces.
. Create a regular expression to extract each name from the String, regardless of whether the name starts with a lower or uppercase character.
. Pass the regular expression as a parameter to the expression language defined for the Splitter EIP.


[[usecase4]]
== Split XML Using Tokenized Language

In this use case, you develop two methods in the `org.jboss.fuse.largefile.tokenize.SplitXMLTest` class.

=== Implement Split Method

In this section, you implement a method to split the contents of an XML String using the XML Expression Language.

. Start with a Direct endpoint in your Apache Camel route.
. Send a String to the consumer that contains a list of orders between `<order>` and `</order>` tags.
. Using the XML Expression Language, configure the Splitter EIP Processor to split the contents.
* You split the `<order/>` tag.
. Verify that the result received by the Mock endpoint contains the number of split items expected, matching the size of the orders.

=== Implement Group Method

. Repeat the previous exercise using another Apache Camel route to group the split items.
. Use a group value of five for a list of ten orders.
. Verify that the Mock endpoint receives two exchanges containing two groups of five orders apiece.

ifdef::showScript[]

endif::showScript[]

