:noaudio:
:toc2:

= Split records, process them in parallel & aggregate Lab

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

<<usecase3>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented using Splitter EIP Pattern
* Process Camel exchanges in parallel
* Aggregate splitted messages to rebuild the original string, stream

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Process splitted items in parallel

The goal of this use case is to design a Junit Test case using the class +org.jboss.fuse.largefile.parallel.ParallelAggregateXMLSplitTest.java+ and to resolve following problem :

Split the content of a string containing the alphabet letters starting from letter +a+ and finishing with the letter +j+. Separate them with a comma. The String must be
send to the +direct:start-parallel+ endpoint and splitted. Execute this process in parallel and set the property +threadNumber+ with the value of the Thread allocated by the pool.
Use this value to define the name of the file +result-${threadNumber}.txt+ where you will append the letter splitted. Count the number of the files created within the +target/split/parallel+ folder and verify that it corresponds to 10.
The Java method to be used to develop the code and unit test is +testParallel+.

IMPORTANT: You can use the Utility Class part of the project to retrieve the Thread Number allocated.


[[usecase2]]
=== Process in parallel using your own ThreadPool

The second use case to be resolved is a variation of the previous. Instead of using the ThreadPool created by Apache Camel when the route is created, you will define your own ThreadPool with 5 threads
and assign it to the Parallel Processor. Like the previous use case, verify that the number of files created within the folder +target/split/parallel-threadpool+ is equal to 5.
The direct endpoint to be used is +direct:start-parallel-threadpool+.

The Java method to be used to develop the code and unit test is +testParallelThreadPool+.


[[usecase3]]
=== Aggregate items splitted

For this last use case, we will use the Aggregation EIP pattern in order aggregate the items splitted to generate the response. Like the previous examples, we will start with our String containing the alphabet letters
separated with the comma separator. This string will be splitted into a collection of items through the Camel route starting from the direct endpoint +start-aggregate"+
Include the aggregator within your route to rebuild the alphabet string but include an integer after each letter. So, the result to be tested should be equivalent to this list
 +a1,b2,c3,d4,e5,f6+

The Java method to be used to develop the code and unit test is +testAggregate+.

ifdef::showScript[]


endif::showScript[]
