:scrollbar:
:data-uri:
:toc2:
:linkattrs:

== Split, Process, and Aggregate Lab

.Goals
* Configure your local environment to develop and implement use cases
* Gain experience using Splitter EIP
* Process Camel Exchanges in parallel
* Aggregate split messages to rebuild the original string and stream

.Prerequisites
* Experience with Java, Spring, and Apache Maven
* Experience with Camel development using Red Hat JBoss Fuse

.Use Cases
In this lab, you explore three use cases:

* <<usecase1>>
* <<usecase2>>
* <<usecase3>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:


== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Process Split Items in Parallel

In this use case, you design a JUnit test case using the `org.jboss.fuse.largefile.parallel.ParallelAggregateXMLSplitTest.java` class.

. Create the `testParallel` Java method to develop the code and unit test.
. Split the contents of a string containing the letters of the alphabet beginning with `a` and ending with `j`, separated by commas.
. Send the String to the `direct:start-parallel` endpoint.
. Split the String.
. Execute this process in parallel and set the `threadNumber` property to the value of the number of threads allocated by the pool.
. Use this value to form the name of the `result-${threadNumber}.txt` file  where you append the split letters.
. Count the number of the files created in the `target/split/parallel` folder and verify that it corresponds to ten.
* You can use the Utility class part of the project to retrieve the number of threads allocated.


[[usecase2]]
== Process in Parallel Using Your Own ThreadPool

This use case is a variation on the first.

. Create the `testParallelThreadPool` Java method to implement the code and unit test.
. Instead of using the thread pool created by Apache Camel when the route is created, define your own `ThreadPool` with five threads.
. Assign the `ThreadPool` to the parallel processor.
. Verify that the number of files created in the `target/split/parallel-threadpool` folder is equal to five, as in the previous use case.
. Use the `direct:start-parallel-threadpool` endpoint.


[[usecase3]]
== Aggregate Split Items

In this use case, you use the Aggregation EIP to aggregate the split items and generate the response.

. Create a `testAggregate` Java method to implement the code and unit test.
. Start with a String containing the letters of the alphabet separated by commas.
. Split this string into a collection of items through a Camel route, starting from the `start-aggregate` Direct endpoint.
. Include the aggregator in your route to rebuild the original string.
. Include an integer after each letter.
* Expect the results to look similar to this list:
+
[source,text]
----
a1,b2,c3,d4,e5,f6
----

ifdef::showScript[]

endif::showScript[]

