:scrollbar:
:data-uri:
:toc2:
:linkattrs:

== Split Items Performance Lab

.Goals
* Configure your local environment to develop and explore use cases
* Iterate through a list of split items to improve performance
* Use a different XML API to parse its contents (StAX, DOM)
* Aggregate the result to reduce the number of writes to the file system

.Prerequisites
* Experience with Java, Spring, and Maven
* Experience with Camel development using Red Hat JBoss Fuse

.Use Cases
In this lab, you examine three use cases:

* <<usecase1>>
* <<usecase2>>
* <<usecase3>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module of the skeleton project.

:numbered:


== Prepare Lab Environment

=== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
|====

=== Install Lab Project

Download and install locally the latest release of the lab project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to implement the use cases, import the project into a new JBoss Developer Studio workspace.


[[usecase1]]
== Stream CSV Records

In this use case, you demonstrate that you can improve file split processing for files containing many records.

=== Evaluate Streaming Options

. Implement `testWithoutStream` and `testWithStream` JUnit methods using the `org.jboss.fuse.largefile.performance.StreamCsvTest` Java test class.
. Use the streaming option of the Splitter EIP.
. Demonstrate that using the streaming option is faster than not using it.

=== Compare Elapsed Time

. Measure the elapsed time required by the Apache Camel route to split and process ten files, each containing 10,000 records.
. Generate the files containing the CSV records using the `gen-csv` Maven profile.
. Make the generated files available under the `target/data` folder.
. Consume the files.
. Split the contents in a route using a carriage return as the delimiter.
. Send the result to the LogEIP processor.
. Define the logging level as `DEBUG`.
* The files should not be deleted by the Camel file consumer.
. Build an expression using the link:http://camel.apache.org/notifybuilder.html[NotificationBuilder^] so that you are notified of each exchange processed.
* This is in contrast to using the Mock endpoint for processing the exchanges.


[[usecase2]]
== Compare StAX Versus DOM Splitting

In this use case, you compare the StAX API against a DOM API in processing large XML files.

. Build the project using the `org.jboss.fuse.largefile.performance.StaxDomTest` Java class.
. Implement two JUnit methods called `testWithXPath` and `testWithXTokenizer`.
. As in the previous use case, create Apache Camel routes that consume the files generated by the `gen-xml` Maven profile under the `target/data` directory.
. Use both the StAX API and the DOM API to split and process ten files, each containing 10,0000 XML records.
. Measure the elapsed time to process the split items.
. Measure the memory consumed to run each Camel route and get the split items.
* The files should not be deleted by the Camel file consumer.
. Build an expression that provides notification when each exchange is processed using the link:http://camel.apache.org/notifybuilder.html[NotificationBuilder^].


[[usecase3]]
== Improve Write Performance

In this use case, you explore improving the performance of writing split contents to a file. You leverage the techniques presented in this lab, using a maximum of three strategies in your implementation.

. Use the `org.jboss.fuse.largefile.performance.SpeedWriteProcessTest` Java class to implement the project.
. Implement the project using a dedicated Apache Camel route, independent of the strategy you use.
. Create JUnit test methods for each strategy.
. Consume the CSV files generated from the `gen-csv` Maven profile without deleting them.
. Split the contents using the carriage return as the delimiter.
. Save the processed results in the `target/data/out` folder with a filename of `bigfile.txt`.
. Check the elapsed time to process the Apache Camel route.
. Save the elapsed time to the `bigfile.txt` file.
. Evaluate your solution by comparing the elapsed times for each strategy.

ifdef::showScript[]

endif::showScript[]

