:noaudio:
:toc2:

= Improve performance of the Splitted items Lab

In this lab you resolve the following use cases:

<<usecase1>>

<<usecase2>>

<<usecase3>>

.Goals
* Configure your local environment to develop and resolve use cases
* Iterate through the list of the items to be splitted to boost the performance
* Use a different XML Api to parse its content (Stax, DOM)
* Aggregate the result to reduce the number of write

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project.

[[usecase1]]
=== Stream CSV records

The goal of this use case is to demonstrate that we can improve the splitting processing of files containing many records using the streaming option of the Splitter EIP Pattern.
So, you will use the Java Test class +org.jboss.fuse.largefile.performance.StreamCsvTest+ to develop 2 Junit methods +testWithoutStream+ and +testWithStream+ where you will demonstrate
that the streaming option is faster compare to the scenatio where you don't use it.

For that purpose, you will measure the elapsed time required by the Apache Camel route to split and process 10 files containing each 100.000 records. The files, which contain
CSV records, can be generated using the maven profile +gen-csv+. The files generated will be available under the folder +target/data+.

Then, you will consume them, split the content in a route using as delimiter the carriage return character and send the result to the LOG EIP processor where the logging level is defined DEBUG.

IMPORTANT: Instead of using the mock endpoint to get all the exchanges processed, you can build an Expression using the http://camel.apache.org/notifybuilder.html[NotificationBuilder] to be notified about the exchanged processed.


[[usecase2]]
=== Compare Stax vs DOM splitting


[[usecase3]]
=== Aggregate result to write a few times


[[usecase4]]
=== Use Async Component


ifdef::showScript[]


endif::showScript[]
