:scrollbar:
:data-uri:


== XML Parser and API

* Choose expression language/XML parser carefully because:
** XPathBuilder loads XML in memory using Document Object Model (DOM)
** Some StAX APIs do not support offset and location


ifdef::showscript[]

Transcript:

When you select the Apache Camel expression language or tokenizer to use for parsing and splitting the content, it is important that you review the XML parser and API that is used in the background when you design the project for the customer. For example, the `XPathBuilder` expression, which is part of the XPath language, uses the Document Object Model, or DOM, API to load the objects in memory to find the tag to be extracted.

As another example, the StAX Xerces API, which is packaged with the JDK, does not implement the location and offset features that the Woodstox API supports for iterating through a list of items. However, if the number of objects to be created into memory is not large, you can use XPath, because it supports iterating through the list of discovered nodes.

endif::showscript[]
