:scrollbar:
:data-uri:


== Tokenize

.Groups

* Goal: Group number of lines into single chunk
* Number that dictates how many groups to combine, must be positive
* Streaming option directs splitter not to read whole file at once
** Results in improved performance if file is large

* Example:
+
[source,xml]
----
<route>
  <from uri="file:inbox"/>
  <split streaming="true">
    <tokenize token="\n" group="1000"/>
    <to uri="activemq:queue:order"/>
  </split>
</route>
----

ifdef::showscript[]

Transcript:

Another benefit of the Tokenize language is that it lets you group split items. Similar to a batch mechanism, this feature lets you generate a group of items that the Camel processor adds within the newly created exchange. Similar to the `stream` option, this option helps reduce the memory footprint by adding the group of items as an object within the exchange. To use this option, you define the group XML attribute in the XML tag or pass the group integer value in the `tokenize` method.

The grouping value must be a valid integer. It cannot be null or negative.

endif::showscript[]
