:scrollbar:
:data-uri:


== `SplitterIterable` Class

* Default: Collection, array, and list

* Example:
+
[source,java]
----
from("direct:splitUsingBody").split(body()).to("mock:result");
----
+
* Can be extended to support your own strategy
* Benefit: Iterates over collection of objects without exposing implementation details

* Example:
+

[source,java]
----
public class GameCollection implements Iterable<Game> {
 private Vector<Game> games;

 public GameCollection() {
  games = new Vector<Game>();
 }

 public void add(Game game) {
  games.add(game);
 }

 @Override
 public Iterator<Game> iterator() {
  return games.iterator();
 }
}
----

ifdef::showscript[]

Transcript:

Whenever the Splitter processor gets an object from the body or header using any of the following languages, the processor automatically splits the object's content using the `SplitterIterable` class. The languages are:

* Simple, body, or header language
* Object-Graph Navigation Language, or OGNL
* MVFLEX Expression Language, or MVEL

MVEL can be a Java collection, an array, a list, an array of Java primitives, or a string with values separated by the specified delimiter.

As a Java developer, you need to decide when you can use or create your own collection. A collection lets you mask the implementation details. You can change it without needing to update the existing Apache Camel route. The example shown here contains a `Vector` in which you add a `Games` object. The `Iterator` method returns an `Iterator` object that the Splitter processor can use to iterate through the list of included items.

endif::showscript[]
