:scrollbar:
:data-uri:


== Performance Optimization Strategies

* Reduce number of write operations to output file
* Use aggregation to group results before writing to output file
** Result can be sent to asynchronous component (SEDA, JMS)
* Prefer `StringBuilder` within `StringBodyAggregator`

ifdef::showscript[]

Transcript:

A variety of strategies are available to improve the performance of your application when you must process a large volume of records.

As mentioned previously, you can use the `stream` option to avoid processing all of the objects created as a list after the split of the content in memory. This option lets you iterate through the list. To use this option, verify that the object being used supports the Iterable JDK interface. Then evaluate if processing the workload in parallel is an option. Like the other approaches described here, adopting parallel processing requires designing a benchmark against which you can perform a stress test for the project using dummy files and data. The test lets you evaluate the threads to use and the policy to configure to release the threads from the pool.

Whenever possible, use the `group` option. This option lets you process as a batch unit, or group, of work, the objects created and added within the body of the child exchange created by the Splitter processor.

To reduce the number of write operations needed when you create a file on the file system, use the Aggregation EIP. This buffers the result processed by the child processor called by the Splitter processor.

Do not use a Java string object to manipulate the old and new Camel Exchanges within the Aggregator processor. Instead, use `StringBuilder` or `StringBuffer` that you ultimately convert to a string.

Instead of sending the string object created to the file producer, use an asynchronous component such as JMS or SEDA to rebuild the file in a separate route using a different nonblocking thread.

endif::showscript[]
