:scrollbar:
:data-uri:


== Tokenize

* Built-in language of `camel-core`
* Goal: Tokenize text documents using:
** Specified delimiter pattern (for example,`\n`)
** Regex
* Can tokenize XML content using the XMLTokenize/xtoken language
* Use `streaming` attribute to iterate through result
+
* Example:
+
[source,xml]
----
<split streaming="true">
    <tokenize token="\n"/>
    <tokenize token="order" xml="true"/>
----
* To process content as one atomic unit, use option +shareUnitOfWork+
* Control exception error propagation with option +stopOnException+

* Example:
+
[source,xml]
----
<route>
    <from uri="direct:start"/>
    <to uri="mock:a"/>
    <!-- share unit of work in the splitter, which tells Camel to propagate failures from
         processing the splitted messages back to the result of the splitter, which allows
         it to act as a combined unit of work -->
    <split shareUnitOfWork="true">
      <tokenize token=","/>
      <to uri="mock:b"/>
      <to uri="direct:line"/>
    </split>
----

ifdef::showscript[]

Transcript:

When the incoming object to be split is not a list, an array list, or an iterable object, a different Apache Camel language is required to create the list of items to be processed.

For this purpose, the framework provides the Tokenize language. This language is built into `camel-core`. Different variants of Tokenize exist, including TokenizePair, TokenizeXML, and XTokenize to process XML files, CSV records, or any stream of data that can be split according to a token. The token is a specified delimiter pattern such as `\n` or a comma or a regular expression.

To use one of the Tokenize languages, define the XML tag within the Apache Camel route or its corresponding Java fluent method and pass the token to be used as a parameter. For example, to split all of the CSV records defined in a string, use the carriage return delimiter.

Using Tokenize, the Splitter generates a list of items and a new exchange for each item. If the stream of data to be processed is very large or important, use the streaming option. This option tells the Splitter processor that instead of loading all of the Java objects in memory, you want to iterate through the list of items. As a general rule, the object that you use to split the content must support a Java-iterable interface like the `Scanner` class and `ArrayList` class.

When a stream of data is split into a collection of items, the items are processed independently from one another. If the logic requires Camel to process the content as one atomic unit during routing, define the `shareUnitOfWork` option at the level of the `split` pattern, as shown in the second example.

To control exception error propagation, use the `stopOnException` option.

endif::showscript[]
