:noaudio:

[#suggested-readings]
== Suggested Readings & work

.Exercise yourself
* Design a Camel project using the File component and the Splitter Pattern
* Review the Apache Camel Splitter & Aggregator pattern

.Readings
* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Development_Guide/MsgRout-Splitter.html[Splitter Pattern]
* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Development_Guide/MsgRout-Aggregator.html[Aggregator]
* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Development_Guide/Intro.html#Intro-Overview[Languages & Expression]


ifdef::showscript[]
[.notes]
****

== Suggested Readings & work

In order to prepare this module, we suggest that you review the links provided but also that you read the chapter about the EIP Patterns within the Camel Development with JBoss Fuse course.
As we will investigate the strategies available to process Large Files but also Messages containing Big String, XML files, it is important that you create some Camel Routes using the
file, ftp or JMS components to collect such big volumes of information to be processed and you review how to use the EIP Splitter & Aggregator patterns.

****
endif::showscript[]
