:scrollbar:
:data-uri:
:noaudio:

== TokenizeXML

* Goal: split XML content
* Available using TokenizeXML and XTokenize languages

* Example:
+
[source,xml]
----
<from uri="file:inbox"/>
  <split streaming="true">
    <tokenize token="order" xml="true"/>
    <to uri="activemq:queue:order"/>
  </split>
----
* XTokenize uses StAX parser
* Best suited for complex XML processing

* Example:
+
[source,xml]
----
<from uri="file:target/xtokenizer"/>
   <split>
     <!-- split the file using XML tokenizer, where we grab the order tag,
          and inject the namespaces declarations from its ancestor nodes -->
     <xtokenize>//s:orders/s:order</xtokenize>
----

ifdef::showscript[]

Transcript:

The TokenizeXML and XTokenize expression languages let you process XML and split streams. Although they provide the same functionality--splitting XML content based on an XML tag--each uses a different API in the background. The TokenizeXML expression language uses a regular expression to parse and extract the tag from the XML stream, while XTokenize relies on the StAX API.

Here is an example of TokenizeXML: If the XML to be parsed contains a list of `<order>` tags defined under the `<orders>` parent tag, by using the `order` token attribute, the split content will contain each `<order>` and closing `<order>` tag with its content.

To inherit a namespace defined in a parent tag, you can either set the `inheritNamespaceTagName` attribute within the XML tag or pass a second parameter to the fluent DSL method with the name of the tag that contains the namespace to be included in the response.

To build more a complex XML expression to split content, Red Hat recommends using the XTokenize language. This language recognizes XML namespaces and handles simple and complex XML structures naturally and efficiently.

Two arguments control the behavior of the tokenizer. The first argument specifies the element using a path notation. This path notation uses a subset of XPath with wildcard support. The second argument represents the extraction mode.

The available extraction modes include `i`, which is the default behavior and injects the contextual namespace bindings into the extracted token; `w`, which wraps the extracted token in its ancestor context; `u`, which unwraps the extracted token to its child context; and `t`, which extracts the text content of the specified element.

Because XTokenize is based on StAX, it uses the StAX location API. It also requires a StAX reader implementation such as Woodstox that correctly returns the offset position pointing to the beginning of each event-triggering segment--for example, the offset position of `<` at each start and end element event.

Using a StAX reader that does not implement the API correctly results in invalid XML snippets after the content is split.

endif::showscript[]
