:scrollbar:
:data-uri:


== Parallel Processing and Aggregation

* Use `parallel` option to process split message in parallel
* Assign dedicated thread pool using `executorServiceRef` option
* To aggregate result, include aggregator

* Example:
+
[source,xml]
----
from("direct:start")
.split().tokenize(",").aggregationStrategy(new MyAggregationStrategy())
  ...
  .log(">> Splitted msg : ${body}")
  .end()
.to("mock:result");
----

ifdef::showscript[]

Transcript:

By default, the Splitter processor uses one thread to split the stream of data--string, file, and so on--and process each split item. Because the processed item may require very complex transformations performed by subsequent processors, if you are not careful, the benefits obtained from using iterative steps may be negated. To prevent this, you can parallelize the workload using the `parallel` attribute. When you enable this option, the Splitter processor uses additional threads that are part of the threadpool. The threads can be assigned by default to the `DefaultCamelContext` or created specifically for the Splitter.

To use your own thread pool, configure the `executorServiceRef` attribute to provide the reference of the bean instantiated for that purpose.

After the splitting process concludes, some applications may need you to rebuild the file, string, or stream that was split. To accomplish this, use the aggregation strategy that you specified when you set up the Splitter.

endif::showscript[]
