:scrollbar:
:data-uri:

:linkattrs:

== Splitter

* EIP pattern
* Goal: Split message into number of pieces and process them individually
* New exchange is created for every piece/item created
* Reduce memory footprint for large files consumed
+
.Example:
+
[source,xml]
----
<split>
   <simple>${body}</simple>
   <to uri="direct://processExchange"/>
</split>
----

.Reference
* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_Camel_Development_Guide/MsgRout-Splitter.html[Splitter^]

ifdef::showscript[]

Transcript:

The Splitter EIP is currently implemented by the Apache Camel integration framework. It lets you split a message into multiple smaller parts that are then processed individually. This reduces the memory footprint when consuming large files.

With this pattern, the framework creates a new exchange containing the content of the item or piece created within its `body` object. A header or property is attached to each created Exchange that includes the size of the split string, a counter that increases for each subexchange created, and a property indicating that this is the last exchange split.

By default, the Splitter pattern can process a list or array of Java objects if they are attached to the `body` object of the exchange. Using simple expression language, you can extract the `body` object of the exchange that you pass to the Splitter processor to split the content. An example is shown here.

endif::showscript[]
