package org.jboss.fuse.security.wssecurity;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.endpoint.Server;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.interceptor.LoggingInInterceptor;
import org.apache.cxf.interceptor.LoggingOutInterceptor;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.jaxws.JaxWsServerFactoryBean;
import org.apache.cxf.service.Service;
import org.apache.cxf.transport.local.LocalTransportFactory;
import org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.wss4j.dom.WSConstants;
import org.apache.wss4j.dom.handler.WSHandlerConstants;

import org.apache.wss4j.stax.ext.WSSConstants;
import org.jboss.fuse.security.AbstractSecurityTest;
import org.jboss.fuse.security.service.Echo;
import org.jboss.fuse.security.service.EchoImpl;
import org.jboss.fuse.security.service.PwdCallback;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class WSSecurityTest extends AbstractSecurityTest {

    protected WSS4JInInterceptor wsIn;
    protected WSS4JOutInterceptor wsOut;
    private Echo echo;
    private Client client;
    private JaxWsServerFactoryBean factory;

    public void setUpWSEndpoint(String PORT) {
        // EXCLUDE-BEGIN
        factory = new JaxWsServerFactoryBean();
        factory.setServiceBean(new EchoImpl());
        if(PORT!= null) {
            factory.setAddress("http://localhost:" + PORT + "/Echo");
        } else {
            factory.setAddress("local://Echo");
            factory.setTransportId(LocalTransportFactory.TRANSPORT_ID);
        }
        Server server = factory.create();
        Service service = server.getEndpoint().getService();

        wsIn = new WSS4JInInterceptor();
        wsIn.setProperty(WSHandlerConstants.SIG_VER_PROP_FILE, "org/jboss/fuse/security/common/insecurity.properties");
        wsIn.setProperty(WSHandlerConstants.DEC_PROP_FILE, "org/jboss/fuse/security/common/insecurity.properties");
        wsIn.setProperty(WSHandlerConstants.PW_CALLBACK_CLASS, PwdCallback.class.getName());

        service.getInInterceptors().add(wsIn);

        wsOut = new WSS4JOutInterceptor();
        wsOut.setProperty(WSHandlerConstants.SIG_PROP_FILE, "org/jboss/fuse/security/common/outsecurity.properties");
        wsOut.setProperty(WSHandlerConstants.ENC_PROP_FILE, "org/jboss/fuse/security/common/outsecurity.properties");
        service.getOutInterceptors().add(wsOut);
        // EXCLUDE-END
    }

    public void setupClient() {
        // EXCLUDE-BEGIN
        JaxWsProxyFactoryBean proxyFac = new JaxWsProxyFactoryBean();
        proxyFac.setServiceClass(Echo.class);
        proxyFac.setAddress("local://Echo");
        proxyFac.getClientFactoryBean().setTransportId(LocalTransportFactory.TRANSPORT_ID);

        echo = (Echo) proxyFac.create();

        client = ClientProxy.getClient(echo);
        //client.getInInterceptors().add(new LoggingInInterceptor());
        client.getInInterceptors().add(wsIn);
        //client.getOutInterceptors().add(new LoggingOutInterceptor());
        client.getOutInterceptors().add(wsOut);
        // EXCLUDE-END
    }

    @Before
    public void setUpService() throws Exception {
        // Create the Web Service endpoint exposing the Echo Service locally without HTTP Transport
        setUpWSEndpoint(null);

        // Create the client
        setupClient();
    }

    /**
     * Issue a SOAP Message where the SOAP Header generated by the WSS4J Interceptor of the client will include a SOAP WSSE header section with a username and a timestamp to authenticate the JAXWS Client
     * request. This use case should issue a user with a wrong password and the test must validate that it fails with the message "Security processing failed."
     */
    @Test
    public void testUsernameTokenWrongPassword() throws Exception {
        // EXCLUDE-BEGIN
        String actions = WSHandlerConstants.TIMESTAMP + " " + WSHandlerConstants.USERNAME_TOKEN;

        // Server Side
        wsIn.setProperty(WSHandlerConstants.ACTION, actions);

        // Client Side
        wsOut.setProperty(WSHandlerConstants.ACTION, actions);
        wsOut.setProperty(WSHandlerConstants.USER, "cmoulliard");
        wsOut.setProperty(WSHandlerConstants.PASSWORD_TYPE, "text");
        wsOut.setProperty("password", "password");

        try {
            assertEquals("test", echo.echo("test"));
            fail("Exception expected");
        } catch(Exception ex) {
            assertEquals("Security processing failed.", ex.getMessage());
        }
        // EXCLUDE-END
    }

    /**
     * Issue a SOAP Message where the SOAP Header generated by the WSS4J Interceptor of the client will include a SOAP WSSE header section with a username and a timestamp to authenticate the JAXWS Client
     * request. This use case should issue a user with a correct password retrieved from the PwdCallback class. The must validate that when we call the Echo service with the message "test", we get as response "test
     */
    @Test public void testUsernameToken() throws Exception {
        // EXCLUDE-BEGIN
        String actions = WSHandlerConstants.TIMESTAMP + " " + WSHandlerConstants.USERNAME_TOKEN;

        // Server Side
        wsIn.setProperty(WSHandlerConstants.ACTION, actions);

        // Client Side
        wsOut.setProperty(WSHandlerConstants.ACTION, actions);
        wsOut.setProperty(WSHandlerConstants.USER, "cmoulliard");
        wsOut.setProperty(WSHandlerConstants.PW_CALLBACK_CLASS, PwdCallback.class.getName());

        assertEquals("test", echo.echo("test"));
        // EXCLUDE-END
    }

    /**
     * Issue a SOAP Message where the SOAP Header includes a WSSE section to sign the message generated by the JAXWS Client
     * The Algorithm to be used to sign the body of the message is SHA256 while the Digest Algo should be RSA SHA1
     * The parts to be signed are the Body and the TimeStamp.
     */
    @Test public void testSignature() throws Exception {
        // EXCLUDE-BEGIN
        String actions = WSHandlerConstants.TIMESTAMP + " " + WSHandlerConstants.SIGNATURE;
        String BODY_PART = "{}{" + WSSConstants.NS_SOAP11 + "}Body;";
        String TIMESTAMP_PART = "{}{" + WSSConstants.NS_WSU10 + "}Timestamp;";

        // Server Side
        wsIn.setProperty(WSHandlerConstants.ACTION, actions);
        wsIn.setProperty(WSHandlerConstants.SIG_DIGEST_ALGO, WSConstants.SHA256);
        wsIn.setProperty(WSHandlerConstants.SIG_ALGO, WSConstants.RSA_SHA1);

        // Client Side
        wsOut.setProperty(WSHandlerConstants.ACTION, actions);
        wsOut.setProperty(WSHandlerConstants.USER, "integration"); // Alias of the user = certificate to be used to sign the Body/Timestamp using the Key
        wsOut.setProperty(WSHandlerConstants.PW_CALLBACK_CLASS, PwdCallback.class.getName());
        wsOut.setProperty(WSHandlerConstants.SIG_DIGEST_ALGO, WSConstants.SHA256);
        wsOut.setProperty(WSHandlerConstants.SIG_ALGO, WSConstants.RSA_SHA1);
        wsOut.setProperty(WSHandlerConstants.SIGNATURE_PARTS, BODY_PART + TIMESTAMP_PART);

        assertEquals("test", echo.echo("test"));
        // EXCLUDE-END
    }

    /**
     * Issue a SOAP Message where the SOAP Header includes a WSSE section to sign and encrypt the message generated by the JAXWS Client
     */
    @Test public void testEncryptionPlusSig() throws Exception {
        // EXCLUDE-BEGIN
        // Server side
        wsIn.setProperty(WSHandlerConstants.ACTION,
                WSHandlerConstants.ENCRYPT + " " + WSHandlerConstants.SIGNATURE);

        // Client Side
        wsOut.setProperty(WSHandlerConstants.USER, "integration");
        wsOut.setProperty(WSHandlerConstants.PW_CALLBACK_CLASS, PwdCallback.class.getName());
        wsOut.setProperty(WSHandlerConstants.ACTION,
                WSHandlerConstants.ENCRYPT + " " + WSHandlerConstants.SIGNATURE);

        assertEquals("test", echo.echo("test"));
        // EXCLUDE-END
    }

}
