:scrollbar:
:data-uri:
:toc2:
:linkattrs:
:sourcedir: ../code/security-ws/src/test/java


== Web Service Security Lab

.Goals
* Configure your local environment to develop and explore use cases
* Become more familiar with WS-Security specification
* Design a web service project and secure it
* Send and receive messages using CXF factory beans class

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with web service technology and SOAP messaging
* Understanding of PKI and message encryption and signatures
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you explore four use cases:

* <<usecase1>>

* <<usecase2>>

* <<usecase3>>

* <<usecase4>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module part of the skeleton project.

Refer to the relevant Apache CXF documentation:

* link:http://cxf.apache.org/docs/ws-security.html["WS-Security^"]
* link:http://cxf.apache.org/docs/a-simple-jax-ws-service.html["A simple JAX-WS service^"]


:numbered:

== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
| link:http://sourceforge.net/projects/soapui/files/[SoapUI^] | Latest version | Optional
|====

=== Install Lab Project

Download and install locally the latest release of the project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to explore the use cases, import the project into a new JBoss Developer Studio workspace.

=== Create Keys and Certificates

For this lab, the keys are generated for you. Outside the lab environment, use the `keytool` command to create the private and public keys and corresponding certificates for your users:

[source,text]
----
keytool -genkey -alias integration  -keyalg RSA  -keypass secUr1t8 -storepass secUr1t8 -keystore security-ws/src/test/resources/integrationstore.jks
----

* When prompted for the first and last names, enter `localhost`.
* Specify any values for the other prompts.
* Answer `yes` to confirm the value of the Common Name (CN).
* Expect the resulting Common Name to look similar to this: `CN=localhost, OU=integration, O=enablement, L=fuse, ST=Unknown, C=US`.


[[usecase1]]
== Generate WSSE SOAP Header with Invalid Password

CXF uses WSS4J to implement WS-Security. WS-Security can be activated in two ways:

* WS-SecurityPolicy, which provides a comprehensive and sophisticated validation of the security properties of a received message

* CXF interceptors added to your service and/or client

In this use case, you design a JUnit test case where the `org.jboss.fuse.security.WSSecurityTest` class includes an `@Test` JUnit method. This test case issues a SOAP message where the SOAP `Header` element is generated by the WSS4J interceptor of the client. It includes a SOAP WSSE `Header` section with a username, password, and timestamp to authenticate the JAXWS client request.

This use case issues a message containing a SOAP `Header` with an incorrect password. The test must validate that the exception message reported during the failed process contains a "Security processing failed" message.

. Use the API to set up the WSS4J interceptors to enable WS-Security within CXF for a server or a client.
* Outside the lab environment, the API is normally used for standalone web services, while Spring XML configuration is used for servlet-hosted web services.

. Create the CXF web service using the `JaxWsServerFactoryBean` class.
* For the the JAXWS client, which is responsible for consuming the echo service, use the `JaxWsProxyFactoryBean` class.
* Use the CXF local transport to configure the client rather than an HTTP transport.

. Develop both classes using the CXF interceptor pattern to generate the SOAP WSSE section header and process this section at the server site.
* Use and configure the Apache WSS4J framework with the CXF In/Out interceptors.

. Annotate the Java classes with `JAX-WS @WebService`, rather than a WSDL file.
* The `Echo` interface and `EchoImpl` Java class implementing this interface are provided within the project.
+
[NOTE]
WS-Security supports many ways of specifying tokens including a `UsernameToken` header. A username and either a password or password digest can be used to authenticate to a remote endpoint. You can use a password callback class to retrieve or prompt for a password so that WS-Security can determine if the user is authorized.

. Configure the WSS4J class using these parameters:

* Actions: `UsernameToken` and `Timestamp`
* User: Your user name, as defined within the `org.jboss.fuse.security.service.PwdCallback` class
* Password: An incorrect password
* Password Type: Text

. Define the WSS4J parameters using the `setProperty` method of the `AbstractWSS4JInterceptor` class.

. Configure the server-side `JaxWsServerFactoryBean` and client-side `JaxWsProxyFactoryBean` to use the `insecurity.properties` and `outsecurity.properties` crypto configuration files.

* This configuration enables message signing and decryption using the `signatureVerificationPropFile` and `decryptionPropFile` parameters.

. Place the properties files in the `org/jboss/fuse/security/common` resource directory.

* Both of the crypto configuration files use the same `integrationstore.jks` keystore file.


//[source,java]
//----
//include::{sourcedir}/org/jboss/fuse/security/wssecurity/WSSecurityTest.java[lines=90..107]
//----


[[usecase2]]
== Generate WSSE SOAP Header with Valid Password

This use case expands on the previous one, but instead of sending an incorrect password, you specify the correct password assigned to your username within the WSSE section of the SOAP `Header`.

. Use the `passwordCallbackClass` as the WSS4J parameter to let the interceptor retrieve the password from the `PwdCallback` class, which implements the `CallbackHandler` interface.
. In the handle method, iterate over the list of users until you find the user.
. Set the corresponding password to the `WSPasswordCallback` object using the `setPassword` method.
. Use the same actions as defined for the previous use case in order to generate a header containing the user credentials and timestamp.


[[usecase3]]
== Generate SOAP Message and Sign Content

In this use case, you sign the body of a message and its timestamp. The algorithm used to digest the signed content is `http://www.w3.org/2001/04/xmlenc#sha256`, and the algorithm used to sign the content is `http://www.w3.org/2000/09/xmldsig#rsa-sha1`. You must set the `Signature` and `Timestamp` actions. The `UsernameToken` does not need to be set.

Signing a message allows the receiver to verify that the message was not altered in transit and that it originated from the correct sender. The sender encrypts a digest, or hash, of the message with its private key, and the recipient decrypts the hash with the sender's public key. The recipient checks that the digest values calculated by both the sender and recipient are the same.

. Use `keytool` to ensure that the client's public key is imported into the server's keystore.

. Configure the WSS4J class using these parameters:

* Actions: `Timestamp` and `Signature`
* Parts to be signed: `signatureParts`
* Parts: `Body` and `Timestamp`
* Sign algorithm: `signatureAlgorithm`
* Digest sign algorithm: `signatureDigestAlgorithm`

. Configure the server and/or client classes appropriately, as well as the In/Out interceptors.
. Use the appropriate user's key and certificate to sign the message.


[[usecase4]]
== Generate SOAP Message, and Sign and Encrypt Content

For this last use case, you encrypt and sign the content of the message.

Encryption involves the sender encrypting a message with the recipient's public key to ensure that only that recipient can read the message. Only the corresponding private key can decrypt the message and that private key is held only by the recipient and not shared with other users. In order to encrypt a message with the recipient's public key, that key must be available in the sender's keystore.

. Follow similar steps to those in the previous signing exercise to encrypt and sign the SOAP message.

. Configure the WSS4J class using this parameter:

* Actions: `Encrypt` and `Signature`

ifdef::showscript[]

:numbered!:

== Instructor Information

* Time estimated: 2d

* How to evaluate the student's solution:

** Verify that the JUnit tests are passing successfully.
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, etc.)
** Review the solutions proposed by the student to resolve the different use cases.
** For each use case, verify that the SOAP request and response populated. They should be comparable to what you can find within the `output/ws-*` corresponding folder.

endif::showscript[]
