:noaudio:
:sourcedir: ../../code/security-ws/src/test/java

= WS Security Lab

.Goals
* todo
* todo

== Description

== Teacher info

* Time estimated : 1h30 - 2h

* How to evaluate the solution of the student :

** Review the Apache Camel Route created and how it has been designed to split the content and handle the exception (= DLQ pattern)

== Prerequisites

== Install Required Software on Your Machine

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[8.1.0.GA] | Required. Account on the jboss.org web site is needed. |
| Integration Stack | https://devstudio.jboss.com/updates/8.0/integration-stack/[8.0.2] | Required. Account on the jboss.org web site is needed. |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest] | Optional |
|===

== Install Lab Assets

Clone the lab from the skeleton branch of the following GitHub repository: https://github.com/redhat-gpe/fuse_integration_advanced.git .

== Configure Your Local Maven Environment

All the usecases to be designed involve using Apache Maven modules with dependencies on Apache Maven libraries supported in JBoss Fuse. Red Hat provides both online and offline Maven repositories for JBoss Fuse.
Follow these steps to configure these online repositories on your machine:

. Edit the Apache Maven `settings.xml` file located under the directory `$HOME/.m2` or `~/.m2`.
+
[NOTE]
If this file does not exist under this location, you can also edit the same file which is available under the `conf` subdirectory of the Apache Maven installation directory.
. Replace the contents of your Maven `$HOME/.m2/settings.xml` with this {settings}.
. Review the details of your new Fuse enabled `$HOME/.m2/settings.xml`
.. Within the `<profile>` tags in the `settings.xml` are defined the `JBoss Fuse` repositories that you need to build the code during execution of `mvn compile` or `mvn install` commands.
.. Within the `<activeProfile>` tags in the `settings.xml` is the name of the default profile used when Apache Maven is running.


== Keys and certificates

Follow these instructions in order to create the Private/Public keys of the users to be used and their corresponding certificates

[source]
----
keytool -genkey -alias integration  -keyalg RSA  -keypass secUr1t8 -storepass secUr1t8 -keystore security/src/test/resources/integrationstore.jks
----

Add `localhost` as name for the first and last name field. You can define the value for the other fields as you want.
Here is an example `CN=localhost, OU=integration, O=enablement, L=fuse, ST=Unknown, C=US`

== Use cases

=== WSSE with Username and Timestamp

This is a test to add a snippet code

[source,java]
----
include::{sourcedir}/org/jboss/fuse/security/wssecurity/WSSecurityTest.java[lines=90..107]
----


ifdef::showScript[]


endif::showScript[]
