:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= WS Trust Lab

In this lab you resolve the following use cases:

<<usecase1>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about WS-Trust specification
* Design Web Service project and secure it
* Send and receive messages using the CXF Bus and XML Config Files

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with Web Service Technology & SOAP Messages
* PKI & encryption/decryption background
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
| Java Crypto Unlimited | http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java 8] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project

[[usecase1]]
=== Use a Security Token Service to issue a token used by the Client

The goal of this use case is to use a Security Token Service to issue a SAML token v2.0 that the SOAP Client will use to send its SOAP Request message to the Web Service which will control the
SAML token received and will return a response if the issued request is authenticated.

The skeleton of the project is similar to what we done with the previous use cases. Nevertheless, there are some differences as a Security Token Service (= Web Service Endpoint) must be exposed to the client
in order to request/renew or cancel a Security Token, the WSDL file of the client must include a WS-Security Policy containing an Initiator Token

Remark : To simplify your work, the STS Server (Spring XML config file, WSDL file, STS Keystore) is already configured like the Hello World Endpoint (the the Spring Config file, Server Keystore)


.Spring XML Client File
* Create a new +wssec-client.xml+ file within the folder +src/test/resources/org/jboss/fuse/wstrust/wssecuritypolicy+
* Create the <jaxws:client/> bean to use the +SoapPort+ port binding as defined within the Hello World wsdl file
* Add the +ws-security+ parameters required to configure the :
** The Crypto/Encrypt property configuration file(s) to use for signature
** The username(s) of the key/Certificate to be used to sign/encrypt
** The CallBackHandler pointing to the java class +ClientCallbackHandler+
* Create a +org.apache.cxf.ws.security.trust.STSClient+ bean and assign it to the ws-security STS Client parameter
* Configure this bean with the following parameters :
** wsdl location : `http://localhost:8080/SecurityTokenService/UT?wsdl`
** Service name : `{http://docs.oasis-open.org/ws-sx/ws-trust/200512/}SecurityTokenService`
** Endpoint name : `{http://docs.oasis-open.org/ws-sx/ws-trust/200512/}UT_Port`
** Use these properties to configure the Security Module of this bean
[source]
----
<entry key="ws-security.username" value="alice"/>
<entry key="ws-security.callback-handler" value="org.jboss.fuse.security.wstrust.ClientCallbackHandler"/>
<entry key="ws-security.encryption.properties" value="org/jboss/fuse/security/wstrust/clientKeystore.properties"/>
<entry key="ws-security.encryption.username" value="mystskey"/>
<entry key="ws-security.sts.token.username" value="myclientkey"/>
<entry key="ws-security.sts.token.properties" value="org/jboss/fuse/security/wstrust/clientKeystore.properties"/>
<entry key="ws-security.sts.token.usecert" value="true"/>
----

.Add a policy within the WSDL file
* Add a policy reference +AsymmetricSAML2Policy+ to the +<wsdl:binding name="Greeter_SOAPBinding" type="tns:Greeter">+ tag
* Create the + <wsp:Policy wsu:Id="AsymmetricSAML2Policy">+ policy
* Add a policy for the +<wsam:Addressing+ to include within the SOAP Header of the Request the MessageId, ReplyTo, Action and To xml tags
* Configure the +AsymmetricBinding+ to include a policy the +InitiatorToken+ where the +RequestSecurityTokenTemplate+ part of the +IssuedToken+
  will include a SAML2 Token Type (+http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0+) and a Public Key as Key Type (+http://docs.oasis-open.org/ws-sx/ws-trust/200512/PublicKey+)
* The issuer of the token is +<wsaw:Address>http://localhost:8080/SecurityTokenService/</wsaw:Address>+
* Include a TimeStamp and +Basic256+ as algorithm to sign/encrypt
* Add a +Wss11+ and +Trust13+ assertion

.New Test class
* Add a new Java Test class with the name +WSTrustTest+ and include an annotated method +testGreetMeClientWithSTS+
* Launch the server containing the Hello World Endpoint using the Spring XML file +org/jboss/fuse/security/wstrust/wssec-server.xml+
* Launch also the STS Server using the Spring XML file +org/jboss/fuse/security/wstrust/wssec-sts.xml+
* Use as Bus URL, the +wssec-client.xml+ file to configure the CXF Spring Bus
* Configure the +runAndValidate+ method to use the +hello_world.wsdl+ file packaged under the folder +src/test/resources/org/jboss/fuse/security/wstrust+

ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
