:scrollbar:
:data-uri:
:toc2:
:linkattrs:
:sourcedir: ../code/security-ws/src/test/java


== Web Services Trust Lab

.Goals
* Configure your local environment to develop and explore use cases
* Become more familiar with WS-Trust specification
* Design a web service project and secure it
* Send and receive messages using the CXF bus and XML configuration files

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with web service technology and SOAP messaging
* Understanding of PKI and message encryption and signatures
* Experience with Camel development using JBoss Fuse

.Use Case
In this lab, you explore one use case:

* <<usecase1>>

This use case is developed as a collection of Java JUnit test classes in the corresponding Maven module part of the skeleton project.

:numbered:


== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
| link:http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Crypto Unlimited^] | Java 8 | Required |
| link:http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[Java Cyptography Extension Unlimited Edition^] | JCE | Required |
|====

=== Install Lab Project

Download and install locally the latest release of the project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to explore the use cases, import the project into a new JBoss Developer Studio workspace.


=== Create Keys and Certificates

For this lab, the keys are generated for you. Outside the lab environment, use the `keytool -genkey` command to create the private and public keys and corresponding certificates for your users:

[source,text]
----
keytool -genkey -alias integration  -keyalg RSA  -keypass secUr1t8 -storepass secUr1t8 -keystore security-ws/src/test/resources/integrationstore.jks
----

* When prompted for the first and last names, enter `localhost`.
* Specify any values for the other prompts.
* Answer `yes` to confirm the value of the Common Name (CN).
* Expect the resulting Common Name to look similar to this: `CN=localhost, OU=integration, O=enablement, L=fuse, ST=Unknown, C=US`.


[[usecase1]]
== Use Security Token Service to Issue Token

In this use case, you use a security token service to issue a SAML v2.0 token. The SOAP client uses this token to send a SOAP request message to the web service, which validates the SAML token received. If the token request is authenticated, the service returns a valid response. If not, it returns an error response.

The project's skeleton code is similar to that of the previous use cases. In this lab, a security token service (the web service endpoint) must be exposed to the client in order to allow the client to request, renew, or cancel a security token. The client's WSDL file must include a WS-Security policy containing an initiator token.

To simplify your work, the STS Server (Spring XML configuration file, WSDL file, and STS keystore) is already configured in a similar way as the `Hello World` endpoint.

=== Create Spring XML Client File

. Create a new `wssec-client.xml` file within the `src/test/resources/org/jboss/fuse/wstrust/wssecuritypolicy` folder.

.  Create the `<jaxws:client/>` bean to use the `SoapPort` port binding as defined in the Hello World WSDL file.
. Add the required `ws-security` parameters:
* Crypto/Encrypt property configuration file(s) to use for the signature
* Username(s) of the key/certificate to be used to sign and encrypt
* Callback handler pointing to the `ClientCallbackHandler` Java class

. Create an `org.apache.cxf.ws.security.trust.STSClient` bean.
. Assign it to the WS-Security STS Client parameter.
. Configure this bean with these parameters:
* WSDL location: `http://localhost:8080/SecurityTokenService/UT?wsdl`
* Service name: `{http://docs.oasis-open.org/ws-sx/ws-trust/200512/}SecurityTokenService`
* Endpoint name: `{http://docs.oasis-open.org/ws-sx/ws-trust/200512/}UT_Port`

. Use these properties to configure the security module of this bean:
+
[source,xml]
----
<entry key="ws-security.username" value="alice"/>
<entry key="ws-security.callback-handler" value="org.jboss.fuse.security.wstrust.ClientCallbackHandler"/>
<entry key="ws-security.encryption.properties" value="org/jboss/fuse/security/wstrust/clientKeystore.properties"/>
<entry key="ws-security.encryption.username" value="mystskey"/>
<entry key="ws-security.sts.token.username" value="myclientkey"/>
<entry key="ws-security.sts.token.properties" value="org/jboss/fuse/security/wstrust/clientKeystore.properties"/>
<entry key="ws-security.sts.token.usecert" value="true"/>
----

=== Add Policy to WSDL File

. Add a `AsymmetricSAML2Policy` policy reference to the `<wsdl:binding name="Greeter_SOAPBinding" type="tns:Greeter">` tag.
. Create the `<wsp:Policy wsu:Id="AsymmetricSAML2Policy">` policy.
. In the SOAP request's `Header`, add a policy for `<wsam:Addressing>` to include the `MessageId`, `ReplyTo`, `Action` and `To` XML tags.
. Configure the `AsymmetricBinding` to include a `InitiatorToken` policy where the `RequestSecurityTokenTemplate` part of the `IssuedToken` includes a SAML v2.0 token type (`http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0`) and a public key as key type (`http://docs.oasis-open.org/ws-sx/ws-trust/200512/PublicKey`).
* The issuer of the token is `<wsaw:Address>http://localhost:8080/SecurityTokenService/</wsaw:Address>`.
. Include a `Timestamp` element and use the `Basic256` algorithm to sign and encrypt.
. Add the `Wss11` and `Trust13` assertion.

=== Add Test Class

. Add a new Java test class with the name `WSTrustTest` and include an annotated `testGreetMeClientWithSTS` method.
. Launch the server containing the Hello World endpoint using the `org/jboss/fuse/security/wstrust/wssec-server.xml` Spring XML file.
. Launch the STS server using the `org/jboss/fuse/security/wstrust/wssec-sts.xml` Spring XML file.
. Use the `wssec-client.xml` file as the bus URL to configure the CXF Spring bus.
. Configure the `runAndValidate` method to use the `hello_world.wsdl` file packaged under the `src/test/resources/org/jboss/fuse/security/wstrust` folder.

ifdef::showscript[]

:numbered!:

== Teacher Information

* Time estimated: 2d

* How to evaluate the student's solution:

** Verify that the JUnit tests pass successfully.
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, etc.)
** Review the solutions proposed by the student to resolve the different use cases.
** For each use case, verify that the SOAP request and response populated. They should be comparable to what you can find in the `output/ws-*` corresponding folder.

endif::showscript[]
