:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= WS Trust Lab

In this lab you resolve the following use cases:

<<usecase1>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about WS-Trust specification
* Design Web Service project and secure it
* Send and receive messages using the CXF Bus and XML Config Files

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with Web Service Technology & SOAP Messages
* PKI & encryption/decryption background
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project

[[usecase1]]
=== Use a Security Token Service to issue a token used by the Client

The goal of this use case is to use a Security Token Service to issue a SAML token v2.0 that the SOAP Client will use to send its SOAP Request message to the Web Service which will control the
SAML token received and will return a response if the issued request is authenticated.

The skeleton of the project is similar to what we done with the previous use cases. Nevertheless, there are some differences as a Security Token Service (= Web Service Endpoint) must be exposed to the client
in order to request/renew or cancel a Security Token, the WSDL file of the client must include a WS-Security Policy containing an Initiator Token

Remark : To simplify your work, the STS Server (Spring XML config file, WSDL file, STS Keystore) is already configured like the Hello World Endpoint (the the Spring Config file, Server Keystore)



.Spring XML Server file
* Create a new +server-signed.xml+ file within the folder +src/test/resources/org/jboss/fuse/security/wssecuritypolicy+
* Add the key +ws-security.signature.properties+ to the +<jaxws:properties/>+ bean to point to the properties file containing the keystore used to digest/sign the SOAP content
* Configure the +<jaxws:endpoint/>+ endpoint with a +<jaxws:features>+ bean to pass the location of the +signed-body-policy.xml+ file containing the Policy designed

.Spring XML Client File
* Create a new +client-signed.xml+ file within the folder +src/test/resources/org/jboss/fuse/security/wssecuritypolicy+
* Reuse the code created for the first use case and change the WSDL Port of the HTTPConduit & JAXS Bean to use the +GreeterSignedPort+
* Add the key +ws-security.signature.properties+ to the +<jaxws:properties/>+ bean to point to the properties file containing the keystore used to digest/sign the SOAP content
* Configure the +<jaxws:endpoint/>+ endpoint with a +<jaxws:features>+ bean to pass the location of the +signed-body-policy.xml+ file containing the Policy designed

.Sign Body and TimeStamp Policy
* Create the +signed-body-policy.xml+ file under the folder +src/test/resources/org/jboss/fuse/security/wssecuritypolicy+
* Develop the policy to sign the Body and the TimeStamp Header
* Generate the Username Token within the SOAP Header with a hashed password
* Include a +TimeStamp+ within the SOAP WSSE Header
* The algorithm to sign the parts of the messahe is +Basic128+
* Use +AsymmetricBinding+ and the +WssX509V3Token10+ to sign/decrypt the SOAP signed parts for the +InitiatorSignatureToken+ and the +RecipientSignatureToken+

.New Test class
* Add a new Java Test class with the name +WSSecurityPolicySignTest+ and include an annotated method +testSignature+
* Launch the server using the Spring XML file +org/jboss/fuse/security/wssecuritypolicy/server-signed.xml+
* Use as Bus URL, the +client-signed.xml+ file to configure the CXF Spring Bus
* Configure the +runAndValidate+ method to use the +hello_world.wsdl+ file packaged under the folder +src/test/resources/org/jboss/fuse/security/wssecuritypolicy+

ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
