:scrollbar:
:data-uri:
:toc2:
:linkattrs:
:sourcedir: ../code/security-ws/src/test/java

== Encrypt and Decrypt SOAP Body Message Lab

.Goals
* Configure your local environment to develop and explore use cases
* Become more experienced with the encryption/decryption process
* Encrypt and decrypt SOAP messages using Camel XMLSecurity DataFormat
* Design a web service project and secure it
* Use the Apache HTTPClient to post a SOAP message

.Prerequisites
* Experience with Java, Spring, and Maven
* Familiarity with web service technology and SOAP messaging
* Understanding of PKI and message encryption and signatures
* Experience with Camel development using JBoss Fuse

.Use Cases
In this lab, you explore three use cases:

* <<usecase1>>

* <<usecase2>>

* <<usecase3>>

Each use case is developed as a collection of Java JUnit test classes in the corresponding Maven module part of the skeleton project.

:numbered:

== Install Lab Assets

[cols="2,1,1",options="header"]
|====
| Software | Version | Notes
| link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java SE^] | 1.8 or higher | Required
| link:http://maven.apache.org[Apache Maven^] | 3.0.5 or higher | Required
| link:http://www.jboss.org/products/devstudio/overview/[Red Hat JBoss Developer Studio^] | 9.0.GA | Required
| link:https://devstudio.jboss.com/9.0/stable/updates/[JBoss Developer Studio Integration Stack^] | 9.0 | Required
| link:http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Crypto Unlimited^] | Java 8 | Required |
|====

=== Install Lab Project

Download and install locally the latest release of the project published on the {course_git_repo} GitHub repository. Because this project contains the skeleton code that you use to explore the use cases, import the project into a new JBoss Developer Studio workspace.

=== Create Keys and Certificates

For this lab, the keys are generated for you. Outside the lab environment, use the `keytool -genkey` command to create the private and public keys and corresponding certificates for your users:

[source,text]
----
keytool -genkey -alias integration  -keyalg RSA  -keypass secUr1t8 -storepass secUr1t8 -keystore security-ws/src/test/resources/integrationstore.jks
----

* When prompted for the first and last names, enter `localhost`.
* Specify any values for the other prompts.
* Answer `yes` to confirm the value of the Common Name (CN).
* Expect the resulting Common Name to look similar to this: `CN=localhost, OU=integration, O=enablement, L=fuse, ST=Unknown, C=US`.


[[usecase1]]
== Encrypt SOAP Message

In this use case, you design an Apache Camel route to encrypt the contents of a SOAP message that you send to a `direct` endpoint exposed by the route.

This project uses Apache Camel and the Apache Camel XMLSecurity DataFormat.

You create a JUnit test class extending the `CamelSpringTestSupport` Java class to load the `EncryptDecryptPayloadTest-context.xml` Spring XML beans file packaged under the `org/jboss/fuse/security/encryption` folder. This XML file contains the declaration of the Apache Camel route and XMLSecurity DataFormat required to marshal the payload.

=== Encrypt Route Direct

. Design a route using the `direct` component with the `direct://encrypt` URI.
. Marshall the contents of the `Body` element using the `encryptXML` reference of the bean.
. Send the result to the `mock:encrypted` endpoint.
. Configure a Spring bean using as the `org.apache.camel.model.dataformat.XMLSecurityDataFormat` Java class and set the ID to `encryptXML`.
. Set the fields of this bean using these key/value pairs:
+
[source,xml]
----
<property name="secureTagContents" value="true"/>
<property name="xmlCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
<property name="keyCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#rsa-1_5"/>
<property name="recipientKeyAlias" value="recipient"/>
<property name="keyOrTrustStoreParametersId" value="trustStoreParams"/>
<property name="namespaces">TODO</property>
----

=== Congigure Camel Key Store Parameters

. Configure a Camel `keyStore` with the `keyStoreParams` ID pointing to the `recipient.ks` keystore file.
. Configure a Camel `keyStore` with the `trustStoreParams` ID pointing to the `sender.ks` keystore file.

=== Develop Test Class

. Add a test class named `EncryptDecryptPayloadTest` under the `src/test/java/org/jboss/fuse/security/encryption` folder.
* Use the `CamelSpringTestSupport` Camel class as the base class.
. Override the method to use your `src/test/resources/org/jboss/fuse/security/encryption/EncryptDecryptPayloadTest-context.xml` Spring Camel beans XML file.
. Add a `testXMLPayloadEncryption` JUnit method.
. Using a Camel `ProducerTemplate`, send a message to the `direct://encrypt` endpoint using the `org.jboss.fuse.security.encryption.Helper.XML_REQUEST` string as the message body.
+
[NOTE]
In the `Helper` class, you can create a `void sendText(final String URI, final Object msg, CamelContext context)` method  that you can reuse from other use cases.

. Verify that the `mock:encrypted` mock endpoint receives a response with an encrypted body.
* Use an `Assert.assertTrue()` expression for this.
* Use the `public boolean hasEncryptedData(Document doc)` method of the `Helper` class to check whether your body is encrypted.

[[usecase2]]
== Decrypt SOAP Message

For this use case, you expand on the previous use case to design an Apache Camel route to decrypt the contents of an encrypted SOAP message. This project uses Apache Camel and Apache Camel XMLSecurity DataFormat.

=== Decrypt Route Direct

. Open the `EncryptDecryptPayloadTest-context.xml` file and add an Apache Camel route.
. Design a route using the `direct` component with the `direct://decrypt` URI.
. Unmarshal the contents of the `Body` element using the `decryptXML` reference of the bean.
. Send the result to the `mock:decrypted` endpoint.
. Configure a Spring bean using `org.apache.camel.model.dataformat.XMLSecurityDataFormat` as the Java class and set the ID to `decryptXML`.
. Set the fields of this bean using these key/value pairs:
+
[source,xml]
----
<property name="secureTag" value=""/>
<property name="secureTagContents" value="true"/>
<property name="xmlCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
<property name="keyCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#rsa-1_5"/>
<property name="recipientKeyAlias" value="recipient"/>
<property name="keyOrTrustStoreParametersId" value="keyStoreParams"/>
<property name="namespaces">TODO</property>
----

=== Add Test Method

. Open the `EncryptDecryptPayloadTest` class and add a `testXMLPayloadDecryption` JUnit test method.
. Send the same message used for the first use case to the `direct://encrypt` endpoint.
. Use the response returned as input to call the `direct://decrypt` endpoint.
. Use the `mock:decrypted` endpoint to assert (with `Assert.assertFalse`) that the  message received is not encrypted.
. Use the response received by the `mock:decrypted` endpoint to verify that the response received is equivalent to the message sent.

* Use `Diff xmlDiff = XMLUnit.compareXML(Original, Result)` method to compare the two `org.w3c.dom.Document` objects.

* Add an `Assert.assertTrue()` assert method  to check that `xmlDiff.identical()` xmlDiff is identical.

[[usecase3]]
== Reply to SOAP Message with Encrypted Response

In this use case, you design a third Apache Camel route that exposes a Camel CXF endpoint. This endpoint consumes a SOAP request message, and replies with an encrypted SOAP response. You use an Apache HTTPClient to send a SOAP request message and wait for a SOAP response message containing an encrypted body. The Camel route consumes the SOAP message, extracts the contents of the SOAP `Body` element using xPath, calls a bean to generate the response, and marshals the result as an encrypted message.

This project uses Apache Camel, Apache Camel XMLSecurity DataFormat, and Apache HTTPClient.

=== Encrypt Route CXF Endpoint

. Open the `EncryptDecryptPayloadTest-context.xml` file and add an Apache Camel route.
. Define the `<cxf:cxfEndpoint id="cheeseServiceBean">` bean using these parameters:
* `address`: `http://localhost:9001/camel/CheeseService`
* `wsdlURL`: `src/test/resources/org/jboss/fuse/security/encryption/CheeseProcess.wsdl`
* `serviceClass`: `org.jboss.fuse.security.encryption.CheeseProcess`
* `DataFormat`: `MESSAGE`
. Add a Camel route exposing the CXF bean endpoint.
. Set a header with the `arg` name and an xPath expression to extract the text of the SOAP message from the body.
* Use the `/soap:Envelope/soap:Body/ns4:processCheese/arg0/text()` xPath expression.
. Verify that the namespaces to be used by xPath are registered in the `CamelContext`.
. Set the `Body` of the response with the value returned by the xPath expression.
. Call the `org.jboss.fuse.security.encryption.CheeseProcessImpl` bean and the  `processCheese` method  to get a `org.jboss.fuse.security.encryption.Country` object response.
. Marshall the Java `Country` object to an XML stream using JAXB.
. Marshall the result using Camel XMLSecurity DataFormat.
* A new Spring bean is required for this marshalling.
* Create it using the `encryptSOAPBody` ID.
. Pass these parameters:
+
[source,xml]
----
<bean id="encryptSOAPBody" class="org.apache.camel.model.dataformat.XMLSecurityDataFormat">
<property name="secureTag" value=""/>
<property name="secureTagContents" value="true"/>
<property name="xmlCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
<property name="keyCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#rsa-1_5"/>
<property name="recipientKeyAlias" value="recipient"/>
<property name="keyOrTrustStoreParametersId" value="trustStoreParams"/>
<property name="namespaces">
----

. Call the `populateSoapResponse` method of the `CheeseProcessImpl` bean service to wrap the body with a SOAP header message.
. Return this message to the Camel CXF endpoint.

=== Add Method to Test Web Service

. Open the `EncryptDecryptPayloadTest` class and add a `testXMLPayloadDecryption` JUnit test method.
. Add a `testEncryptedSOAPBody` JUnit method.
. Use the Apache HTTPClient project to post an HTTP request using the `org.apache.commons.httpclient.methods.PostMethod(String URL)` method  where the URL corresponds to the `http://localhost:9001/camel/CheeseService` web service endpoint to call.
. Create an `org.apache.commons.httpclient.methods.StringRequestEntity(String content, String contentType, String charset)` to send the `Helper.XML_REQUEST` XML String.
. Add a `SOAPAction` with `setRequestHeader()` to the post object.
. Create a `HttpClient` object and execute the post.
. Assert that you get a response with the HTTP response code of `200`.
. Extract from the SOAP message the SOAP `Body` element as a string.
. Use xPath to navigate to the SOAP `Body` XML element and extract the content.
* Call the `helper.decryptXMLPayload(String xmlBodyEncrypted, CamelContext);` helper method to decrypt its content and verify it.

ifdef::showscript[]

:numbered!:

== Teacher Information

* Time estimated: 2d

* How to evaluate the student's solution:

** Verify that the JUnit Tests pass successfully.
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, etc.)
** Review the solutions proposed by the student to resolve the different use cases.
** For each use case, verify that the SOAP request and response populated. They should be comparable to what you can find in the `output/ws-*` corresponding folder.
