:noaudio:
:sourcedir: ../code/security-ws/src/test/java
:toc2:

= WS Security Lab

In this lab you resolve the following use cases:

<<usecase1>>

.Goals
* Configure your local environment to develop and resolve use cases
* Become more experimented about Encryption/Decryption process
* Encrypt and decrypt SOAP Message using Camel XML Security Data Format
* Design Web Service project and secure it
* Use the Apache HTTP Client to post SOAP Message

.Prerequisites
* Experience with Java, Spring & Apache Maven
* Expertise with Web Service Technology & SOAP Messages
* Design Apache Camel routes and marshall/unmarshall data payload
* PKI & encryption/decryption background
* Complete Red Hat OPEN course: Camel Development with Red Hat JBoss Fuse

:numbered:
== Install Lab assets

|===
| Software | Version & URL | Notes |

| Java SE | http://www.oracle.com/technetwork/java/javase/downloads/index.html[1.8 or higher] | Required |
| Apache Maven | http://maven.apache.org[3.0.5 or higher] | Required |
| JBoss Developer Studio | http://www.jboss.org/products/devstudio/overview/[9.0.GA] | Required |
| Integration Stack | https://devstudio.jboss.com/9.0/stable/updates/[9.0] | Required |
| SoapUI | http://sourceforge.net/projects/soapui/files/[latest version] | Optional |
| Java Crypto Unlimited | http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java 8] | Required |
|===

=== Install the lab project

Download the latest release of the project published on the following GitHub repository: {course_git_repo} and install it locally. As this project contains the skeleton of the code
that you will use to resolve the use cases, we suggest that you next import it in a new Workspace of JBoss Developer Studio.

=== Keys and certificates

Follow these instructions in order to create the Private/Public keys of the users to be used and their corresponding certificates

[source]
----
keytool -genkey -alias integration  -keyalg RSA  -keypass secUr1t8 -storepass secUr1t8 -keystore security/src/test/resources/integrationstore.jks
----

Add `localhost` as name for the first and last name field. You can define the value for the other fields as you want.
Here is an example `CN=localhost, OU=integration, O=enablement, L=fuse, ST=Unknown, C=US`

== Use case exercise

The different use cases should be developed as a collection of Java JUnit Test class within the corresponding Maven module part of the skeleton project

[[usecase1]]
=== Generate SOAP Header with WSSE : username, timestamp & wrong password

The goal of this use case is to design 3 Apache Camel Routes; one to encrypt the content of a SOAP Body message, a second to decrypt the content and a third to expose a Camel CXF Endpoint that a HTTP Client will use to send
a SOAP Message and waiting as response a SOAP Message containing the encrypted body.

This project will use the following technologies : Apache Camel, Apache Camel XMLSecurity Dataformat and Apache HTTP Client.

You will create a Junit Test class extending the +CamelSpringTestSupport+ java to load the Spring XML Beans file +EncryptDecryptPayloadTest-context.xml+ packaged under the folder +org/jboss/fuse/security/encryption+ containing the declaration of the
3 Apache Camel Routes & XMLSecurity Data Format required to marshall/unmarshall the paylaods.

.Route Direct - Encrypt
* Design a route using the Direct component with the URI +direct://encrypt+
* Marshall the content of the body using the reference of the Bean +encryptXML+
* Send the result to the +mock:encrypted+ endpoint
* Configure a Spring Bean using as Java class +org.apache.camel.model.dataformat.XMLSecurityDataFormat+ and set the id with the word +encryptXML+
* Set the fields of this bean using this key/value
[source]
----
<property name="secureTagContents" value="true"/>
<property name="xmlCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
<property name="keyCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#rsa-1_5"/>
<property name="recipientKeyAlias" value="recipient"/>
<property name="keyOrTrustStoreParametersId" value="trustStoreParams"/>
<property name="namespaces">TODO</property>
----

.Route Direct - Decrypt
* Design a route using the Direct component with this the +direct://decrypt+
* UnMarshall the content of the body using the reference of the Bean +decryptXML+
* Send the result to the +mock:decrypted+ endpoint
* Configure a Spring Bean using as Java class +org.apache.camel.model.dataformat.XMLSecurityDataFormat+ and set the id with the word +decryptXML+
* Set the fields of this bean using this key/value
[source]
----
<property name="secureTag" value=""/>
<property name="secureTagContents" value="true"/>
<property name="xmlCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
<property name="keyCipherAlgorithm" value="http://www.w3.org/2001/04/xmlenc#rsa-1_5"/>
<property name="recipientKeyAlias" value="recipient"/>
<property name="keyOrTrustStoreParametersId" value="keyStoreParams"/>
<property name="namespaces">TODO</property
----

.Camel Key Store Parameters
* Configure a Camel Key Store with the id +keyStoreParams+ to point to the Keystore file of the +recipient.ks+
* Configure a Camel Key Store with the id +trustStoreParams+ to point to the Keystore file of the +sender.ks+

.Design the Test Class
* Add a new test class with the name +EncryptDecryptPayloadTest+ under the folder +src/test/java/org/jboss/fuse/security/encryption+
* Extends the Camel class +CamelSpringTestSupport+
* Override the method to use your Spring Camel Beans XML file +src/test/resources/org/jboss/fuse/security/encryption/EncryptDecryptPayloadTest-context.xml+
* Add the Junit method: +testXMLPayloadEncryption+
* Using a Camel ProducerTemplate, send a Message to the +direct://encrypt+ using as Body Message the String defined here +org.jboss.fuse.security.encryption.Helper.XML_REQUEST+

NOTE: You can create within the Helper class a method +void sendText(final String URI, final Object msg, CamelContext context)+ that you will reuse from other use cases.

* Verify that the Mock Endpoint +mock:encrypted+ will receive a Body from the Exchange which is encrypted using an Assert.assertTrue() expression

NOTE: Use the method +public boolean hasEncryptedData(Document doc)+ of the helper class to check if your Body is encrypted or not


ifdef::showscript[]

:numbered!:
= Teacher info

* Time estimated : 2d

* How to evaluate the solution of the student :

** Check if the Junit Tests are passing successfully
** Review the code submitted by the student, Java classes and frameworks technology used (Spring, Blueprint, CDI, ...)
** Review the solutions proposed by the student to resolve the different use cases
** For each use case, verify the SOAP Request and response populated. They should be comparable to what you can find within the +output/ws-*+ corresponding folder

endif::showscript[]
