:scrollbar:
:data-uri:
:linkattrs:


== WS-SecurityPolicy

* Externalized in XML file and passed as parameter to 
`<jaxws:endpoint/>` using `<feature/>`:
+
[source,xml]
----
<jaxws:features>
    <p:policies>
        <wsp:PolicyReference xmlns:wsp="http://www.w3.org/ns/ws-policy" URI="classpath:/to/my/policy.xml"/>
    </p:policies>
</jaxws:features>
----

.References
* link:http://docs.oasis-open.org/ws-sx/ws-securitypolicy/v1.3/errata01/ws-securitypolicy-1.3-errata01.html["WS-SecurityPolicy 1.3 Errata 01^"]
* link:http://cxf.apache.org/docs/ws-securitypolicy.html["WS-SecurityPolicy^"]

ifdef::showscript[]

Transcript:

Another approach that Apache CXF supports is to define the policies in a separate XML file. The reference to the file, which includes the filename and classpath, is passed to a `<jaxws:endpoint/>` as a CXF `policies` feature, as shown here.

The advantage of this approach is that you can maintain and manage the WSDL contract file separately from the security policies within your project's team.

The `policies` feature enables and configures the CXF policy framework. It can have any number of `Policy` or `PolicyReference` child elements.

You can assign such policies globally by attaching them to the CXF bus. They are then applied to all client and server endpoints created on that bus.

endif::showscript[]
