:scrollbar:
:data-uri:
:linkattrs:


== WS-Trust

.Overview

* Security provider hands out tokens
* Client contacts security tokens service (STS) to get/renew a token based on SAML v2 rules
* Token is included within SOAP header client request and sent to web service
* Web service asserts the token and the SAML rules (v1, v2)

.Reference
* link:http://cxf.apache.org/docs/ws-trust.html["WS-Trust^"]

ifdef::showscript[]

Transcript:

The WS-Trust specification is an extension of the WS-SecurityPolicy specification to enable applications to construct trusted SOAP message exchanges.

According to the specification, WS-Trust is based on a process in which a web service can require an incoming message to prove a set of claims--for example, name, key, permission, and capability.

If a message arrives without the required proof of claims, the service is supposed to ignore or reject the message. A service can indicate the required claims and related information in its policy as described by WS-SecurityPolicy. These security claims are usually described using v1 or v2 SAML assertion rules.

This trust is represented through the exchange and brokering of security tokens. The tokens are issued by a security tokens service, or STS, which is a web service endpoint that can issue, renew, and validate security tokens. The STS server acts as a central security proxy server, globally managing the certificates and keys of the application's client.

The client contacts the STS to get or renew a token based on SAML v2 rules. The issued token is then used by the web service client to issue the SOAP header request to the target service. The service determines whether the token is valid, the user is authenticated, and the client is asserted or authorized to access the service.

endif::showscript[]
