:scrollbar:
:data-uri:
:linkattrs:


== Payload Encryption/Decryption

* Camel XML security component supports signing and verifying SOAP body message for:
** Enveloped XML signature
** Enveloping XML signature
** Detached XML signature

* Camel route example:
+
[source,xml]
----
<from uri="direct:enveloping" />
  <to uri="xmlsecurity:sign://enveloping?keyAccessor=#accessor" />
  <to uri="xmlsecurity:verify://enveloping?keySelector=#selector" />
<to uri="mock:result" />
----

* XML example:
+
[source,xml]
----
<[parent element]>
   ... <!-- Signature element is added as last child of the parent element-->
   <Signature Id="generated_unique_signature_id">
       <SignedInfo>
             <Reference URI="">
                   <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                   (<Transform>)* <!-- By default "http://www.w3.org/2006/12/xml-c14n11" is added to the transforms -->
                   <DigestMethod>
                   <DigestValue>
             </Reference>
             (<Reference URI="#[keyinfo_Id]">
                   <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                   <DigestMethod>
                   <DigestValue>
             </Reference>)?
             <!-- further references possible, see option &#39;properties&#39; below -->
      </SignedInfo>
      <SignatureValue>
      (<KeyInfo Id="[keyinfo_id]">)?
      <!-- Object elements possible, see option &#39;properties&#39; below -->
  </Signature>
</[parent element]>
----

.References
* link:http://docs.oracle.com/javase/6/docs/technotes/guides/security/xmldsig/overview.html["JSR 105^"]
* link:https://www.w3.org/TR/xmldsig-core1/["XML Signature Syntax and Processing Version 1.1^"]
* link:http://camel.apache.org/xml-security-component.html[XML Security component^]


ifdef::showscript[]

Transcript:

When you need to verify the signature of an XML message or digest its content, you use the Apache Camel XML security component. This component supports two options, sign and verify, and is configured using many parameters.

The XML signature option can verify enveloped, enveloping, and detached XML signatures. An enveloped XML signature means that the XML signature is wrapped by the signed XML document--in other words, the XML signature element is a child element of a parent element that belongs to the signed XML document. An enveloping XML signature means that the XML signature contains the signed content. All other cases are called detached XML signatures.

For the signing process, a private key is necessary. You specify a key accessor bean that provides this private key. For validation, the corresponding public key is necessary. You specify a key selector bean that provides this public key.

The key accessor bean must implement the `KeyAccessor` interface. The `org.apache.camel.component.xmlsecurity.api` package contains the default implementation class `DefaultKeyAccessor`, which reads the private key from a Java keystore.

The key selector bean must implement the `javax.xml.crypto.KeySelector` interface. The `org.apache.camel.component.xmlsecurity.api` package contains the default implementation class `DefaultKeySelector`, which reads the public key from a keystore.

Here you see an example of creating the keys necessary for signing and validating.

endif::showscript[]
