:noaudio:

[#xmlsecurity-sign-verify]
== Encrypt/Decrypt Payload

* Camel XML Security Component supports to sign & verify SOAP Body message for
** Enveloped XML Signature
** Enveloping XML Signature
** Detached XML Signature

.Camel Route Example
[source,xml]
----
<from uri="direct:enveloping" />
  <to uri="xmlsecurity:sign://enveloping?keyAccessor=#accessor" />
  <to uri="xmlsecurity:verify://enveloping?keySelector=#selector" />
<to uri="mock:result" />
----

.XML Example
[source]
----
<[parent element]>
   ... <!-- Signature element is added as last child of the parent element-->
   <Signature Id="generated_unique_signature_id">
       <SignedInfo>
             <Reference URI="">
                   <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                   (<Transform>)* <!-- By default "http://www.w3.org/2006/12/xml-c14n11" is added to the transforms -->
                   <DigestMethod>
                   <DigestValue>
             </Reference>
             (<Reference URI="#[keyinfo_Id]">
                   <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                   <DigestMethod>
                   <DigestValue>
             </Reference>)?
             <!-- further references possible, see option &#39;properties&#39; below -->
      </SignedInfo>
      <SignatureValue>
      (<KeyInfo Id="[keyinfo_id]">)?
      <!-- Object elements possible, see option &#39;properties&#39; below -->
  </Signature>
</[parent element]>
----

.References
* http://docs.oracle.com/javase/6/docs/technotes/guides/security/xmldsig/overview.html[JSR 105]
* https://www.w3.org/TR/xmldsig-core1/[XML Signature Syntax]
* http://camel.apache.org/xml-security-component.html[Camel XML Security - sign/verify]

ifdef::showscript[]
[.notes]
****

== Encrypt Payload

When we have to verify the signature of a XML message signed or to digest its content, we will use the Apache Camel XML Security Component. This component supports 2 options; sign or verify and is configured through many parameters.

XML Signature differs between enveloped, enveloping, and detached XML signature. In the enveloped XML signature case, the XML Signature is wrapped by the signed XML Document;
which means that the XML signature element is a child element of a parent element, which belongs to the signed XML Document.
In the enveloping XML signature case, the XML Signature contains the signed content. All other cases are called detached XML signatures.

For the signing process, a private key is necessary. You specify a key accessor bean which provides this private key. For the validation, the corresponding public key is necessary; you specify a key selector bean which provides this public key.
The key accessor bean must implement the KeyAccessor interface. The package org.apache.camel.component.xmlsecurity.api contains the default implementation class DefaultKeyAccessor which reads the private key from a Java keystore.
The key selector bean must implement the javax.xml.crypto.KeySelector interface. The package org.apache.camel.component.xmlsecurity.api contains the default implementation class DefaultKeySelector which reads the public key from a keystore.

****
endif::showscript[]