:scrollbar:
:data-uri:
:linkattrs:


== Transport Layer Security

* WS-SecurityPolicy can provide:
** Transport-level security for message using `TransportBinding` section
** SOAP message or parts of it (body, headers, attachment)

* Structure of `TransportBinding` section:
+
[source,xml]
----
<sp:TransportBinding xmlns:sp="..." ... >
  <wsp:Policy xmlns:wsp="...">
    <sp:TransportToken ... >
      <wsp:Policy> ... </wsp:Policy>
      ...
    </sp:TransportToken>
    <sp:AlgorithmSuite ... > ... </sp:AlgorithmSuite>
    <sp:Layout ... > ... </sp:Layout>
    <sp:IncludeTimestamp ... />
      ...
  </wsp:Policy>
  ...
</sp:TransportBinding>
----

.References
* link:http://docs.oasis-open.org/ws-sx/ws-securitypolicy/v1.3/ws-securitypolicy.html["WS-SecurityPolicy 1.3^"]
* link:http://cxf.apache.org/docs/ws-securitypolicy.html["WS-SecurityPolicy^"]


ifdef::showscript[]

Transcript:

In addition to providing security for the SOAP message or its parts--body, headers, attachments--WS-SecurityPolicy can provide transport-level security for a message.

Transport-layer message protection refers to message protection, including encryption and signing, that is provided by the transport layer. For example, HTTPS provides encryption and message signing features using SSL/TLS.

In fact, WS-SecurityPolicy does not add much to the HTTPS feature set, because HTTPS is already fully configurable using Spring XML configuration.

If you use WS-SecurityPolicy and transport binding to configure the HTTPS transport, you must also configure HTTPS security appropriately in the Spring configuration using `<sec:keyManagers/>`, `<sec:trustManagers/>`, and so on.

To configure the HTTPS transport using WS-SecurityPolicy and TransportBinding, the `TransportBinding` section contains a policy with the XML tags shown here:

* The `TransportToken` defines a particular type of security token to be used--for example, `X.509`. It also indicates how the transport is secured--for example, `HTTPS`.
* The `AlgorithmSuite` element specifies the suite of cryptographic algorithms to use for signing and encryption--for example, `base64`.
* The `Layout` specifies whether to impose any conditions on the order in which security headers are added to the SOAP message. Options include `Lax`, `Strict`, and so on.
* `IncludeTimestamp` adds the `Timestamp` to the SOAP header.

endif::showscript[]
