:noaudio:

[#ws-security-policy]
== WS Security Policy

* Goal : apply policies that modify the semantics of connections and communications at runtime in a Web services application
* Policy +<wsp:Policy>+ can be assigned to the Port section of the WSDL file
+
[source,xml]
----
<wsdl:service name="PingService10">
    <wsdl:port name="UserNameOverTransport_IPingService" binding="BindingName">
      <wsp:Policy>
        <!-- Policy expression comes here! -->
      </wsp:Policy>
      <soap:address location="SOAPAddress"/>
    </wsdl:port>
----

* Or as a reference
+
[source,xml]
----
<wsdl:service name="PingService10">
    <wsdl:port name="UserNameOverTransport_IPingService" binding="BindingName">
 <wsp:PolicyReference URI="#PolicyID"/>
      <soap:address location="SOAPAddress"/>
    </wsdl:port>
  </wsdl:service>
  ...
  <wsp:Policy wsu:Id="PolicyID">
    <!-- Policy expression comes here ... -->
  </wsp:Policy>
----

.References
* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_CXF_Security_Guide/WsPolicy.html#WsPolicy-Intro[Fuse CXF Security doc]

ifdef::showscript[]
[.notes]
****

== WS Security Policy

The WS Security Policy like the WS Security specification extends the SOAP Specification but is based on Policies.
The Web Services policies have been defined within the WS-Policy specification and define a framework for allowing web services to express their constraints and requirements.
Such constraints and requirements are expressed as security policy assertions for the WS-SecurityPolicy specification with respect to security features provided in SOAP Message Security [WSS10, WSS11].

As such policies can't be defined using Java Annotations, by consequence, it is only possible to use the WS-Security Policy using the approach WSDL to Java.

The Policy Assertions are defined within the namespace +http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702+ which is associated by convention to the prefix wsp and will describe how messages are to be secured.

In general, a +<wsp:Policy/> element is composed of multiple different policy settings (where individual policy settings are specified as policy assertions). Hence, the policy defined by a wsp:Policy element is really a composite object.
The content of the wsp:Policy element is called a policy expression, where the policy expression consists of various logical combinations of the basic policy assertions. By tailoring the syntax of the policy expression, you can determine what
combinations of policy assertions must be satisfied at runtime in order to satisfy the policy overall.

A policy is built up using policy assertions, which can additionally be qualified using the wsp:Optional attribute, and various nested combinations of the wsp:All and wsp:ExactlyOne elements.
The net effect of composing these elements is to produce a range of acceptable policy alternatives.

There are 2 ways to configure the WS Policies. You can define them within the WSDL File within the +<wsdl:port/>+ section or refer it within the Port Binding section using a +<PolicyReference/>+ as you can see within the 2 snippets code
of this slide. A policy can be assigned globally for the binding of a Service but you can also define a policy that you will assign to the Input or Output Body message. Typically, such a policy will be used to specify that the body must be signed and/or encrypted like also the Header section.

WARNING: The WS-SecurityPolicy fragment does not include "everything" that is required for a runtime to be able to able to create the messages. It does not describe things such as locations of key stores, user names and passwords, etc...
Those need to be configured in at runtime to augment the WS-SecurityPolicy fragment using what has been presented previously.

****
endif::showscript[]