:scrollbar:
:data-uri:
:noaudio:

== WS-SecurityPolicy - SOAP Message

* SOAP message-level security offers more granularity
* Support for symmetric (Kerberos token) and asymmetric (public key) key protocols
* Can sign and/or encrypt specific parts of message (body, headers)

* Asymmetric example:
+
[source,xml]
----
<sp:AsymmetricBinding xmlns:sp="..." ... >
  <wsp:Policy xmlns:wsp="...">
   <sp:InitiatorToken>
     <wsp:Policy> ... </wsp:Policy>
   </sp:InitiatorToken>
   <sp:RecipientToken>
     <wsp:Policy> ... </wsp:Policy>
   </sp:RecipientToken>
   <sp:AlgorithmSuite ... > ... </sp:AlgorithmSuite>
   <sp:Layout ... > ... </sp:Layout>
   <sp:IncludeTimestamp ... />
   <sp:EncryptSignature ... />
   <sp:OnlySignEntireHeadersAndBody ... />
   ...
  </wsp:Policy>
  <sp:SignedParts xmlns:sp="..." ... >
    <sp:Body />
    <sp:Header Name="xs:NCName"? Namespace="xs:anyURI" ... />
    <sp:Attachments />
    ...
  </sp:SignedParts>
</sp:AsymmetricBinding>
----

ifdef::showscript[]

Transcript:

Applying message protection at the SOAP encoding layer, instead of at the transport layer, provides a more flexible range of protection policies.

In particular, because the SOAP layer is aware of the message structure, you can apply protection at a finer level of granularity--for example, by encrypting and signing only those headers that actually require protection.

To configure the protection, use a security binding. This can be either `AsymmetricBinding` for public key cryptography or `SymmetricBinding` when using, for example, private cryptography with a Kerberos token.

In an asymmetric-binding scenario, you specify the keys used for signing and encrypting. An asymmetric binding usually contains two elements, `InitiatorToken` and `RecipientToken`.

Based on the specification, each of these elements should contain tokens for signing and encrypting operations by the sender (initiator) and recipient, respectively. You generally define these as X509 tokens.

In addition to those two elements, you can specify other properties such as `AlgorithmicSuite` and `IncludeTimestamp` in the asymmetric binding element, similar to the way you define other security binding assertions.

To sign or encrypt specific parts of the SOAP message, use the `SignedPart` or `EncryptedPart` XML tag. Include the correct child elements to define whether the body, a header with its name, or an attachment is to be signed or encrypted.

endif::showscript[]
