:scrollbar:
:data-uri:
:linkattrs:
:noaudio:

== Endpoint Security

.TLS with Mutual Authentication
* Configure server with `<sec:ClientAuthentication/>`
* TrustManager is required by both client and server
* KeyManager is required only on client side for mutual authentication
+
[source,xml]
----
<http:destination id="{Namespace}PortName.http-destination">
  <http:tlsServerParameters secureSocketProtocol="TLSv1">
    ...
    <sec:clientAuthentication want="true" required="true"/>
  </http:tlsServerParameters>
</http:destination>
----

.Reference
* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_CXF_Security_Guide/ConfigTLS.html#i305901[Mutual Authentication^]

ifdef::showscript[]

Transcript:

When you need mutual TLS authentication between the client and the server, and the server expects to get the client's certificate and public key to sign, encrypt, decrypt, or digest the content of a SOAP message, use either the `org.apache.cxf.configuration.security.ClientAuthentication` Java class or its corresponding XML tag, `<sec:clientAuthentication/>`.

Use the appropriate Boolean values to specify if mutual authentication is required or optional.

The client authentication feature does not indicate that the client must provide a username and password. Instead, it indicates that the client must provide its certificate containing its public key, which the server verifies using TrustManager.

For mutual authentication, you must configure both the TLS server parameters and the TLS client parameters with a TrustManager. However, a KeyManager is required only on the client side.

endif::showscript[]
