:scrollbar:
:data-uri:
:linkattrs:


== WS-Security

* WSS4j can be configured using Java API or Spring XML beans:

** Java API:
+
[source,java]
----
import org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
...

Endpoint cxfEndpoint = jaxWsEndpoint.getServer().getEndpoint();

Map<String,Object> inProps = new HashMap<String,Object>();
... // how to configure the properties is outlined below;

WSS4JInInterceptor wssIn = new WSS4JInInterceptor(inProps);
cxfEndpoint.getInInterceptors().add(wssIn);

Map<String,Object> outProps = new HashMap<String,Object>();
... // how to configure the properties is outlined below;

WSS4JOutInterceptor wssOut = new WSS4JOutInterceptor(outProps);
cxfEndpoint.getOutInterceptors().add(wssOut);
----



** Spring XML beans:
+
[source,xml]
----
<jaxws:endpoint id="myService"
   implementor="com.acme.MyServiceImpl"
   address="http://localhost:9001/MyService">

   <bean id="myPasswordCallback"
      class="com.mycompany.webservice.ServerPasswordCallback"/>

   <jaxws:inInterceptors>
      <bean class="org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor">
         <constructor-arg>
            <map>
               <entry key="action" value="UsernameToken"/>
               <entry key="passwordType" value="PasswordDigest"/>
               <entry key="signaturePropFile" value="..."/>
               <entry key="passwordCallbackRef">
                  <ref bean="myPasswordCallback"/>
               </entry>
               ...
            </map>
         </constructor-arg>
      </bean>
   </jaxws:inInterceptors>
----


.Reference

* link:http://cxf.apache.org/docs/interceptors.html[Interceptors and Phases^]

ifdef::showscript[]


Transcript:

To configure the WSS4J interceptors, you can use the `org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor` and `org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor` Java classes, as shown here.

You use the CXF endpoint object to get the list of the in or out interceptors, and then add a new interceptor. The CXF framework handles these interceptors during the `PRE_PROTOCOL` phase. Alternatively, you can instantiate the WSS4J interceptors using a `<jaxws:Interceptors>` or `<jaxws:outInterceptors/>` list of beans, as shown in the second example.

You configure the WSS4J interceptor with a map that you pass as a constructor argument. The key and entries, such as `action`, `signaturePropFile`, and so on, map to the text strings in WSS4J's `WSHandlerConstants` and `WSConstants` classes for the corresponding `WSHandlerConstants.XXXXX` and `WSConstants.XXXX` constants.

When you want to set up some actions, create the `Action` key with the values `UsernameToken` and `Timestamp`. CXF then generates a `UsernameToken` with a `Timestamp` within the WS-Security SOAP header section.

To see a list of all the actions available, look in the `org.apache.wss4j.dom.handler.WSHandlerConstants` Java class.

To specify the class to be used to control the password using a `CallBack` mechanism, add the `passwordCallbackClass` key.

To specify the file to be used to sign/digest or encrypt/decrypt the elements of the SOAP messages, use the `signaturePropFile` and `encryptPropFile` keys, respectively. These keys point to the location of the properties files that WSS4J uses to configure the crypto provider.

The `org.apache.ws.security.crypto.provider` key and its value, `org.apache.ws.security.components.crypto.Merlin`, tell WSS4J which class to use to instantiate the Java crypto provider. By default, the provider is `Merlin`.

Similar to TLS client and server parameters, you also define in these properties files the location of the keystore, the password to be used, and so on.





endif::showscript[]
