:noaudio:

[#ws-security-trust-config]
== WS Trust Config

* STS : Designed as a Secured WS & WS Trust WSDL
* WSP - Web Service Provider : Web Service & WS Trust Policies
* WSC - Web Service Client : Web Service acting as a STS Client & WS Trust Policies
+
[source,xml]
----
...
<sp:AsymmetricBinding>
  <wsp:Policy>
    <!--
          The sp:InitiatorToken element specifies the elements required in
          generating the initiator request to the ws-provider's service.
    -->
    <sp:InitiatorToken>
      <wsp:Policy>
        <sp:IssuedToken
                  sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
          <sp:RequestSecurityTokenTemplate>
            <t:TokenType/>
            <t:KeyType>
----

.References
* http://cxf.apache.org/docs/ws-trust.html[Cxf & WS-Trust]

ifdef::showscript[]
[.notes]
****

== WS Trust Config

To use WS Trust within a project, 3 actors must be designed; the client calling the Web Service Provider (WSC), the Server exposing the Web Service (WSP) and the Security Token Server (STS).

The Security Token Server is designed like any other Secured Web Service implemented with the Apache CXF framework excepted that we will define a WSDL to expose the service responsible to issue, renew, cancel, validate or request a collection of Security Token.
Policies will be added to this WSDL file in order to authenticate the WSC using a UsernameToken or a X.509 Token. A Symmetric binding is required for the first and an asymmetric (= Public Key) for the second.
Different Java classes must be developed like the SecurityTokenServiceProvider, SAMLTokenProvider, SAMLTokenValidator to support the creation of STS. The Apache CXF project proposes some dummies classes that you can reuse to design your own STS Server.

The WSC, to be able to call the STS server must include within a property of its <jaxws:client/> bean declaration, the bean of the java class "org.apache.cxf.ws.security.trust.STSClient". This class must be parameterized with the
wsdl Location, the endpoint and servicename like also the WS Security keys responsible to setup the client keys store to be used to encrypt the content or to issue STS request appropriately.

The WSC will issue a SOAP Request to the STS server to obtain SAML tokens that will subsequently be used to authenticate/authorize SOAP requests to the WSP that trusts the STS.
WS-Trust shifts the validation of the client from the web service provider to the STS, meaning that the web service provider would not need to be individually configured to trust each client accessing it.
All that is required is that there be a mutual trust relationship between the WSC and the STS.

With WS-Trust, the SAML assertion the WSC receives from the STS is repeatedly used in the WSC's subsequent calls to the WSP until the token expires (5 minutes per CXF default).
However, if (and only if) you are making several calls from the same client, activating WS-SecureConversation between WSC and WSP can result in performance gains.
WS-SecureConversation results in the WSC sending the SAML Assertion just once to the WSP to establish identity; afterwards a simpler security context token (SCT) will be passed from the WSC to the WSP.

The WSDL of the WSC includes a policy or assertion which is used to define how the Issued token to be generated by the STS Server must be conform. Generally, 2 xml tags will be used for that purpose, the Token Type which
is SAMLv2 or SAMLv1 and the key type which is of public type. This policy exists also at the WSP in order to allow the Server to validate the token received against a specific token type.

****
endif::showscript[]