:scrollbar:
:data-uri:
:linkattrs:
:noaudio:

== Endpoint Security

* CXF endpoint security relies on SSL/TLS for HTTPS transport
* Keystores and truststores configured using TLS parameters
* Server side secured using Jetty Engine Factory and Jetty Engine Instance:
+
[source,xml]
----
<httpj:engine-factory id="ClientAuthHttpsSettings">
    <httpj:engine port="9001">
        <http:tlsServerParameters secureSocketProtocol="TLSv1">
            ...
            <sec:keyManagers keyPassword="CertPassword">
              <sec:keyStore type="JKS"
                            password="KeystorePassword"
                            file="certs/CertName.jks"/>
            </sec:keyManagers>
            ...
          </http:tlsServerParameters>
----
+
* Client side secured using `<http:conduit/>`:
+
[source,xml]
----
<http:conduit id="{Namespace}PortName.http-conduit">
  <http:tlsClientParameters>
    ...
    <sec:keyManagers keyPassword="CertPassword">
      <sec:keyStore type="JKS"
                    password="KeystorePassword"
                    file="certs/CertName.jks"/>
    </sec:keyManagers>
    ...
  </http:tlsClientParameters>
</http:conduit>
----

.Reference
* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_CXF_Security_Guide/ConfigTLS.html[Configuring HTTPS^]


ifdef::showscript[]

Transcript:

The CXF endpoint is a web service that is exposed to clients using a transport connector. The transport connectors that the Apache CXF framework supports include local, HTTP, HTTPS, TCP, UDP, JMS, and WebSocket. This module discusses only the HTTP transport connector, which is the most common. Most of the information discussed in this module can also be applied to other transport connectors that use the same technology to secure an endpoint, such as JMS and WebSpot.

You can use the HTTP transport connector within a JBoss Fuse project if the corresponding JAR file is included within the Java classpath of the application, deployed as a bundle into a JBoss Fuse container, or deployed as a module on Red Hat JBoss Enterprise Application Platform (JBoss EAP).

To use the Jetty web component serving an HTTP connector for clients sending Simple Object Access Protocol, or SOAP, XML messages, you use the Maven artifact `cxf-rt-transports-http-jetty`.

To secure the HTTP endpoint using the SSL/TLS Protocol, you use a Jetty engine factory bean to instantiate a Jetty server and pass the bean as a parameter that defines the TLS server parameters. The TLS server parameters include the key manager properties to point to the Java keystore of the server as well as the password to use to access the keys or certificates packaged within the KeyManager store. If a TrustManager is required, you also use the TLS server parameters to configure it.

To configure this secured HTTP transport connector on the server side, use the Java class `org.apache.cxf.configuration.jsse.TLSServerParameters`. Alternatively, configure the transport connector as a Spring bean with the XML tag `<http:tlsServerParameters>`, as shown here.

You configure the TLS client parameters on the client side within the HTTP conduit using a Spring bean with the XML tag `<http:tlsClientParameters>`.

Note that you can also define the cipher suites, which are a Java crypto-algorithm used to encrypt and decrypt or sign and digest messages, as a property such as which version of TLS/SSL protocol to use.

endif::showscript[]
