:noaudio:

[#ws-security]
== WS Security

* WS Security extends SOAP specification
* To secure the SOAP Message :
** Pass Username token with digested, base64 password
** Encrypt messages or parts of messages
** Sign messages
** Timestamp messages

* Implemented mainly using Apache WSS4J with interceptor (IN/OUT)

.References
* https://www.oasis-open.org/committees/download.php/16790/wss-v1.1-spec-os-SOAPMessageSecurity.pdf[WS-Security Spec 1.1]

* http://cxf.apache.org/docs/ws-security.html[CXF & WS-Security]
* http://www.oasis-open.org/committees/download.php/16782/wss-v1.1-spec-os-UsernameTokenProfile.pdf[Username Token Profile], http://www.oasis-open.org/committees/download.php/16785/wss-v1.1-spec-os-x509TokenProfile.pdf[X.509 Token Profile]

ifdef::showscript[]
[.notes]
****

== WS Security

The goal of the Web Service Security Spec is to provide SOAP extensions that can be used when building secure Web services to implement message content integrity and confidentiality. The security can be designed using different
security models including PKI, Kerberos or SSL or security token formats, encryption technologies or signature formats.

The WS Security specification provides three main mechanisms; the ability to send a security token (aka a user name token with a digested or base 64 password) associated or not with a TimeStamp and a time to live value;
message integrity where the messages will be signed and digested and message confidentiality using an encryption algorithm.

The WS Security specification is mainly implemented within the Apache CXF framework using the Apache WSS4J Project and WSS4J Interceptors which are placed in the chain of the CXF interceptors into the Incoming or Outgoing flow.

When a Kerberos or X509 Token is required instead of the UserName token which is defined as clear text within the XML SOAP Header, then a Binary Format with a specific encoding and decoding will be used.

****
endif::showscript[]