:noaudio:

[#ws-security-policy]
== WS Security Policy

* Goal : apply policies that modify the semantics of connections and communications at runtime in a Web services application
* Policy +<wsp:Policy>+ can be assigned to the Port section of the WSDL file
+
[source,xml]
----
<wsdl:service name="PingService10">
    <wsdl:port name="UserNameOverTransport_IPingService" binding="BindingName">
      <wsp:Policy>
        <!-- Policy expression comes here! -->
      </wsp:Policy>
      <soap:address location="SOAPAddress"/>
    </wsdl:port>
----

* Or as a reference
+
[source,xml]
----
<wsdl:service name="PingService10">
    <wsdl:port name="UserNameOverTransport_IPingService" binding="BindingName">
 <wsp:PolicyReference URI="#PolicyID"/>
      <soap:address location="SOAPAddress"/>
    </wsdl:port>
  </wsdl:service>
  ...
  <wsp:Policy wsu:Id="PolicyID">
    <!-- Policy expression comes here ... -->
  </wsp:Policy>
----

.References
* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_CXF_Security_Guide/WsPolicy.html#WsPolicy-Intro[Fuse CXF Security doc]

ifdef::showscript[]
[.notes]
****

== WS Security Policy

The WS Security Policy like the WS Security specification extends the SOAP Specification but is based on Policies.
The Web Services policies have been defined within the WS-Policy specification and define a framework for allowing web services to express their constraints and requirements.
Such constraints and requirements are expressed as security policy assertions for the WS-SecurityPolicy specification with respect to security features provided in SOAP Message Security [WSS10, WSS11].

As such policies can't be defined using Java Annotations, by consequence, it is only possible to use the WS-Security Policy using the approach WSDL to Java.

The Policy Assertions are defined within the namespace +http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702+ which is associated by convention to the prefix wsp and will describe how messages are to be secured.

****
endif::showscript[]