:scrollbar:
:data-uri:
:linkattrs:


== WS-Trust

.Configuration

* STS: Designed as secured web service and WS-Trust WSDL
* Web service provider (WSP): Web service and WS-Trust policies
* Web service client (WSC): Web service acting as a STS client and WS-Trust policies

* Example:
+
[source,xml]
----
...
<sp:AsymmetricBinding>
  <wsp:Policy>
    <!--
          The sp:InitiatorToken element specifies the elements required in
          generating the initiator request to the ws-provider's service.
    -->
    <sp:InitiatorToken>
      <wsp:Policy>
        <sp:IssuedToken
                  sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
          <sp:RequestSecurityTokenTemplate>
            <t:TokenType/>
            <t:KeyType>
----

.Reference
* link:http://cxf.apache.org/docs/ws-trust.html["WS-Trust^"]

ifdef::showscript[]

Transcript:

To use WS-Trust within a project, you must design three components: the STS, the client calling the web service provider, and the server exposing the web service.

The STS is designed like any other secured web service implemented with the Apache CXF framework, with one exception: Here you define a WSDL to expose the service responsible for issuing, renewing, canceling, validating, or requesting collection of a security token.

You add policies to this WSDL file to authenticate the web service client, or WSC, using a username token or an X.509 token. A username token requires a symmetric binding, while an X.509 token requires an asymmetric binding.

To support creation of the STS, you must develop a number of Java classes, including `SecurityTokenServiceProvider`, `SAMLTokenProvider`, and `SAMLTokenValidator`. The Apache CXF project proposes some dummy classes that you can modify to design your own STS server.

To call the STS server, the WSC must include the bean of the  `org.apache.cxf.ws.security.trust.STSClient` Java class within a property of its `<jaxws:client/>` bean declaration. This class must be parameterized with the WSDL location, the endpoint, and the service name. It must also contain the WS security keys responsible for setting up the client keystore that is used to encrypt the content or issue STS requests.

The WSC issues a SOAP request to the STS server to obtain SAML tokens that are subsequently used to authenticate and authorize SOAP requests to the WSP that trusts the STS.

WS-Trust shifts the validation of the client from the web service provider to the STS, meaning that you do not need to configure the web service provider to trust each client accessing it individually. All that is required is a mutual trust relationship between the WSC and the STS.

With WS-Trust, the SAML assertion the WSC receives from the STS is used repeatedly in the WSC's subsequent calls to the WSP until the token expires. The CXF default is 5 minutes.

However, if--and only if--you are making several calls from the same client, activating `WS-SecureConversation` between the WSC and WSP can result in performance gains. `WS-SecureConversation` results in the WSC sending the SAML assertion to the WSP only one time, to establish identity. After that, a simpler security context token is passed from the WSC to the WSP.

The WSDL of the WSC includes a policy or assertion that defines the requirements for the token to be generated by the STS server. Generally, two XML tags are used: the token type, which is SAMLv2 or SAMLv1, and the key type, which is `public`. This policy also exists at the WSP to allow the server to validate the token received against a specific token type.

endif::showscript[]
