:noaudio:

[#suggested-readings]
== Suggested Readings & work

.Exercise yourself
* Read Camel & CXF chapter within the Camel Development with JBoss Fuse course
* Develop some Camel & CXF Camel Routes
* Use the CXF Maven plugin to generate the Java code from the WSDL or WSDL from Java Annotated classes

.Readings
* http://www.javaworld.com/article/2073287/soa/secure-web-services.html[Secure Web Service]
* https://www.digitalocean.com/community/tutorials/java-keytool-essentials-working-with-java-keystores[Keytool & Keystore]
* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Security_Guide/CreateCerts.html[Manage your certificates]

ifdef::showscript[]
[.notes]
****

== Suggested Readings & work

In order to prepare this module, we suggest that you review the links provided but also that you read the chapter about Camel & CXF within the Camel Development with JBoss Fuse course, that you create some projects
using your WSDL file and expose a Web Service from a Camel Route that you will consume from another Camel Route playing the role of a client. Exercise tyourself to also use the CXF Maven Plugins reponsioble to generate the Java
classes from the WSDL file of the WSDL file from the Java Annotated Classes.

****
endif::showscript[]