:scrollbar:
:data-uri:
:linkattrs:
:noaudio:

== WS-SecurityPolicy

* Goal: Apply policies that modify the semantics of connections and communications at runtime in web services application
* Policy `<wsp:Policy>` can be assigned to `Port` section of WSDL file:
+
[source,xml]
----
<wsdl:service name="PingService10">
    <wsdl:port name="UserNameOverTransport_IPingService" binding="BindingName">
      <wsp:Policy>
        <!-- Policy expression comes here! -->
      </wsp:Policy>
      <soap:address location="SOAPAddress"/>
    </wsdl:port>
----

* Or as reference:
+
[source,xml]
----
<wsdl:service name="PingService10">
    <wsdl:port name="UserNameOverTransport_IPingService" binding="BindingName">
 <wsp:PolicyReference URI="#PolicyID"/>
      <soap:address location="SOAPAddress"/>
    </wsdl:port>
  </wsdl:service>
  ...
  <wsp:Policy wsu:Id="PolicyID">
    <!-- Policy expression comes here ... -->
  </wsp:Policy>
----

.References
* link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2.1/html/Apache_CXF_Security_Guide/WsPolicy.html#WsPolicy-Intro["The WS-Policy Framework^"]

* link:http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702[Policy assertion namespace^]

ifdef::showscript[]

Transcript:

Similar to the WS-Security specification, WS-SecurityPolicy extends the SOAP specification--but in this case, it is based on policies.

Within the WS-Policy specification, web services policies are defined as a framework for allowing web services to express their constraints and requirements.

Such constraints and requirements are expressed as security policy assertions for the WS-SecurityPolicy specification with respect to security features provided in SOAP message security. These assertions include Wss10 and Wss11.

You cannot define these policies using Java annotations. Instead, you must use the Web Services Description Language, or WSDL, approach to Java.

The policy assertions are defined within the namespace shown in the references. By convention, this namespace is associated with the prefix `wsp` and describes how messages are to be secured.

In general, a `<wsp:Policy/>` element is composed of multiple policy settings. Each individual policy setting is specified as a set of policy assertions. Therefore, the policy defined by a `wsp:Policy` element is really a composite object.

The content of the `wsp:Policy` element is called a _policy expression_. A policy expression consists of various logical combinations of the basic policy assertions. By tailoring the syntax of the policy expression, you can determine which combinations of policy assertions must be satisfied at runtime to satisfy the overall policy.

As you build the policy from the policy assertions, you can qualify it using the `wsp:Optional` attribute, as well as various nested combinations of the `wsp:All` and `wsp:ExactlyOne` elements. Combining these elements lets you produce a range of acceptable policy alternatives.

There are two ways to configure policies. The first way is to define them in the WSDL file in the `<wsdl:port/>` section. Alternatively, you can refer to policies within the port binding section using `<PolicyReference/>`.

You can assign a policy globally to bind a service, or define a policy that you assign to the input or output body message. You typically use such a policy to specify that the body must be signed and/or encrypted, similar to the header section.

Note that the WS-SecurityPolicy fragment does not include everything needed for a runtime to be able to create messages. It does not describe things such as locations of keystores, usernames, passwords, and so on. Those elements need to be configured at runtime to augment the WS-SecurityPolicy fragment.


endif::showscript[]
