:noaudio:

[#ws-security-policy-external]
== WS Security Policy

* Externalized in a XML file and passed as parameter to a +<jaws:endpoint/>+ using a +<feature/>+
+
[source,xml]
----
<jaxws:features>
    <p:policies>
        <wsp:PolicyReference xmlns:wsp="http://www.w3.org/ns/ws-policy" URI="classpath:/to/my/policy.xml"/>
    </p:policies>
</jaxws:features>
----

.References
* http://docs.oasis-open.org/ws-sx/ws-securitypolicy/v1.3/errata01/ws-securitypolicy-1.3-errata01.html[WS Security Spec]
* http://cxf.apache.org/docs/ws-securitypolicy.html[CXF & WS Security Policy]

ifdef::showscript[]
[.notes]
****

== WS Security Policy

The second approach that Apache CXF supports consist to define the policies within a separate file. The reference (file, classpath) of the file will be passed as a CXF Policies features as you can see within the snippet code
example of this slide.

The policies feature enables and configures the CXF Policy Framework. It can have any number of Policy or PolicyReference child elements.

You can assign such policies globally by attaching them to the CXF Bus. Then, they will be applied to all the client and server endpoints created on that bus.

The advantage of this approach is that you can maintain and manage the WSDL contract file separately from the Security Policies within your project's team.

****
endif::showscript[]