:scrollbar:
:data-uri:
:linkattrs:
:noaudio:

== Payload Encryption/Decryption

* SOAP body, element, element content level can be encrypted/decrypted
* XML encryption capability provided by Apache Santuario project
* Symmetric encryption/decryption currently supported using Triple-DES and AES (128, 192, and 256)
* Encryption uses Apache Camel `marshall` processor
* Decryption uses Apache Camel `unmarshall` processor

* Camel route example:
+
[source,xml]
----
from("direct:start")
    .marshal().secureXML()
    .unmarshal().secureXML()
    .to("direct:end");
----

.References
* link:http://camel.apache.org/xmlsecurity-dataformat.html[XMLSecurity Data Format^]
* link:http://santuario.apache.org/[Apache Santuario^]

ifdef::showscript[]

Transcript:

Instead of using WS-Security or WS-SecurityPolicy, you can use the Apache Camel XML security component and data format to encrypt/decrypt or sign/digest the content of the SOAP message elements: body, header, and attachment. In this case, the CXF web service provider endpoint must be encapsulated using the Apache Camel CXF component to let the Apache Camel route collect and process the HTTP request containing the SOAP message and then call the processor in charge to encrypt or decrypt the content.

The API responsible for encrypting/signing the XML elements is provided by the Apache Santuario project, which is used by the Apache Camel XML security component and data format. This project includes the standard Java XML Digital Signature, or JSR-105, API, which is a mature DOM-based implementation of XML signature and XML encryption. The project also includes a more recent StAX-based streaming XML signature and XML encryption implementation.

Symmetric encryption and decryption is currently supported using Triple-DES and AES (128, 192, and 256).

To encrypt the content of the XML element, include a marshaller within your Apache Camel route. To decrypt the content, set up an unmarshaller.

Different parameters exist for configuring `org.apache.camel.model.dataformat.XMLSecurityDataFormat`. Here are some examples:

* The `secureTag` property allows you to define the XPath to access the XML elements within the XML content. If this parameter is not defined, then all XML content is encrypted or decrypted.
* The `secureTagContents` property is a Boolean value used to specify if you want to include the XML element or only the child elements.
* The `xmlCipherAlgorithm` property allows you to specify the algorithm to be used.
* The `keyOrTrustStoreParameters` parameter lets you configure the location of the keystores using another Camel bean.


endif::showscript[]
